# Generated by Django 5.2.9 on 2026-01-19 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー'),
        ),
    ]
