# Generated by Django 5.2.9 on 2026-06-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_nativepushtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='call_recordings/', verbose_name='録音ファイル')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIMEタイプ')),
                ('file_size', models.BigIntegerField(verbose_name='ファイルサイズ')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='録音時間（秒）')),
                ('recording_started_at', models.DateTimeField(blank=True, null=True, verbose_name='録音開始日時')),
                ('recording_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='録音終了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_recordings', to=settings.AUTH_USER_MODEL, verbose_name='録音登録者')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='notifications.callsession', verbose_name='通話セッション')),
            ],
            options={
                'verbose_name': '通話録音',
                'verbose_name_plural': '通話録音',
                'db_table': 'call_recordings',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
