# Generated by Django 5.2.9 on 2026-08-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_callrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='transcript',
            field=models.TextField(blank=True, default='', verbose_name='文字起こし'),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='transcript_language',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='検出言語'),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='transcript_status',
            field=models.CharField(blank=True, choices=[('pending', '処理待ち'), ('processing', '処理中'), ('done', '完了'), ('failed', '失敗')], default='', max_length=20, verbose_name='文字起こし状態'),
        ),
    ]
