# Generated by Django 5.2.9 on 2026-10-02 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_callrecording_transcript_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('request', '要望'), ('bug', '不具合'), ('question', '問い合わせ'), ('other', 'その他')], max_length=20, verbose_name='種類')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('body', models.TextField(verbose_name='内容')),
                ('status', models.CharField(choices=[('PENDING', '未対応'), ('IN_PROGRESS', '対応中'), ('DONE', '完了'), ('REJECTED', '却下')], default='PENDING', max_length=20, verbose_name='状況')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='却下理由')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='最終対応日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_user_request_tasks', to=settings.AUTH_USER_MODEL, verbose_name='最終対応者')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_request_tasks', to=settings.AUTH_USER_MODEL, verbose_name='依頼者')),
            ],
            options={
                'verbose_name': 'システム管理者リクエスト',
                'verbose_name_plural': 'システム管理者リクエスト',
                'db_table': 'notifications_user_request_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='notificatio_status_f1abdf_idx')],
            },
        ),
    ]
