# Generated by Django 5.2.9 on 2026-01-14 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部署名')),
                ('level', models.CharField(choices=[('division', '事業部'), ('group', '係'), ('team', '班')], max_length=20, verbose_name='階層')),
                ('display_id', models.IntegerField(verbose_name='表示順')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.department', verbose_name='親部署')),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署',
                'db_table': 'accounts_department',
                'ordering': ['display_id', 'id'],
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('employee_code', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='社員コード')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='役職')),
                ('role', models.CharField(choices=[('staff', '一般'), ('supervisor', '班長'), ('chief', '係長'), ('manager', '事業部長')], default='staff', max_length=20, verbose_name='役割')),
                ('employment_type', models.CharField(choices=[('regular', '正社員'), ('skilled', '特定技能実習生'), ('intern', '実習生'), ('temporary', '人材派遣')], default='regular', max_length=20, verbose_name='雇用形態')),
                ('division', models.CharField(blank=True, max_length=100, verbose_name='事業部')),
                ('group', models.CharField(blank=True, max_length=100, verbose_name='係')),
                ('team', models.CharField(blank=True, max_length=100, verbose_name='班')),
                ('joined_on', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department', verbose_name='所属部署')),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
                'db_table': 'accounts_userprofile',
            },
        ),
    ]
