# Generated by Django 5.2.9 on 2026-01-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersmtpconfig',
            table='accounts_user_smtp_configs',
        ),
    ]
