# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_department_position_permission'),
    ]

    operations = [
        # division を CharField から ForeignKey に変更
        migrations.RemoveField(
            model_name='userprofile',
            name='division',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='division',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'level': 'division'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='division_users',
                to='accounts.department',
                verbose_name='事業部'
            ),
        ),
        # group を CharField から ForeignKey に変更
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'level': 'group'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='group_users',
                to='accounts.department',
                verbose_name='係'
            ),
        ),
        # team を CharField から ForeignKey に変更
        migrations.RemoveField(
            model_name='userprofile',
            name='team',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'level': 'team'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='team_users',
                to='accounts.department',
                verbose_name='班'
            ),
        ),
    ]
