# Generated by Django 5.2.9 on 2026-02-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_departmentpermission_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpermission',
            name='resource',
            field=models.CharField(choices=[('dashboard', 'ダッシュボード'), ('orders', '受注'), ('production', '生産'), ('production.process_input', '生産: 工程作業入力'), ('production.record_edit', '生産: 実績変更'), ('production.scrap_record', '生産: 仕損品記録'), ('production.plan_input', '生産: 生産計画入力'), ('production.inventory', '生産: 在庫/残量一覧'), ('production.scrap_history', '生産: 仕損履歴'), ('production.progress', '生産: 進捗管理'), ('production.line_demands', '生産: ライン需要一覧'), ('production.line_calendars', '生産: ライン勤務カレンダ'), ('production.stock_allocations', '生産: 在庫引当'), ('production.orders', '生産: 製造指示'), ('production.sequence_board', '生産: ミックス順序ボード'), ('production.line_monitor', '生産: ライン稼働監視'), ('production.mobile_input', '生産: モバイル作業入力（ライン）'), ('purchase', '仕入'), ('shipping', '出荷'), ('inventory', '在庫'), ('quality', '品質'), ('notifications', '通知'), ('engineering_change', '設変'), ('masters', 'マスタ'), ('settings', '設定'), ('settings.profile', '設定: プロフィール編集'), ('settings.users', '設定: ユーザー管理'), ('settings.user_permissions', '設定: ユーザー権限編集'), ('settings.permission_templates', '設定: 権限テンプレート'), ('settings.smtp', '設定: SMTP設定'), ('settings.purchase_plan_lock', '設定: 仕入計画ロック設定'), ('settings.production_plan_lock', '設定: 生産計画ロック設定'), ('settings.scheduled_tasks', '設定: 定時タスク設定'), ('settings.stocktake_init', '設定: 棚卸初期化'), ('users', 'ユーザー管理'), ('manual', 'マニュアル')], max_length=50),
        ),
        migrations.AlterField(
            model_name='departmentpositionpermission',
            name='resource',
            field=models.CharField(choices=[('dashboard', 'ダッシュボード'), ('orders', '受注'), ('production', '生産'), ('production.process_input', '生産: 工程作業入力'), ('production.record_edit', '生産: 実績変更'), ('production.scrap_record', '生産: 仕損品記録'), ('production.plan_input', '生産: 生産計画入力'), ('production.inventory', '生産: 在庫/残量一覧'), ('production.scrap_history', '生産: 仕損履歴'), ('production.progress', '生産: 進捗管理'), ('production.line_demands', '生産: ライン需要一覧'), ('production.line_calendars', '生産: ライン勤務カレンダ'), ('production.stock_allocations', '生産: 在庫引当'), ('production.orders', '生産: 製造指示'), ('production.sequence_board', '生産: ミックス順序ボード'), ('production.line_monitor', '生産: ライン稼働監視'), ('production.mobile_input', '生産: モバイル作業入力（ライン）'), ('purchase', '仕入'), ('shipping', '出荷'), ('inventory', '在庫'), ('quality', '品質'), ('notifications', '通知'), ('engineering_change', '設変'), ('masters', 'マスタ'), ('settings', '設定'), ('settings.profile', '設定: プロフィール編集'), ('settings.users', '設定: ユーザー管理'), ('settings.user_permissions', '設定: ユーザー権限編集'), ('settings.permission_templates', '設定: 権限テンプレート'), ('settings.smtp', '設定: SMTP設定'), ('settings.purchase_plan_lock', '設定: 仕入計画ロック設定'), ('settings.production_plan_lock', '設定: 生産計画ロック設定'), ('settings.scheduled_tasks', '設定: 定時タスク設定'), ('settings.stocktake_init', '設定: 棚卸初期化'), ('users', 'ユーザー管理'), ('manual', 'マニュアル')], max_length=50),
        ),
        migrations.AlterField(
            model_name='positionpermission',
            name='resource',
            field=models.CharField(choices=[('dashboard', 'ダッシュボード'), ('orders', '受注'), ('production', '生産'), ('production.process_input', '生産: 工程作業入力'), ('production.record_edit', '生産: 実績変更'), ('production.scrap_record', '生産: 仕損品記録'), ('production.plan_input', '生産: 生産計画入力'), ('production.inventory', '生産: 在庫/残量一覧'), ('production.scrap_history', '生産: 仕損履歴'), ('production.progress', '生産: 進捗管理'), ('production.line_demands', '生産: ライン需要一覧'), ('production.line_calendars', '生産: ライン勤務カレンダ'), ('production.stock_allocations', '生産: 在庫引当'), ('production.orders', '生産: 製造指示'), ('production.sequence_board', '生産: ミックス順序ボード'), ('production.line_monitor', '生産: ライン稼働監視'), ('production.mobile_input', '生産: モバイル作業入力（ライン）'), ('purchase', '仕入'), ('shipping', '出荷'), ('inventory', '在庫'), ('quality', '品質'), ('notifications', '通知'), ('engineering_change', '設変'), ('masters', 'マスタ'), ('settings', '設定'), ('settings.profile', '設定: プロフィール編集'), ('settings.users', '設定: ユーザー管理'), ('settings.user_permissions', '設定: ユーザー権限編集'), ('settings.permission_templates', '設定: 権限テンプレート'), ('settings.smtp', '設定: SMTP設定'), ('settings.purchase_plan_lock', '設定: 仕入計画ロック設定'), ('settings.production_plan_lock', '設定: 生産計画ロック設定'), ('settings.scheduled_tasks', '設定: 定時タスク設定'), ('settings.stocktake_init', '設定: 棚卸初期化'), ('users', 'ユーザー管理'), ('manual', 'マニュアル')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='resource',
            field=models.CharField(choices=[('dashboard', 'ダッシュボード'), ('orders', '受注'), ('production', '生産'), ('production.process_input', '生産: 工程作業入力'), ('production.record_edit', '生産: 実績変更'), ('production.scrap_record', '生産: 仕損品記録'), ('production.plan_input', '生産: 生産計画入力'), ('production.inventory', '生産: 在庫/残量一覧'), ('production.scrap_history', '生産: 仕損履歴'), ('production.progress', '生産: 進捗管理'), ('production.line_demands', '生産: ライン需要一覧'), ('production.line_calendars', '生産: ライン勤務カレンダ'), ('production.stock_allocations', '生産: 在庫引当'), ('production.orders', '生産: 製造指示'), ('production.sequence_board', '生産: ミックス順序ボード'), ('production.line_monitor', '生産: ライン稼働監視'), ('production.mobile_input', '生産: モバイル作業入力（ライン）'), ('purchase', '仕入'), ('shipping', '出荷'), ('inventory', '在庫'), ('quality', '品質'), ('notifications', '通知'), ('engineering_change', '設変'), ('masters', 'マスタ'), ('settings', '設定'), ('settings.profile', '設定: プロフィール編集'), ('settings.users', '設定: ユーザー管理'), ('settings.user_permissions', '設定: ユーザー権限編集'), ('settings.permission_templates', '設定: 権限テンプレート'), ('settings.smtp', '設定: SMTP設定'), ('settings.purchase_plan_lock', '設定: 仕入計画ロック設定'), ('settings.production_plan_lock', '設定: 生産計画ロック設定'), ('settings.scheduled_tasks', '設定: 定時タスク設定'), ('settings.stocktake_init', '設定: 棚卸初期化'), ('users', 'ユーザー管理'), ('manual', 'マニュアル')], max_length=50),
        ),
    ]
