# Generated by Django 5.2.9 on 2026-03-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_departmentpermission_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unit',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 'unit'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_users', to='accounts.department', verbose_name='グループ'),
        ),
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('division', '事業部'), ('group', '係'), ('team', '班'), ('unit', 'グループ')], max_length=20, verbose_name='階層'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('staff', '一般'), ('leader', 'リーダー'), ('supervisor', '班長'), ('chief', '係長'), ('manager', '事業部長')], default='staff', max_length=20, verbose_name='役割'),
        ),
    ]
