# Generated by Django 5.2.9 on 2026-03-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_refactor_role_and_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_teams',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level': 'team'}, related_name='supervisor_users', to='accounts.department', verbose_name='班長担当班'),
        ),
    ]
