# Generated by Django 5.2.9 on 2026-03-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_supervisor_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leader_units',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level': 'unit'}, related_name='leader_users', to='accounts.department', verbose_name='リーダー担当グループ'),
        ),
    ]
