# Generated by Django 5.2.9 on 2026-03-20 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_record_inquiry_permission_resource'),
        ('masters', '0037_merge_0027_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitLineMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_default', models.BooleanField(default=False, verbose_name='初期ライン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('unit', models.ForeignKey(limit_choices_to={'level': 'unit'}, on_delete=django.db.models.deletion.CASCADE, related_name='line_mappings', to='accounts.department', verbose_name='グループ')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_mappings', to='masters.line', verbose_name='ライン')),
            ],
            options={
                'verbose_name': 'グループライン紐付',
                'verbose_name_plural': 'グループライン紐付',
                'db_table': 'accounts_unit_line_mapping',
                'ordering': ['unit_id', '-is_default', 'sort_order', 'id'],
                'unique_together': {('unit', 'line')},
            },
        ),
    ]
