# Generated by Django 5.2.9 on 2026-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_departmentpermission_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='approver_app_notification_enabled',
            field=models.BooleanField(default=True, verbose_name='承認者アプリ通知'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='approver_email_notification_enabled',
            field=models.BooleanField(default=False, verbose_name='承認者メール通知'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='approver_task_enabled',
            field=models.BooleanField(default=True, verbose_name='承認者タスク作成'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='creator_app_notification_enabled',
            field=models.BooleanField(default=True, verbose_name='作成者アプリ通知'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='creator_email_notification_enabled',
            field=models.BooleanField(default=False, verbose_name='作成者メール通知'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='creator_task_enabled',
            field=models.BooleanField(default=True, verbose_name='作成者タスク作成'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='reviewer1_app_notification_enabled',
            field=models.BooleanField(default=True, verbose_name='確認者1アプリ通知'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='reviewer1_email_notification_enabled',
            field=models.BooleanField(default=False, verbose_name='確認者1メール通知'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='reviewer1_task_enabled',
            field=models.BooleanField(default=True, verbose_name='確認者1タスク作成'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='reviewer2_app_notification_enabled',
            field=models.BooleanField(default=True, verbose_name='確認者2アプリ通知'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='reviewer2_email_notification_enabled',
            field=models.BooleanField(default=False, verbose_name='確認者2メール通知'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='reviewer2_task_enabled',
            field=models.BooleanField(default=True, verbose_name='確認者2タスク作成'),
        ),
    ]
