# Generated by Django 5.2.9 on 2026-09-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_approvalrouteconfig_approved_result_app_notification_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='reviewer2_enabled',
            field=models.BooleanField(default=True, verbose_name='確認者2使用'),
        ),
    ]
