# Generated by Django 5.2.9 on 2026-09-09 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_approvalrouteconfig_reviewer2_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', '作成済み'), ('reviewing', '確認中'), ('approved', '承認済み'), ('rejected', '却下'), ('sent', '送信済み')], default='created', max_length=20, verbose_name='ステータス')),
                ('current_stage', models.CharField(choices=[('creator', '作成者'), ('reviewer1', '確認①'), ('reviewer2', '確認②'), ('approver', '承認者'), ('completed', '完了')], default='creator', max_length=20, verbose_name='現在の段階')),
                ('context', models.JSONField(default=dict, verbose_name='申請コンテキスト')),
                ('pdf_file', models.FileField(blank=True, default='', upload_to='approval/', verbose_name='PDFファイル')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='却下理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('route_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='accounts.approvalrouteconfig', verbose_name='承認ルート設定')),
            ],
            options={
                'verbose_name': '承認申請',
                'verbose_name_plural': '承認申請',
                'db_table': 'accounts_approval_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('creator', '作成者'), ('reviewer1', '確認①'), ('reviewer2', '確認②'), ('approver', '承認者'), ('completed', '完了')], max_length=20, verbose_name='段階')),
                ('action', models.CharField(choices=[('confirmed', '確認済み'), ('approved', '承認'), ('rejected', '却下')], max_length=20, verbose_name='アクション')),
                ('comment', models.TextField(blank=True, default='', verbose_name='コメント')),
                ('acted_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounts.approvalrequest', verbose_name='承認申請')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
            ],
            options={
                'verbose_name': '承認ステップ',
                'verbose_name_plural': '承認ステップ',
                'db_table': 'accounts_approval_step',
                'ordering': ['acted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('CREATOR_CREATE', '作成'), ('REVIEWER1_REVIEW', '確認①'), ('REVIEWER2_REVIEW', '確認②'), ('APPROVER_APPROVE', '承認'), ('CREATOR_FIX', '差戻し修正')], max_length=30, verbose_name='タスク種別')),
                ('status', models.CharField(choices=[('PENDING', '未処理'), ('DONE', '完了'), ('SKIPPED', 'スキップ')], default='PENDING', max_length=10, verbose_name='ステータス')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.approvalrequest', verbose_name='承認申請')),
            ],
            options={
                'verbose_name': '承認タスク',
                'verbose_name_plural': '承認タスク',
                'db_table': 'accounts_approval_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
