# Generated by Django 5.2.9 on 2026-09-24 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_alter_departmentpermission_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='approver_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_route_approver', to='accounts.department', verbose_name='承認者部署'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='creator_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_route_creator', to='accounts.department', verbose_name='作成者部署'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='reviewer1_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_route_reviewer1', to='accounts.department', verbose_name='確認者1部署'),
        ),
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='reviewer2_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_route_reviewer2', to='accounts.department', verbose_name='確認者2部署'),
        ),
    ]
