# Generated by Django 5.2.9 on 2026-09-24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_approval_route_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrouteconfig',
            name='creator_authorized_users',
            field=models.ManyToManyField(blank=True, related_name='approval_route_creator_authorized', to=settings.AUTH_USER_MODEL, verbose_name='作成可能ユーザー'),
        ),
    ]
