# Generated by Django 5.2.9 on 2026-10-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_departmentpermission_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_system_admin',
            field=models.BooleanField(default=False, verbose_name='システム管理者'),
        ),
    ]
