# Generated by Django 5.2.9 on 2026-09-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0084_add_two_person_only_to_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ライン名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '勤務ライン',
                'verbose_name_plural': '勤務ライン',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作業者名')),
                ('shift_type', models.CharField(choices=[('朝', '朝勤'), ('昼', '昼勤'), ('夜', '夜勤')], default='朝', max_length=2, verbose_name='勤務帯')),
                ('work_start', models.TimeField(default='08:00', verbose_name='出勤時刻')),
                ('work_end', models.TimeField(default='17:00', verbose_name='退勤時刻')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='shifts.shiftline', verbose_name='勤務ライン')),
            ],
            options={
                'verbose_name': 'シフト作業者',
                'verbose_name_plural': 'シフト作業者',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('work_hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='実働時間(h)')),
                ('units', models.IntegerField(default=0, verbose_name='台数')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                ('shift_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shifts.shiftline', verbose_name='勤務ライン')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shifts.shiftworker', verbose_name='作業者')),
            ],
            options={
                'verbose_name': 'シフト配置',
                'verbose_name_plural': 'シフト配置',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftLineProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#64748b', max_length=7, verbose_name='表示色')),
                ('required_hours', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='必要時間(h)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                ('shift_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_processes', to='shifts.shiftline', verbose_name='勤務ライン')),
            ],
            options={
                'verbose_name': 'ライン工程設定',
                'verbose_name_plural': 'ライン工程設定',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('shift_line', 'process')},
            },
        ),
    ]
