# Generated by Django 5.2.9 on 2026-09-15 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0084_add_two_person_only_to_process'),
        ('shifts', '0002_shiftworker_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftlineprocess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='line_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shiftlineprocess', verbose_name='ライン工程/活動'),
        ),
        migrations.AddField(
            model_name='shiftlineprocess',
            name='custom_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='活動名'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程'),
        ),
        migrations.AlterField(
            model_name='shiftlineprocess',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程'),
        ),
    ]
