# Generated by Django 5.2.9 on 2026-05-17 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutsourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='品目コード')),
                ('item_name', models.CharField(max_length=200, verbose_name='品目名称')),
                ('customer_delivery_lt', models.IntegerField(default=2, verbose_name='顧客納入LT（日数）')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '外作品目',
                'verbose_name_plural': '外作品目',
                'db_table': 'outsource_item',
            },
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='外作先名')),
                ('daily_capacity', models.IntegerField(blank=True, null=True, verbose_name='日キャパ（参考値）')),
                ('transport_lt_supply', models.IntegerField(default=1, verbose_name='支給運送LT（日数）')),
                ('transport_lt_delivery', models.IntegerField(default=1, verbose_name='完成品運送LT（日数）')),
                ('notes', models.TextField(blank=True, default='', verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '外作先',
                'verbose_name_plural': '外作先',
                'db_table': 'outsource_subcontractor',
            },
        ),
        migrations.CreateModel(
            name='OutsourceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=100, unique=True, verbose_name='案件番号')),
                ('item_code', models.CharField(max_length=50, verbose_name='品目コード')),
                ('item_name', models.CharField(max_length=200, verbose_name='品目名称')),
                ('order_qty', models.IntegerField(verbose_name='受注数量')),
                ('painting_name', models.CharField(max_length=100, verbose_name='塗装名')),
                ('painting_date', models.DateField(verbose_name='塗装日')),
                ('earliest_start', models.DateField(blank=True, null=True, verbose_name='最早着手日')),
                ('latest_finish', models.DateField(blank=True, null=True, verbose_name='最遅完了日')),
                ('status', models.CharField(choices=[('IMPORTED', '取込済'), ('SENT_TO_SUB', '展開送付済'), ('SPLIT_REGISTERED', '分割計画登録済'), ('IN_PROGRESS', '加工中'), ('COMPLETED', '完了')], default='IMPORTED', max_length=20, verbose_name='ステータス')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取込日時')),
                ('notes', models.TextField(blank=True, default='', verbose_name='備考')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='outsource.outsourceitem', verbose_name='品目')),
            ],
            options={
                'verbose_name': '外作受注',
                'verbose_name_plural': '外作受注',
                'db_table': 'outsource_order',
                'ordering': ['-painting_date', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='OutsourceSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='分割連番')),
                ('process_date', models.DateField(verbose_name='加工予定日')),
                ('qty', models.IntegerField(verbose_name='分割数量')),
                ('material_supplied', models.BooleanField(default=False, verbose_name='材料支給済')),
                ('process_completed', models.BooleanField(default=False, verbose_name='加工完了')),
                ('shipped', models.BooleanField(default=False, verbose_name='出荷済')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='outsource.outsourceorder', verbose_name='案件')),
            ],
            options={
                'verbose_name': '分割計画',
                'verbose_name_plural': '分割計画',
                'db_table': 'outsource_split',
                'ordering': ['order', 'sequence'],
                'unique_together': {('order', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, verbose_name='材料コード')),
                ('material_name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('required_qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='必要数量')),
                ('supply_date', models.DateField(verbose_name='支給予定日')),
                ('supplied_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='支給済数量')),
                ('supplied', models.BooleanField(default=False, verbose_name='支給完了')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='outsource.outsourcesplit', verbose_name='分割計画')),
            ],
            options={
                'verbose_name': '材料所要量',
                'verbose_name_plural': '材料所要量',
                'db_table': 'outsource_material_requirement',
                'ordering': ['supply_date', 'material_code'],
            },
        ),
        migrations.AddField(
            model_name='outsourceitem',
            name='subcontractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='outsource.subcontractor', verbose_name='外作先'),
        ),
        migrations.CreateModel(
            name='OutsourceBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, verbose_name='材料コード')),
                ('material_name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('quantity_per', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='員数（親1個あたり）')),
                ('unit', models.CharField(default='個', max_length=20, verbose_name='単位')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=100, verbose_name='調達先名')),
                ('procurement_lt', models.IntegerField(default=7, verbose_name='材料調達LT（日数）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='outsource.outsourceitem', verbose_name='親品目')),
            ],
            options={
                'verbose_name': '外作BOM',
                'verbose_name_plural': '外作BOM',
                'db_table': 'outsource_bom',
                'unique_together': {('item', 'material_code')},
            },
        ),
    ]
