# Generated by Django 5.2.9 on 2026-05-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0002_materialrequirement_supplier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField(verbose_name='出荷日')),
                ('qty', models.IntegerField(verbose_name='出荷数量')),
                ('person', models.CharField(max_length=50, verbose_name='担当者')),
                ('notes', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='outsource.outsourcesplit', verbose_name='分割計画')),
            ],
            options={
                'verbose_name': '顧客出荷',
                'verbose_name_plural': '顧客出荷',
                'db_table': 'outsource_customer_shipment',
                'ordering': ['shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='納入日')),
                ('qty', models.IntegerField(verbose_name='受入数量')),
                ('inspector', models.CharField(max_length=50, verbose_name='検収者')),
                ('notes', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='outsource.outsourcesplit', verbose_name='分割計画')),
            ],
            options={
                'verbose_name': '外作先納入',
                'verbose_name_plural': '外作先納入',
                'db_table': 'outsource_subcontractor_delivery',
                'ordering': ['delivery_date'],
            },
        ),
    ]
