# Generated by Django 5.2.9 on 2026-05-18 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0050_product_unit_price'),
        ('outsource', '0003_add_delivery_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsourcebom',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier', verbose_name='調達先'),
        ),
        migrations.AlterField(
            model_name='outsourcebom',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='調達先名（自動）'),
        ),
    ]
