# Generated by Django 5.2.9 on 2026-05-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0004_bom_supplier_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsourceitem',
            name='product_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='品番'),
        ),
    ]
