# Generated by Django 5.2.9 on 2026-05-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0005_item_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequirement',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='発注済'),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='ordered_at',
            field=models.DateField(blank=True, null=True, verbose_name='発注日'),
        ),
    ]
