# Generated by Django 5.2.9 on 2026-05-18 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0050_product_unit_price'),
        ('outsource', '0006_add_material_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsourceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, unique=True, verbose_name='材料コード')),
                ('material_name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=100, verbose_name='調達先名（自動）')),
                ('procurement_lt', models.IntegerField(default=7, verbose_name='調達LT（日数）')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier', verbose_name='調達先')),
            ],
            options={
                'verbose_name': '構成品',
                'verbose_name_plural': '構成品',
                'db_table': 'outsource_material',
                'ordering': ['material_code'],
            },
        ),
        migrations.AddField(
            model_name='outsourcebom',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_usages', to='outsource.outsourcematerial', verbose_name='構成品'),
        ),
    ]
