# Generated by Django 5.2.9 on 2026-05-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0011_materialrequirement_material_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('updated_count', models.IntegerField(default=0, verbose_name='更新件数')),
                ('warning_count', models.IntegerField(default=0, verbose_name='警告件数')),
                ('error_count', models.IntegerField(default=0, verbose_name='エラー件数')),
                ('detail', models.JSONField(default=dict, verbose_name='取込詳細')),
                ('imported_by', models.CharField(blank=True, default='', max_length=100, verbose_name='取込者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '分割計画取込履歴',
                'verbose_name_plural': '分割計画取込履歴',
                'db_table': 'outsource_split_import_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
