# Generated by Django 5.2.9 on 2026-05-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0012_add_split_import_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequirement',
            name='issued_by',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='出庫者'),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='shipment_planned_by',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='便計画者'),
        ),
    ]
