# Generated by Django 5.2.9 on 2026-03-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_add_work_times'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='overtimeapplication',
            name='t_overtime_applic_work_idx',
        ),
        migrations.RemoveIndex(
            model_name='overtimeapplication',
            name='t_overtime_applic_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='overtimeapprovallog',
            name='t_overtime_approvallog_idx',
        ),
        migrations.AddField(
            model_name='overtimeapplication',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='overtime_signatures/', verbose_name='サイン'),
        ),
        migrations.AlterField(
            model_name='overtimeapplication',
            name='end_time',
            field=models.TimeField(verbose_name='残業終了時刻'),
        ),
        migrations.AlterField(
            model_name='overtimeapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='overtimeapplication',
            name='start_time',
            field=models.TimeField(verbose_name='残業開始時刻'),
        ),
        migrations.AlterField(
            model_name='overtimeapprovallog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
