# Generated by Django 5.2.9 on 2026-03-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_add_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeapplication',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('submitted', '申請中'), ('approved_leader', 'リーダー承認済み'), ('approved_supervisor', '班長承認済み'), ('approved_chief', '係長承認済み'), ('approved_manager', '最終承認済み'), ('rejected', '却下')], default='draft', max_length=30, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='overtimeapprovallog',
            name='role',
            field=models.CharField(choices=[('leader', 'リーダー'), ('supervisor', '班長'), ('chief', '係長'), ('manager', '課長/部長')], max_length=20, verbose_name='役割'),
        ),
    ]
