# Generated by Django 5.2.9 on 2026-03-22 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0038_add_use_direct_process_to_line'),
        ('overtime', '0005_add_leave_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeapplication',
            name='work_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_applications', to='masters.workpattern', verbose_name='勤務パターン（休日出勤用）'),
        ),
        migrations.AlterField(
            model_name='overtimeapplication',
            name='application_type',
            field=models.CharField(choices=[('overtime', '時間外'), ('holiday', '休日出勤'), ('half_day_am', '午前半休'), ('half_day_pm', '午後半休'), ('paid_leave', '有給'), ('paid_leave_consec', '連続有給')], default='overtime', max_length=20, verbose_name='申請種別'),
        ),
    ]
