# Generated by Django 5.2.9 on 2026-03-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0007_overtimeapplication_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeapplication',
            name='application_type',
            field=models.CharField(choices=[('normal', '定時'), ('overtime', '時間外'), ('holiday', '休日出勤'), ('half_day_am', '午前半休'), ('half_day_pm', '午後半休'), ('paid_leave', '有給'), ('paid_leave_consec', '連続有給')], default='overtime', max_length=20, verbose_name='申請種別'),
        ),
    ]
