# Generated by Django 5.2.9 on 2025-12-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=50, verbose_name='受注番号')),
                ('order_type', models.CharField(choices=[('FIRM', '確定'), ('FORECAST', '内示')], max_length=20, verbose_name='受注タイプ')),
                ('version_no', models.CharField(default='v1', max_length=20, verbose_name='版番号')),
                ('source_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='ソースシステム')),
                ('source_file', models.CharField(blank=True, max_length=200, null=True, verbose_name='ソースファイル')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='受注日')),
                ('freeze_from', models.DateField(blank=True, null=True, verbose_name='凍結開始日')),
                ('status', models.CharField(choices=[('OPEN', 'オープン'), ('CLOSED', 'クローズ'), ('CANCELED', 'キャンセル')], default='OPEN', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.customer', verbose_name='得意先')),
            ],
            options={
                'verbose_name': '受注',
                'verbose_name_plural': '受注',
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_no', models.IntegerField(verbose_name='行番号')),
                ('product_code', models.CharField(max_length=50, verbose_name='製品コード')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='数量')),
                ('due_date', models.DateField(verbose_name='納期')),
                ('plant_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='工場コード')),
                ('ship_to_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='納入先コード')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='受注')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '受注明細',
                'verbose_name_plural': '受注明細',
                'db_table': 't_order_line',
            },
        ),
        migrations.CreateModel(
            name='StgOrderRaw',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=20, verbose_name='得意先コード')),
                ('order_type', models.CharField(choices=[('FIRM', '確定'), ('FORECAST', '内示')], max_length=20, verbose_name='受注タイプ')),
                ('source_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='ソースシステム')),
                ('source_file', models.CharField(blank=True, max_length=200, null=True, verbose_name='ソースファイル')),
                ('source_row_no', models.IntegerField(verbose_name='ソース行番号')),
                ('record_token', models.CharField(blank=True, max_length=50, null=True, verbose_name='レコード識別子')),
                ('start_month', models.DateField(blank=True, null=True, verbose_name='開始月度')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='納期')),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='製品コード')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='数量')),
                ('raw_payload', models.JSONField(verbose_name='生データ（JSON）')),
                ('parse_status', models.CharField(choices=[('PENDING', '未処理'), ('PARSED', '処理済'), ('ERROR', 'エラー')], default='PENDING', max_length=20, verbose_name='解析ステータス')),
                ('error_message', models.CharField(blank=True, max_length=200, null=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '受注取込ステージング（生データ）',
                'verbose_name_plural': '受注取込ステージング（生データ）',
                'db_table': 'stg_order_raw',
                'indexes': [models.Index(fields=['customer_code'], name='stg_order_r_custome_83ee68_idx'), models.Index(fields=['parse_status'], name='stg_order_r_parse_s_be345d_idx')],
            },
        ),
        migrations.CreateModel(
            name='StgOrderDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('FIRM', '確定'), ('FORECAST', '内示')], max_length=20, verbose_name='受注タイプ')),
                ('version_no', models.CharField(default='v1', max_length=20, verbose_name='版番号')),
                ('product_code', models.CharField(max_length=50, verbose_name='製品コード')),
                ('due_date', models.DateField(verbose_name='納期')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='数量')),
                ('plant_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='工場コード')),
                ('ship_to_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='納入先コード')),
                ('source_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='ソースシステム')),
                ('source_file', models.CharField(blank=True, max_length=200, null=True, verbose_name='ソースファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer', verbose_name='得意先')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.stgorderraw', verbose_name='生データ')),
            ],
            options={
                'verbose_name': '受注取込ステージング（日別）',
                'verbose_name_plural': '受注取込ステージング（日別）',
                'db_table': 'stg_order_daily',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='t_order_status_2d3a57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer', 'order_no', 'order_type', 'version_no')},
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['due_date'], name='t_order_lin_due_dat_0e5900_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['product_code'], name='t_order_lin_product_866639_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together={('order', 'line_no')},
        ),
        migrations.AddIndex(
            model_name='stgorderdaily',
            index=models.Index(fields=['due_date'], name='stg_order_d_due_dat_a18b91_idx'),
        ),
        migrations.AddIndex(
            model_name='stgorderdaily',
            index=models.Index(fields=['customer', 'due_date'], name='stg_order_d_custome_a9b723_idx'),
        ),
    ]
