# Generated by Django 5.2.9 on 2025-12-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_line_backl_plan_da_8b86d8_idx_line_backlo_plan_da_bdedd1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linebacklog',
            name='order_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
