# Generated by Django 5.2.9 on 2025-12-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_linestatus_linerealtimerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='linebacklog',
            name='sequence_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
