# Generated by Django 5.2.9 on 2025-12-17 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_line_calendar'),
        ('orders', '0018_linerealtimerecord_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessRealtimeRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='製品コード')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品名')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='記録時刻')),
                ('record_type', models.CharField(choices=[('PRODUCTION', '生産完成'), ('EQUIPMENT_STATE', '設備状態変更'), ('OPERATOR_ACTION', '作業者アクション')], max_length=20, verbose_name='記録タイプ')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='数量')),
                ('equipment_state', models.CharField(blank=True, choices=[('RUNNING', '運転中'), ('IDLE', '待機'), ('SETUP', '段取り中'), ('MAINTENANCE', '保全中'), ('BREAKDOWN', '故障'), ('STOPPED', '停止')], max_length=20, null=True, verbose_name='設備状態')),
                ('event_data', models.JSONField(blank=True, null=True, verbose_name='イベント詳細データ')),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ロット番号')),
                ('operator_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='作業者名')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '工程実時間記録',
                'verbose_name_plural': '工程実時間記録',
                'db_table': 't_process_realtime_record',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['process', 'timestamp'], name='t_process_r_process_9565b9_idx'), models.Index(fields=['record_type'], name='t_process_r_record__2f1f01_idx'), models.Index(fields=['product_code'], name='t_process_r_product_ccead9_idx')],
            },
        ),
    ]
