# Generated by Django 5.2.9 on 2025-12-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_scrap_disposition_default'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lineganttplan',
            new_name='t_line_gant_line_id_5f06e2_idx',
            old_name='idx_line_gantt_plan_date',
        ),
        migrations.RenameIndex(
            model_name='scraprecord',
            new_name='t_scrap_rec_process_79ed8b_idx',
            old_name='orders_scr_process_2d11e6_idx',
        ),
        migrations.RenameIndex(
            model_name='scraprecord',
            new_name='t_scrap_rec_line_id_48671a_idx',
            old_name='orders_scr_line_id_23aeaf_idx',
        ),
        migrations.AddField(
            model_name='linebacklog',
            name='actual_shipment_qty',
            field=models.IntegerField(default=0, verbose_name='実績出庫数'),
        ),
        migrations.AddField(
            model_name='linebacklog',
            name='adjust_qty',
            field=models.IntegerField(default=0, verbose_name='調整数'),
        ),
        migrations.AddField(
            model_name='linebacklog',
            name='scrap_qty',
            field=models.IntegerField(default=0, verbose_name='仕損数'),
        ),
        migrations.AddField(
            model_name='scraprecord',
            name='plan_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='計画日'),
        ),
        migrations.AlterField(
            model_name='processrealtimerecord',
            name='record_type',
            field=models.CharField(choices=[('PRODUCTION', '生産完成'), ('SCRAP', '仕損'), ('EQUIPMENT_STATE', '設備状態変更'), ('OPERATOR_ACTION', '作業者アクション')], max_length=20, verbose_name='記録タイプ'),
        ),
    ]
