# Generated by Django 5.2.9 on 2025-12-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_rename_idx_line_gantt_plan_date_t_line_gant_line_id_5f06e2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linebacklog',
            name='plan_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
