# Generated by Django 5.2.9 on 2025-12-31 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0022_alter_routingstep_options'),
        ('orders', '0029_linebacklog_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgorderdaily',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='stgorderdaily',
            name='product_name_halfwidth',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='品名半角'),
        ),
        migrations.AlterField(
            model_name='stgorderdaily',
            name='raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.stgorderraw', verbose_name='生データ（旧）'),
        ),
        migrations.CreateModel(
            name='StgOrderRawKubota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=20, verbose_name='得意先コード')),
                ('order_type', models.CharField(choices=[('FIRM', '確定'), ('FORECAST', '内示')], max_length=20, verbose_name='受注タイプ')),
                ('source_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='ソースシステム')),
                ('source_file', models.CharField(blank=True, max_length=200, null=True, verbose_name='ソースファイル')),
                ('source_row_no', models.IntegerField(verbose_name='ソース行番号')),
                ('data_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='データNo')),
                ('record_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='レコード識別')),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='品番')),
                ('inspection_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='検査区分')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='品名')),
                ('start_month', models.CharField(blank=True, max_length=10, null=True, verbose_name='スタート月度')),
                ('date_headers', models.JSONField(blank=True, null=True, verbose_name='日付ヘッダー配列')),
                ('quantities', models.JSONField(blank=True, null=True, verbose_name='数量配列')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='納入指示日')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='納入指示数')),
                ('order_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='注番')),
                ('raw_payload', models.JSONField(verbose_name='生データ（JSON）')),
                ('parse_status', models.CharField(choices=[('PENDING', '未処理'), ('PARSED', '処理済'), ('ERROR', 'エラー')], default='PENDING', max_length=20, verbose_name='解析ステータス')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'クボタ受注取込ステージング（生データ）',
                'verbose_name_plural': 'クボタ受注取込ステージング（生データ）',
                'db_table': 'stg_order_raw_kubota',
                'indexes': [models.Index(fields=['customer_code'], name='stg_order_r_custome_d6458c_idx'), models.Index(fields=['parse_status'], name='stg_order_r_parse_s_4748fc_idx'), models.Index(fields=['source_file'], name='stg_order_r_source__e79a13_idx'), models.Index(fields=['product_code', 'inspection_type'], name='stg_order_r_product_b4c29d_idx')],
            },
        ),
        migrations.AddField(
            model_name='stgorderdaily',
            name='raw_kubota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.stgorderrawkubota', verbose_name='クボタ生データ'),
        ),
        migrations.CreateModel(
            name='StgOrderRawTiera',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=20, verbose_name='得意先コード')),
                ('order_type', models.CharField(choices=[('FIRM', '確定'), ('FORECAST', '内示')], max_length=20, verbose_name='受注タイプ')),
                ('source_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='ソースシステム')),
                ('source_file', models.CharField(blank=True, max_length=200, null=True, verbose_name='ソースファイル')),
                ('source_row_no', models.IntegerField(verbose_name='ソース行番号')),
                ('data_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='データ区分')),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='製品コード(図番)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='納期')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='数量')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='納品書用品名')),
                ('product_name_kana', models.CharField(blank=True, max_length=200, null=True, verbose_name='納品書用品名カナ')),
                ('c_table_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='C表No/不良通知No')),
                ('raw_payload', models.JSONField(verbose_name='生データ（JSON）')),
                ('parse_status', models.CharField(choices=[('PENDING', '未処理'), ('PARSED', '処理済'), ('ERROR', 'エラー')], default='PENDING', max_length=20, verbose_name='解析ステータス')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ティエラ受注取込ステージング（生データ）',
                'verbose_name_plural': 'ティエラ受注取込ステージング（生データ）',
                'db_table': 'stg_order_raw_tiera',
                'indexes': [models.Index(fields=['customer_code'], name='stg_order_r_custome_8a3b27_idx'), models.Index(fields=['parse_status'], name='stg_order_r_parse_s_18448f_idx'), models.Index(fields=['source_file'], name='stg_order_r_source__aa5038_idx')],
            },
        ),
        migrations.AddField(
            model_name='stgorderdaily',
            name='raw_tiera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.stgorderrawtiera', verbose_name='ティエラ生データ'),
        ),
        migrations.AddIndex(
            model_name='stgorderdaily',
            index=models.Index(fields=['product_code'], name='stg_order_d_product_49e5c5_idx'),
        ),
    ]
