# Generated by Django 5.2.9 on 2026-01-04 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0023_line_line_type'),
        ('orders', '0033_orderline_actual_shipment_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentActual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shipment_date', models.DateField(verbose_name='出荷日')),
                ('product_code', models.CharField(max_length=50, verbose_name='品番コード')),
                ('customer_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='得意先コード')),
                ('ship_to_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='納入先コード')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='出荷実績数')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer', verbose_name='得意先')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '出荷実績',
                'verbose_name_plural': '出荷実績',
                'db_table': 't_shipment_actual',
            },
        ),
        migrations.CreateModel(
            name='ShipmentActualHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', '作成'), ('UPDATE', '更新'), ('DELETE', '削除')], max_length=10, verbose_name='操作')),
                ('shipment_date', models.DateField(verbose_name='出荷日')),
                ('product_code', models.CharField(max_length=50, verbose_name='品番コード')),
                ('customer_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='得意先コード')),
                ('ship_to_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='納入先コード')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='出荷実績数')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('shipment_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='orders.shipmentactual', verbose_name='出荷実績')),
            ],
            options={
                'verbose_name': '出荷実績履歴',
                'verbose_name_plural': '出荷実績履歴',
                'db_table': 't_shipment_actual_history',
            },
        ),
        migrations.AddIndex(
            model_name='shipmentactual',
            index=models.Index(fields=['shipment_date'], name='t_shipment__shipmen_6a1e16_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentactual',
            index=models.Index(fields=['product_code'], name='t_shipment__product_b3d76c_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentactual',
            index=models.Index(fields=['customer_code'], name='t_shipment__custome_3e3ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentactual',
            index=models.Index(fields=['ship_to_code'], name='t_shipment__ship_to_e6ab81_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentactualhistory',
            index=models.Index(fields=['shipment_actual', 'created_at'], name='t_shipment__shipmen_19135a_idx'),
        ),
    ]
