# Generated by Django 5.2.9 on 2026-01-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_containercapacity_productgroup_product_capacity_and_more'),
        ('orders', '0035_scraprecord_event_type_return_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(verbose_name='出荷日')),
                ('order_quantity', models.IntegerField(verbose_name='受注数量')),
                ('shipped_quantity', models.IntegerField(default=0, verbose_name='出荷済数量')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='受注')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '出荷進捗',
                'verbose_name_plural': '出荷進捗',
                'db_table': 't_delivery_progress',
                'indexes': [models.Index(fields=['order_date'], name='t_delivery__order_d_c16dd1_idx'), models.Index(fields=['product'], name='t_delivery__product_6386b6_idx')],
            },
        ),
    ]
