# Generated by Django 5.2.9 on 2026-01-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_deliveryprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgorderrawrieden',
            name='order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='発注番号'),
        ),
        migrations.AlterField(
            model_name='stgorderrawrieden',
            name='order_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='発注先コード'),
        ),
    ]
