# Generated by Django 5.2.9 on 2026-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_orderline_customer_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgorderrawtiera',
            name='order_document_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='注文書号'),
        ),
    ]
