# Generated by Django 5.2.9 on 2026-01-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseplanchangelog',
            new_name='purchase_pl_plan_da_8ea1ee_idx',
            old_name='purchase_pl_plan_da_8a5c9e_idx',
        ),
    ]
