# Generated by Django 5.2.9 on 2026-02-21 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_alter_product_category'),
        ('purchase', '0002_rename_purchase_pl_plan_da_8a5c9e_idx_purchase_pl_plan_da_8ea1ee_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringChangeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_date', models.DateField(blank=True, null=True, verbose_name='切替予定日')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_change_cases', to='masters.product')),
            ],
            options={
                'db_table': 'engineering_change_case',
            },
        ),
        migrations.CreateModel(
            name='EngineeringChangePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty_after_eol', models.IntegerField(default=0, verbose_name='打ち切り後必要量')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='purchase.engineeringchangecase')),
                ('new_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineering_change_new_parts', to='masters.product')),
                ('old_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_change_old_parts', to='masters.product')),
            ],
            options={
                'db_table': 'engineering_change_part',
            },
        ),
        migrations.AddIndex(
            model_name='engineeringchangecase',
            index=models.Index(fields=['switch_date'], name='engineering_switch__ad0166_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringchangecase',
            index=models.Index(fields=['final_product'], name='engineering_final_p_2c6c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringchangepart',
            index=models.Index(fields=['old_part'], name='engineering_old_par_aaf889_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringchangepart',
            index=models.Index(fields=['new_part'], name='engineering_new_par_a3c31f_idx'),
        ),
    ]
