# Generated by Django 5.2.9 on 2026-02-21 02:34

from django.db import migrations, models


def fill_case_code(apps, schema_editor):
    EngineeringChangeCase = apps.get_model('purchase', 'EngineeringChangeCase')
    for case in EngineeringChangeCase.objects.all().iterator():
        if not case.case_code:
            case.case_code = f'EC-{case.id:06d}'
            case.save(update_fields=['case_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_engineeringchangecase_engineeringchangepart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringchangecase',
            name='case_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='案件コード'),
        ),
        migrations.AddField(
            model_name='engineeringchangepart',
            name='switch_date',
            field=models.DateField(blank=True, null=True, verbose_name='切替予定日'),
        ),
        migrations.RunPython(fill_case_code, migrations.RunPython.noop),
    ]
