# Generated by Django 5.2.9 on 2026-02-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_engineeringchangecase_case_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringchangecase',
            name='case_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='案件名'),
        ),
    ]
