# Generated by Django 5.2.9 on 2026-02-21 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_alter_product_category'),
        ('purchase', '0005_engineeringchangecase_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringchangecase',
            name='final_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineering_change_cases', to='masters.product'),
        ),
    ]
