# Generated by Django 5.2.9 on 2026-03-01 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_product_order_lot_min_product_order_lot_multiple_and_more'),
        ('purchase', '0006_alter_engineeringchangecase_final_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderApprovalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.SmallIntegerField(unique=True)),
                ('level_name', models.CharField(max_length=50)),
                ('approver_users', models.ManyToManyField(blank=True, related_name='purchase_order_approval_levels', to=settings.AUTH_USER_MODEL)),
                ('notify_users', models.ManyToManyField(blank=True, related_name='purchase_order_approval_notify_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_order_approval_config',
                'ordering': ['approval_level'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_no', models.CharField(max_length=30, unique=True)),
                ('order_date', models.DateField()),
                ('desired_delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', '作成中'), ('SUBMITTED', '業務員サイン済'), ('APPROVED_L2', '班長承認済'), ('APPROVED_L3', '係長承認済'), ('APPROVED', '最終承認済'), ('SENT', '購入先送信済'), ('REJECTED', '差戻'), ('CANCELED', 'キャンセル')], default='DRAFT', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_proposals_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_proposals', to='masters.supplier')),
            ],
            options={
                'db_table': 'purchase_order_proposal',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderProposalApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.SmallIntegerField()),
                ('action', models.CharField(choices=[('APPROVED', '承認'), ('REJECTED', '差戻')], max_length=20)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_proposal_approvals', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='purchase.purchaseorderproposal')),
            ],
            options={
                'db_table': 'purchase_order_proposal_approval',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderProposalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortage_date', models.DateField(blank=True, null=True)),
                ('shortage_qty', models.IntegerField(blank=True, null=True)),
                ('order_qty', models.IntegerField(default=0)),
                ('snapshot_stock', models.IntegerField(blank=True, null=True)),
                ('snapshot_min_stock', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_proposal_lines', to='masters.line')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_proposal_lines', to='masters.product')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.purchaseorderproposal')),
            ],
            options={
                'db_table': 'purchase_order_proposal_line',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('CREATE_PROPOSAL', '発注提案書作成'), ('APPROVE_L2', '班長承認'), ('APPROVE_L3', '係長承認'), ('APPROVE_L4', '事業部長承認'), ('SEND_TO_SUPPLIER', '購入先送信')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', '未対応'), ('DONE', '完了'), ('SKIPPED', 'スキップ')], default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_tasks', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='purchase.purchaseorderproposal')),
            ],
            options={
                'db_table': 'purchase_order_task',
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('WEEKLY_NTH_DAY', '月の第N週の曜日'), ('MONTHLY_DATE', '毎月日付'), ('EVERY_WEEK', '毎週曜日')], max_length=30)),
                ('nth_week', models.SmallIntegerField(blank=True, null=True)),
                ('day_of_week', models.SmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.SmallIntegerField(blank=True, null=True)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_schedules', to='masters.supplier')),
            ],
            options={
                'db_table': 'supplier_order_schedule',
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorderproposal',
            index=models.Index(fields=['supplier', 'order_date'], name='purchase_or_supplie_79241e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderproposal',
            index=models.Index(fields=['status'], name='purchase_or_status_93f8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderproposalapproval',
            index=models.Index(fields=['proposal', 'approval_level'], name='purchase_or_proposa_3d07ea_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderproposalline',
            index=models.Index(fields=['proposal'], name='purchase_or_proposa_5dbe41_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderproposalline',
            index=models.Index(fields=['product'], name='purchase_or_product_4444b6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordertask',
            index=models.Index(fields=['assigned_to', 'status'], name='purchase_or_assigne_7ae728_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordertask',
            index=models.Index(fields=['task_type', 'status'], name='purchase_or_task_ty_66a820_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordertask',
            index=models.Index(fields=['proposal'], name='purchase_or_proposa_a1ba66_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorderschedule',
            index=models.Index(fields=['supplier', 'is_enabled'], name='supplier_or_supplie_970882_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorderschedule',
            index=models.Index(fields=['pattern_type'], name='supplier_or_pattern_f98395_idx'),
        ),
    ]
