# Generated by Django 5.2.9 on 2026-03-02 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_purchaseorderapprovalconfig_purchaseorderproposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderapprovalconfig',
            name='proxy_approver_users',
            field=models.ManyToManyField(blank=True, related_name='purchase_order_approval_proxy_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseordertask',
            name='task_type',
            field=models.CharField(choices=[('CREATE_PROPOSAL', '発注提案書作成'), ('CREATE_ORDER_PDF', '注文書作成'), ('APPROVE_L2', '班長承認'), ('APPROVE_L3', '係長承認'), ('APPROVE_L4', '事業部長承認'), ('SEND_TO_SUPPLIER', '購入先送信')], max_length=30),
        ),
    ]
