# Generated by Django 5.2.9 on 2026-05-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_nth_week_to_nth_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderpattern',
            name='interval_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='間隔営業日数'),
        ),
        migrations.AddField(
            model_name='supplierorderpattern',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始基準日'),
        ),
        migrations.AlterField(
            model_name='supplierorderpattern',
            name='recurrence_type',
            field=models.CharField(choices=[('WEEKLY', '毎週曜日'), ('MONTHLY_DATE', '毎月日付'), ('MONTHLY_NTH_DOW', '月の第N週の曜日'), ('EVERY_BUSINESS_DAY', '毎営業日'), ('EVERY_N_BUSINESS_DAYS', 'N営業日ごと')], max_length=30, verbose_name='繰返し種別'),
        ),
    ]
