# Generated by Django 5.2.9 on 2026-05-21 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_add_every_n_business_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderschedule',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='purchase.supplierorderpattern', verbose_name='納入パターン'),
        ),
    ]
