# Generated by Django 5.2.9 on 2026-06-03 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0058_calendar_created_by_updated_by'),
        ('purchase', '0015_supplierorderschedule_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAutoDeliveryListConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('scheduled_hour', models.PositiveSmallIntegerField(default=7, verbose_name='実行時（時）')),
                ('scheduled_minute', models.PositiveSmallIntegerField(default=0, verbose_name='実行時（分）')),
                ('cc_emails', models.TextField(blank=True, default='', verbose_name='業務員CC送信先メール（改行区切り）')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最終実行日時')),
                ('last_run_status', models.CharField(blank=True, choices=[('SUCCESS', '成功'), ('FAILED', '失敗'), ('RUNNING', '実行中'), ('SKIPPED', 'スキップ')], max_length=20, null=True, verbose_name='最終実行結果')),
                ('last_run_message', models.TextField(blank=True, default='', verbose_name='最終実行メッセージ')),
                ('last_run_duration_seconds', models.FloatField(blank=True, null=True, verbose_name='最終実行時間（秒）')),
                ('notify_on_failure', models.ManyToManyField(blank=True, related_name='auto_delivery_list_failure_notifications', to=settings.AUTH_USER_MODEL, verbose_name='失敗時の通知先')),
                ('notify_on_non_delivery', models.ManyToManyField(blank=True, related_name='auto_delivery_list_non_delivery_notifications', to=settings.AUTH_USER_MODEL, verbose_name='納入日でないときの通知先')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_delivery_list_config', to='masters.supplier', verbose_name='対象仕入先')),
            ],
            options={
                'verbose_name': '自動納入リスト送信設定',
                'verbose_name_plural': '自動納入リスト送信設定',
                'db_table': 'purchase_auto_delivery_list_config',
            },
        ),
    ]
