# Generated by Django 5.2.9 on 2026-06-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_auto_delivery_list_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseautodeliverylistconfig',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='納入日（何営業日後）'),
        ),
    ]
