# Generated by Django 5.2.9 on 2026-06-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_auto_delivery_list_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseautodeliverylistconfig',
            name='progress_days_back',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='進度表（何日前から）'),
        ),
    ]
