# Generated by Django 5.2.9 on 2026-06-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_auto_delivery_list_progress_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseautodeliverylistconfig',
            name='reply_to_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='返信先メールアドレス'),
        ),
    ]
