# Generated by Django 5.2.9 on 2026-06-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0019_auto_delivery_list_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseautodeliverylistconfig',
            name='progress_days_forward',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='進度表（何日後まで）'),
        ),
        migrations.AlterField(
            model_name='purchaseautodeliverylistconfig',
            name='progress_days_back',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='進度表（何営業日前から）'),
        ),
    ]
