# Generated by Django 5.2.9 on 2026-07-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_purchase_actual_kikan_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseautodeliverylistconfig',
            name='send_delivery_list_excel',
            field=models.BooleanField(default=True, verbose_name='納品リストExcel送信'),
        ),
        migrations.AddField(
            model_name='purchaseautodeliverylistconfig',
            name='send_delivery_note_pdf',
            field=models.BooleanField(default=True, verbose_name='外作納品書PDF送信'),
        ),
        migrations.AddField(
            model_name='purchaseautodeliverylistconfig',
            name='send_progress_excel',
            field=models.BooleanField(default=True, verbose_name='進度表Excel送信'),
        ),
        migrations.AddField(
            model_name='purchaseautodeliverylistconfig',
            name='send_progress_pdf',
            field=models.BooleanField(default=True, verbose_name='進度表PDF送信'),
        ),
    ]
