# Generated by Django 5.2.9 on 2026-07-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0022_auto_delivery_list_file_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseautodeliverylistconfig',
            name='email_body_custom',
            field=models.TextField(blank=True, default='', verbose_name='メール本文（カスタム）'),
        ),
    ]
