# Generated by Django 5.2.9 on 2026-08-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0033_purchaseautoordersendhistory_attachment_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseautoordersendconfig',
            name='send_order_pdf',
            field=models.BooleanField(default=False, verbose_name='注文書PDF送信'),
        ),
    ]
