# Generated by Django 5.2.9 on 2026-09-14 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0084_add_two_person_only_to_process'),
        ('purchase', '0037_delete_purchaseorderapprovalconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderproposalemailconfig',
            options={'ordering': ['supplier__supplier_code'], 'verbose_name': '外作・購入品注文メール設定', 'verbose_name_plural': '外作・購入品注文メール設定'},
        ),
        migrations.AlterField(
            model_name='purchaseordertask',
            name='task_type',
            field=models.CharField(choices=[('CREATE_PROPOSAL', '外作・購入品注文書作成'), ('CREATE_ORDER_PDF', '注文書作成'), ('APPROVE_L2', '班長承認'), ('APPROVE_L3', '係長承認'), ('APPROVE_L4', '事業部長承認'), ('SEND_TO_SUPPLIER', '購入先送信')], max_length=30),
        ),
        migrations.CreateModel(
            name='DiscontinuationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(max_length=30, unique=True, verbose_name='案件コード')),
                ('title', models.CharField(max_length=200, verbose_name='案件名')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了時期')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'discontinuation_case',
                'indexes': [models.Index(fields=['end_date'], name='discontinua_end_dat_1ae73d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiscontinuationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='打ち切り時期')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purchase.discontinuationcase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discontinuation_products', to='masters.product', verbose_name='完成品')),
            ],
            options={
                'db_table': 'discontinuation_product',
            },
        ),
        migrations.CreateModel(
            name='DiscontinuationPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discontinuation_parts', to='masters.product', verbose_name='構成品')),
                ('disc_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='purchase.discontinuationproduct')),
            ],
            options={
                'db_table': 'discontinuation_part',
            },
        ),
        migrations.AddIndex(
            model_name='discontinuationproduct',
            index=models.Index(fields=['product'], name='discontinua_product_b4b73f_idx'),
        ),
        migrations.AddIndex(
            model_name='discontinuationpart',
            index=models.Index(fields=['part'], name='discontinua_part_id_70e991_idx'),
        ),
    ]
