# Generated by Django 5.2.9 on 2026-09-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0038_discontinuation_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderproposalline',
            options={'ordering': ['product__product_code']},
        ),
    ]
