# Generated by Django 5.2.9 on 2025-12-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calendar_code', models.CharField(max_length=20, unique=True, verbose_name='カレンダコード')),
                ('calendar_name', models.CharField(max_length=50, verbose_name='カレンダ名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'カレンダ',
                'verbose_name_plural': 'カレンダ',
                'db_table': 'm_calendar',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_code', models.CharField(max_length=20, unique=True, verbose_name='ラインコード')),
                ('line_name', models.CharField(max_length=50, verbose_name='ライン名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ライン',
                'verbose_name_plural': 'ライン',
                'db_table': 'm_line',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('process_code', models.CharField(max_length=20, unique=True, verbose_name='工程コード')),
                ('process_name', models.CharField(max_length=50, verbose_name='工程名')),
                ('is_outsource', models.BooleanField(default=False, verbose_name='外注工程')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '工程',
                'verbose_name_plural': '工程',
                'db_table': 'm_process',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=30, unique=True, verbose_name='品番コード')),
                ('product_name', models.CharField(max_length=100, verbose_name='品名')),
                ('category', models.CharField(choices=[('ASSEMBLY', '組立品'), ('SINGLE', '単品'), ('MATERIAL', '材料'), ('PURCHASED', '購入品')], max_length=20, verbose_name='カテゴリ')),
                ('unit', models.CharField(default='個', max_length=10, verbose_name='単位')),
                ('standard_lt_days', models.IntegerField(blank=True, null=True, verbose_name='標準LT(日)')),
                ('self_lt_days', models.IntegerField(blank=True, null=True, verbose_name='自工程LT(日)')),
                ('is_final_product', models.BooleanField(default=False, verbose_name='最終製品')),
                ('is_phantom', models.BooleanField(default=False, verbose_name='見なし組立')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '製品',
                'verbose_name_plural': '製品',
                'db_table': 'm_product',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(max_length=20, unique=True, verbose_name='仕入先コード')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='仕入先名')),
            ],
            options={
                'verbose_name': '仕入先',
                'verbose_name_plural': '仕入先',
                'db_table': 'm_supplier',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=20, unique=True, verbose_name='得意先コード')),
                ('customer_name', models.CharField(max_length=100, verbose_name='得意先名')),
                ('short_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='略称')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.calendar', verbose_name='カレンダ')),
            ],
            options={
                'verbose_name': '得意先',
                'verbose_name_plural': '得意先',
                'db_table': 'm_customer',
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(default='v1', max_length=20, verbose_name='版')),
                ('valid_from', models.DateField(verbose_name='有効開始日')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='有効終了日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product', verbose_name='親製品')),
            ],
            options={
                'verbose_name': 'BOM',
                'verbose_name_plural': 'BOM',
                'db_table': 'm_bom',
                'unique_together': {('parent_product', 'version', 'valid_from')},
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('routing_code', models.CharField(max_length=30, verbose_name='ルーティングコード')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_default', models.BooleanField(default=False, verbose_name='既定')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': 'ルーティング',
                'verbose_name_plural': 'ルーティング',
                'db_table': 'm_routing',
                'unique_together': {('product', 'routing_code')},
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='数量')),
                ('loss_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='ロス率')),
                ('sourcing_type', models.CharField(choices=[('MAKE', '自社製造'), ('BUY', '購買'), ('SUBCON', '外注')], default='MAKE', max_length=20, verbose_name='調達区分')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.bom', verbose_name='BOM')),
                ('child_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product', verbose_name='子製品')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier', verbose_name='仕入先')),
            ],
            options={
                'verbose_name': 'BOM明細',
                'verbose_name_plural': 'BOM明細',
                'db_table': 'm_bom_item',
            },
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_date', models.DateField(verbose_name='対象日')),
                ('is_working_day', models.BooleanField(verbose_name='稼働日')),
                ('work_minutes', models.IntegerField(blank=True, null=True, verbose_name='稼働分')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.calendar', verbose_name='カレンダ')),
            ],
            options={
                'verbose_name': 'カレンダ日',
                'verbose_name_plural': 'カレンダ日',
                'db_table': 'm_calendar_day',
                'unique_together': {('calendar', 'target_date')},
            },
        ),
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_no', models.IntegerField(verbose_name='工程番号')),
                ('time_unit', models.CharField(choices=[('DAY', '日'), ('MINUTE', '分')], default='DAY', max_length=10, verbose_name='時間単位')),
                ('lead_time_days', models.IntegerField(default=0, verbose_name='リードタイム(日)')),
                ('start_offset_min', models.IntegerField(blank=True, null=True, verbose_name='開始オフセット(分)')),
                ('duration_min', models.IntegerField(blank=True, null=True, verbose_name='所要時間(分)')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='masters.routing', verbose_name='ルーティング')),
            ],
            options={
                'verbose_name': 'ルーティング工程',
                'verbose_name_plural': 'ルーティング工程',
                'db_table': 'm_routing_step',
                'ordering': ['routing', 'step_no'],
                'unique_together': {('routing', 'step_no')},
            },
        ),
    ]
