# Generated by Django 5.2.9 on 2025-12-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name_halfwidth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='品名半角'),
        ),
    ]
