# Generated by Django 5.2.9 on 2025-12-11 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_add_management_unit_to_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCycleTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cycle_time_min', models.DecimalField(decimal_places=2, help_text='1個あたりの標準加工時間（分）', max_digits=10, verbose_name='標準サイクル時間(分)')),
                ('setup_time_min', models.IntegerField(default=0, help_text='ロット開始時の準備時間（分）', verbose_name='段取り時間(分)')),
                ('lot_size', models.IntegerField(default=1, help_text='標準的な生産ロットサイズ', verbose_name='標準ロットサイズ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='有効開始日')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='有効終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '工程別サイクル時間',
                'verbose_name_plural': '工程別サイクル時間',
                'db_table': 'm_process_cycle_time',
                'indexes': [models.Index(fields=['product', 'process'], name='m_process_c_product_d485e8_idx'), models.Index(fields=['is_active'], name='m_process_c_is_acti_8abcfa_idx')],
                'unique_together': {('product', 'process', 'line', 'valid_from')},
            },
        ),
    ]
