# Generated by Django 5.2.9 on 2025-12-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_add_process_cycle_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='is_coproduct',
            field=models.BooleanField(default=False, help_text='1つの工程で複数の製品が同時に生産されるBOM（親製品は仮想セット品番）', verbose_name='連産品BOM'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_virtual_set',
            field=models.BooleanField(default=False, help_text='連産品を表す仮想的なセット品番（この品番自体は在庫を持たない）', verbose_name='仮想セット品番'),
        ),
    ]
