# Generated by Django 5.2.9 on 2025-12-31 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_routingstep_parallel_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routingstep',
            options={'ordering': ['routing', 'step_no', 'parallel_group'], 'verbose_name': 'ルーティング工程', 'verbose_name_plural': 'ルーティング工程'},
        ),
    ]
