const masters = [
  {
    path: "/masters",
    name: "MasterMenu",
    component: () => import("@/views/masters/MasterMenu.vue"),
    meta: { pageTitle: "マスタメンテ", resource: "masters", allowChildResources: true },
  },
  {
    path: "/masters/product",
    name: "ProductMaster",
    component: () => import("@/views/masters/ProductMaster.vue"),
    meta: { pageTitle: "製品マスタ", resource: "masters.product" },
  },
  {
    path: "/masters/product-group",
    name: "ProductGroupMaster",
    component: () => import("@/views/masters/ProductGroupMaster.vue"),
    meta: { pageTitle: "製品グループマスタ", resource: "masters.product_group" },
  },
  {
    path: "/masters/product-code-mapping",
    name: "ProductCodeMappingMaster",
    component: () => import("@/views/masters/ProductCodeMappingMaster.vue"),
    meta: { pageTitle: "品番変換マスタ", resource: "masters.product" },
  },
  {
    path: "/masters/container-capacity",
    name: "ContainerCapacityMaster",
    component: () => import("@/views/masters/ContainerCapacityMaster.vue"),
    meta: { pageTitle: "容器マスタ", resource: "masters.container_capacity" },
  },
  {
    path: "/masters/equipment",
    name: "EquipmentMaster",
    component: () => import("@/views/masters/EquipmentMaster.vue"),
    meta: { pageTitle: "設備マスタ", resource: "masters.equipment" },
  },
  {
    path: "/masters/customer",
    name: "CustomerMaster",
    component: () => import("@/views/masters/CustomerMaster.vue"),
    meta: { pageTitle: "得意先マスタ", resource: "masters.customer" },
  },
  {
    path: "/masters/supplier",
    name: "SupplierMaster",
    component: () => import("@/views/masters/SupplierMaster.vue"),
    meta: { pageTitle: "仕入先マスタ", resource: "masters.supplier" },
  },
  {
    path: "/masters/supplier-truck",
    name: "SupplierTruckMaster",
    component: () => import("@/views/masters/SupplierTruckMaster.vue"),
    meta: { pageTitle: "仕入れ先トラックマスタ", resource: "masters.supplier_truck" },
  },
  {
    path: "/masters/process",
    name: "ProcessMaster",
    component: () => import("@/views/masters/ProcessMaster.vue"),
    meta: { pageTitle: "工程マスタ", resource: "masters.process" },
  },
  {
    path: "/masters/line",
    name: "LineMaster",
    component: () => import("@/views/masters/LineMaster.vue"),
    meta: { pageTitle: "ラインマスタ", resource: "masters.line" },
  },
  {
    path: "/masters/calendar",
    name: "CalendarMaster",
    component: () => import("@/views/masters/CalendarMaster.vue"),
    meta: { pageTitle: "カレンダマスタ", resource: "masters.calendar" },
  },
  {
    path: "/masters/work-pattern",
    name: "WorkPatternMaster",
    component: () => import("@/views/masters/WorkPatternMaster.vue"),
    meta: { pageTitle: "勤務パターンマスタ", resource: "masters.work_pattern" },
  },
  {
    path: "/masters/bom",
    name: "BOMMaster",
    component: () => import("@/views/masters/BOMMaster.vue"),
    meta: { pageTitle: "構成マスタ（BOM）", manualPath: "マスタ/BOM作成マニュアル.md", resource: "masters.bom" },
  },
  {
    path: "/masters/tiera-converter",
    name: "TieraConverter",
    component: () => import("@/views/masters/TieraConverter.vue"),
    meta: { pageTitle: "ティエラCSV変換", resource: "masters.bom" },
  },
  {
    path: "/masters/routing",
    name: "RoutingMaster",
    component: () => import("@/views/masters/RoutingMaster.vue"),
    meta: { pageTitle: "ルーティングマスタ", manualPath: "マスタ/ルーティング工程作成ルール.md", resource: "masters.routing" },
  },
  {
    path: "/masters/contact",
    name: "ContactMaster",
    component: () => import("@/views/masters/ContactMaster.vue"),
    meta: { pageTitle: "連絡先マスタ", resource: "masters.contact" },
  },
  {
    path: "/masters/kubota-sakai-truck",
    name: "KubotaSakaiTruckMaster",
    component: () => import("@/views/masters/KubotaSakaiTruckMaster.vue"),
    meta: { pageTitle: "クボタ堺便マスタ", resource: "masters.kubota_sakai_truck" },
  },
  {
    path: "/masters/where-used",
    name: "WhereUsedPage",
    component: () => import("@/views/masters/WhereUsedPage.vue"),
    meta: { pageTitle: "逆展開（Where Used）", resource: "masters.bom" },
  },
  {
    path: "/masters/mobile-device",
    name: "MobileDeviceMaster",
    component: () => import("@/views/masters/MobileDeviceMaster.vue"),
    meta: { pageTitle: "携帯端末管理", resource: "masters.mobile_device" },
  },
  {
    path: "/masters/sourcing-bulk-change",
    name: "SourcingBulkChange",
    component: () => import("@/views/masters/SourcingBulkChange.vue"),
    meta: { pageTitle: "加工先一括変更", resource: "masters.sourcing_bulk_change" },
  },
];

export default masters;
