const production = [
  {
    path: "/production/menu",
    name: "ProductionMenu",
    component: () => import("@/views/production/ProductionMenu.vue"),
    meta: { pageTitle: "生産管理メニュー", manualPath: "README.md", resource: "production", allowChildResources: true },
  },
  {
    path: "/production/morning-meetings",
    name: "MorningMeetingList",
    component: () => import("@/views/production/MorningMeetingList.vue"),
    meta: { pageTitle: "朝礼一覧", manualPath: "生産/朝礼.md", resource: "production.morning_meeting" },
  },
  {
    path: "/production/morning-meetings/new",
    name: "MorningMeetingCreate",
    component: () => import("@/views/production/MorningMeetingForm.vue"),
    meta: { pageTitle: "朝礼作成", manualPath: "生産/朝礼.md", resource: "production.morning_meeting", permission: "edit" },
  },
  {
    path: "/production/morning-meetings/:id/edit",
    name: "MorningMeetingEdit",
    component: () => import("@/views/production/MorningMeetingForm.vue"),
    props: true,
    meta: { pageTitle: "朝礼編集", manualPath: "生産/朝礼.md", resource: "production.morning_meeting", permission: "edit" },
  },
  {
    path: "/production/morning-meetings/:id/run",
    name: "MorningMeetingRun",
    component: () => import("@/views/production/MorningMeetingRun.vue"),
    props: true,
    meta: { pageTitle: "朝礼実行", manualPath: "生産/朝礼.md", resource: "production.morning_meeting" },
  },
  {
    path: "/production/unused",
    name: "ProductionUnusedMenu",
    component: () => import("@/views/production/ProductionUnusedMenu.vue"),
    meta: { pageTitle: "未使用機能", manualPath: "README.md" },
  },
  {
    path: "/production/line-demands",
    name: "LineDemandList",
    component: () => import("@/views/production/LineDemandList.vue"),
    meta: { pageTitle: "ライン需要一覧", manualPath: "生産/ライン需要一覧.md" },
  },
  {
    path: "/production/line-calendars",
    name: "LineCalendar",
    component: () => import("@/views/production/LineCalendar.vue"),
    meta: { pageTitle: "ライン勤務カレンダ", manualPath: "生産/ライン勤務カレンダ.md", resource: "production.line_calendars", permission: "edit" },
  },
  {
    path: "/production/progress",
    name: "ProductionProgress",
    component: () => import("@/views/production/ProductionProgress.vue"),
    meta: { pageTitle: "進捗管理", manualPath: "生産/進捗管理.md" },
  },
  {
    path: "/production/progress-only",
    name: "ProductionProgressOnly",
    component: () => import("@/views/production/ProductionProgressOnly.vue"),
    meta: { pageTitle: "進度のみ", manualPath: "生産/進捗のみ.md", resource: "production.progress" },
  },
  {
    path: "/production/plan-input",
    name: "ProductionPlanInput",
    component: () => import("@/views/production/ProductionPlanInput.vue"),
    meta: { pageTitle: "生産計画入力", manualPath: "生産/生産計画入力.md", resource: "production.plan_input", permission: "edit" },
  },
  {
    path: "/production/plan-change-history",
    name: "ProductionPlanChangeHistory",
    component: () => import("@/views/production/ProductionPlanChangeHistory.vue"),
    meta: { pageTitle: "生産計画変更履歴", manualPath: "README.md", resource: "production.plan_input" },
  },
  {
    path: "/production/gantt-display-product-map",
    name: "GanttDisplayProductMapList",
    component: () => import("@/views/production/GanttDisplayProductMap.vue"),
    meta: { pageTitle: "ガントチャート生成表示品マップ", manualPath: "生産/ガント生成表示品マップ.md" },
  },
  {
    path: "/production/gantt-display-product-map/new",
    name: "GanttDisplayProductMapCreate",
    component: () => import("@/views/production/GanttDisplayProductMapForm.vue"),
    meta: { pageTitle: "ガントチャート生成表示品マップ 新規", manualPath: "生産/ガント生成表示品マップ.md" },
  },
  {
    path: "/production/gantt-display-product-map/:id/edit",
    name: "GanttDisplayProductMapEdit",
    component: () => import("@/views/production/GanttDisplayProductMapForm.vue"),
    props: true,
    meta: { pageTitle: "ガントチャート生成表示品マップ 編集", manualPath: "生産/ガント生成表示品マップ.md" },
  },
  {
    path: "/production/default-start-time",
    name: "DefaultStartTimeSetting",
    component: () => import("@/views/production/DefaultStartTimeSetting.vue"),
    meta: { pageTitle: "デフォルト開始時刻設定", manualPath: "生産/デフォルト開始時刻設定.md", resource: "production.plan_input", permission: "edit" },
  },
  {
    path: "/production/inventory",
    name: "ProductionInventory",
    component: () => import("@/views/inventory/ProductionInventory.vue"),
    meta: { pageTitle: "在庫 / 残量一覧", manualPath: "生産/在庫残量一覧.md", resource: "production.inventory" },
  },
  {
    path: "/production/component-inventory",
    name: "ComponentInventory",
    component: () => import("@/views/inventory/ComponentInventory.vue"),
    meta: { pageTitle: "構成部品在庫一覧", manualPath: "生産/構成部品在庫一覧.md", resource: "production.inventory" },
  },
  {
    path: "/production/stock-allocations",
    name: "StockAllocationList",
    component: () => import("@/views/production/StockAllocationList.vue"),
    meta: { pageTitle: "在庫引当一覧", manualPath: "生産/在庫引当一覧.md" },
  },
  {
    path: "/production/safety-stock-list",
    name: "SafetyStockList",
    component: () => import("@/views/production/SafetyStockList.vue"),
    meta: { pageTitle: "安全在庫一覧", manualPath: "生産/安全在庫一覧.md", resource: "production.inventory" },
  },
  {
    path: "/production/stock-allocations/new",
    name: "StockAllocationCreate",
    component: () => import("@/views/production/StockAllocationForm.vue"),
    meta: { pageTitle: "在庫引当 新規登録", manualPath: "生産/在庫引当一覧.md" },
  },
  {
    path: "/production/stock-allocations/:id/edit",
    name: "StockAllocationEdit",
    component: () => import("@/views/production/StockAllocationForm.vue"),
    props: true,
    meta: { pageTitle: "在庫引当 編集", manualPath: "生産/在庫引当一覧.md" },
  },
  {
    path: "/production/orders",
    name: "ProductionOrderList",
    component: () => import("@/views/production/ProductionOrderList.vue"),
    meta: { pageTitle: "製造指示一覧", manualPath: "生産/製造指示一覧.md" },
  },
  {
    path: "/production/orders/new",
    name: "ProductionOrderCreate",
    component: () => import("@/views/production/ProductionOrderForm.vue"),
    meta: { pageTitle: "製造指示 新規登録", manualPath: "生産/製造指示登録編集.md" },
  },
  {
    path: "/production/orders/:id/edit",
    name: "ProductionOrderEdit",
    component: () => import("@/views/production/ProductionOrderForm.vue"),
    props: true,
    meta: { pageTitle: "製造指示 編集", manualPath: "生産/製造指示登録編集.md" },
  },
  {
    path: "/production/orders/:id/actuals",
    name: "ProcessActualEntry",
    component: () => import("@/views/production/ProcessActualEntry.vue"),
    props: true,
    meta: { pageTitle: "工程実績入力", manualPath: "生産/工程実績入力.md" },
  },
  {
    path: "/production/sequence-board",
    name: "ProductionSequenceBoard",
    component: () => import("@/views/production/ProductionSequenceBoard.vue"),
    meta: { pageTitle: "日次ミックス順序ボード（7品固定運転向け）", manualPath: "生産/ミックス順序ボード.md" },
  },
  {
    path: "/production/line-monitor",
    name: "LineRealtimeMonitor",
    component: () => import("@/views/production/LineRealtimeMonitor.vue"),
    meta: { pageTitle: "ライン稼働監視", manualPath: "生産/ライン稼働監視.md" },
  },
  {
    path: "/production/camera-actual-input",
    name: "CameraActualInput",
    component: () => import("@/views/production/CameraActualInput.vue"),
    meta: { pageTitle: "実績入力（カメラ）", manualPath: "生産/カメラ実績入力.md", resource: "production.process_input", permission: "edit" },
  },
  {
    path: "/production/mobile-input",
    name: "MobileLineInput",
    component: () => import("@/views/production/MobileLineInput.vue"),
    meta: { pageTitle: "ライン作業記録", manualPath: "生産/ライン作業記録.md" },
  },
  {
    path: "/production/mobile-process-input",
    name: "MobileProcessInput",
    component: () => import("@/views/production/MobileProcessInput.vue"),
    meta: {
      pageTitle: "工程作業記録",
      allowedRecordTypes: ["PRODUCTION", "EQUIPMENT_STATE"],
      manualPath: "生産/工程作業入力.md",
      resource: "production.process_input",
      permission: "edit",
    },
  },
  {
    path: "/production/tablet-process-input",
    name: "TabletProcessInput",
    component: () => import("@/views/production/TabletProcessInput.vue"),
    meta: {
      pageTitle: "工程作業記録（タブレット）",
      allowedRecordTypes: ["PRODUCTION", "EQUIPMENT_STATE"],
      manualPath: "生産/工程作業入力.md",
      resource: "production.process_input",
      permission: "edit",
    },
  },
  {
    path: "/production/dual-process-input",
    name: "DualProcessInput",
    component: () => import("@/views/production/DualProcessInput.vue"),
    meta: {
      pageTitle: "１人２工程入力",
      allowedRecordTypes: ["PRODUCTION", "EQUIPMENT_STATE"],
      manualPath: "生産/１人２工程入力.md",
      resource: "production.process_input",
      permission: "edit",
    },
  },
  {
    path: "/production/simultaneous-process-input",
    name: "SimultaneousProcessInput",
    component: () => import("@/views/production/SimultaneousProcessInput.vue"),
    meta: {
      pageTitle: "同時加工入力",
      allowedRecordTypes: ["PRODUCTION", "EQUIPMENT_STATE"],
      manualPath: "生産/工程作業入力.md",
      resource: "production.process_input",
      permission: "edit",
    },
  },
  {
    path: "/production/two-person-one-equipment-input",
    name: "TwoPersonOneEquipmentInput",
    component: () => import("@/views/production/TwoPersonOneEquipmentInput.vue"),
    meta: {
      pageTitle: "2人1設備入力",
      allowedRecordTypes: ["PRODUCTION", "EQUIPMENT_STATE"],
      manualPath: "生産/１人２工程入力.md",
      resource: "production.process_input",
      permission: "edit",
    },
  },
  {
    path: "/production/laser-process-input",
    name: "LaserProcessInput",
    component: () => import("@/views/production/LaserProcessInput.vue"),
    meta: {
      pageTitle: "レーザー実績入力",
      manualPath: "生産/レーザー実績入力.md",
      resource: "production.process_input",
      permission: "edit",
    },
  },
  {
    path: "/production/scrap-record",
    name: "ScrapRecordInput",
    component: () => import("@/views/production/MobileProcessInput.vue"),
    meta: {
      pageTitle: "仕損品記録",
      allowedRecordTypes: ["SCRAP"],
      manualPath: "生産/仕損品記録.md",
      resource: "production.scrap_record",
      permission: "edit",
    },
  },
  {
    path: "/production/record-inquiry",
    name: "ProductionRecordInquiry",
    component: () => import("@/views/production/ProductionRecordInquiry.vue"),
    meta: { pageTitle: "生産実績照会", manualPath: "生産/生産実績照会.md", resource: "production.record_inquiry" },
  },
  {
    path: "/production/record-edit",
    name: "ProductionRecordEdit",
    component: () => import("@/views/production/ProductionRecordEdit.vue"),
    meta: { pageTitle: "実績変更", manualPath: "生産/実績変更.md", resource: "production.record_edit", permission: "edit" },
  },
  {
    path: "/production/process-gantt",
    name: "ProcessGanttView",
    component: () => import("@/views/production/ProcessGanttView.vue"),
    meta: { pageTitle: "工程ガント", manualPath: "README.md" },
  },
  {
    path: "/production/single-process-plan",
    name: "SingleProcessPlanInput",
    component: () => import("@/views/production/SingleProcessPlanInput.vue"),
    meta: { pageTitle: "単独計画", manualPath: "生産/単独計画.md", resource: "production.plan_input", permission: "edit" },
  },
  {
    path: "/production/scrap-history",
    name: "ScrapHistory",
    component: () => import("@/views/production/ScrapHistory.vue"),
    meta: { pageTitle: "仕損履歴", manualPath: "生産/仕損履歴.md", resource: "production.scrap_history" },
  },
  {
    path: "/production/brake-line-input",
    name: "BrakeLineInput",
    component: () => import("@/views/production/BrakeLineInput.vue"),
    meta: { pageTitle: "ブレーキライン実績入力", manualPath: "生産/ブレーキライン実績入力.md", resource: "production.process_input", permission: "edit" },
  },
  {
    path: "/production/process-knowledge-manager",
    name: "ProcessKnowledgeManager",
    component: () => import("@/views/production/ProcessKnowledgeManager.vue"),
    meta: {
      pageTitle: "工程別コツ・注意事項管理",
      resource: "production.process_knowledge",
      permission: "edit",
      fallbackToParent: false,
    },
  },
  {
    path: "/production/process-knowledge-viewer",
    name: "ProcessKnowledgeViewer",
    component: () => import("@/views/production/ProcessKnowledgeViewer.vue"),
    meta: {
      pageTitle: "工程別コツ・注意事項",
      resource: "production.process_knowledge",
      fallbackToParent: false,
    },
  },
  {
    path: "/production/spot-line-input",
    name: "SpotLineInput",
    component: () => import("@/views/production/SpotLineInput.vue"),
    meta: { pageTitle: "スポット実績入力", manualPath: "生産/スポット実績入力.md", resource: "production.process_input", permission: "edit" },
  },
  {
    path: "/production/desktop-process-input",
    name: "DesktopProcessInput",
    component: () => import("@/views/production/DesktopProcessInput.vue"),
    meta: {
      pageTitle: "工程作業記録（デスクトップ）",
      allowedRecordTypes: ["PRODUCTION", "EQUIPMENT_STATE"],
      manualPath: "生産/工程作業入力_デスクトップ.md",
      resource: "production.process_input",
      permission: "edit",
    },
  },
  {
    path: "/production/product-photo-upload",
    name: "ProductPhotoUpload",
    component: () => import("@/views/production/ProductPhotoUpload.vue"),
    meta: { pageTitle: "製品写真アップロード", manualPath: "README.md", resource: "production.process_input", permission: "edit" },
  },
  {
    path: "/production/product-info-editor",
    name: "ProductInfoEditor",
    component: () => import("@/views/production/ProductInfoEditor.vue"),
    meta: { pageTitle: "製品情報編集", resource: "production.process_input", permission: "edit" },
  },
  {
    path: "/production/plan-deviation-report",
    name: "PlanDeviationReport",
    component: () => import("@/views/production/PlanDeviationReport.vue"),
    meta: { pageTitle: "計画乖離レポート", resource: "production.record_inquiry" },
  },
  {
    path: "/production/load-calc-menu",
    name: "LoadCalcMenu",
    component: () => import("@/views/production/LoadCalcMenu.vue"),
    meta: { pageTitle: "負荷計算", manualPath: "生産/負荷計算.md", resource: "production" },
  },
  {
    path: "/production/actual-cycle-time",
    name: "ActualCycleTimeSummary",
    component: () => import("@/views/production/ActualCycleTimeSummary.vue"),
    meta: { pageTitle: "出来高集計", manualPath: "生産/出来高集計.md", resource: "production.record_inquiry" },
  },
  {
    path: "/production/line-cycle-time",
    name: "LineCycleTimeInput",
    component: () => import("@/views/production/LineCycleTimeInput.vue"),
    meta: { pageTitle: "ラインサイクルタイム入力", manualPath: "生産/ラインサイクルタイム.md", resource: "production.plan_input", permission: "edit" },
  },
  {
    path: "/production/line-load-chart",
    name: "LineLoadChart",
    component: () => import("@/views/production/LineLoadChart.vue"),
    meta: { pageTitle: "長期負荷チャート", manualPath: "生産/長期負荷チャート.md", resource: "production" },
  },
  {
    path: "/production/progress-pdf-compare",
    name: "ProgressPdfCompare",
    component: () => import("@/views/production/ProgressPdfCompare.vue"),
    meta: { pageTitle: "進度PDF突合", resource: "production" },
  },
];

export default production;
