const production = [
  {
    path: "/production/menu",
    name: "ProductionMenu",
    component: () => import("@/views/production/ProductionMenu.vue"),
    meta: { pageTitle: "生産管理メニュー", manualPath: "README.md" },
  },
  {
    path: "/production/line-demands",
    name: "LineDemandList",
    component: () => import("@/views/production/LineDemandList.vue"),
    meta: { pageTitle: "ライン需要一覧", manualPath: "生産/ライン需要一覧.md" },
  },
  {
    path: "/production/line-calendars",
    name: "LineCalendar",
    component: () => import("@/views/production/LineCalendar.vue"),
    meta: { pageTitle: "ライン勤務カレンダ", manualPath: "生産/ライン勤務カレンダ.md" },
  },
  {
    path: "/production/progress",
    name: "ProductionProgress",
    component: () => import("@/views/production/ProductionProgress.vue"),
    meta: { pageTitle: "進捗管理", manualPath: "生産/進捗管理.md" },
  },
  {
    path: "/production/progress-only",
    name: "ProductionProgressOnly",
    component: () => import("@/views/production/ProductionProgressOnly.vue"),
    meta: { pageTitle: "進度のみ", manualPath: "生産/進捗管理.md" },
  },
  {
    path: "/production/plan-input",
    name: "ProductionPlanInput",
    component: () => import("@/views/production/ProductionPlanInput.vue"),
    meta: { pageTitle: "生産計画入力", manualPath: "生産/生産計画入力.md" },
  },
  {
    path: "/production/plan-change-history",
    name: "ProductionPlanChangeHistory",
    component: () => import("@/views/production/ProductionPlanChangeHistory.vue"),
    meta: { pageTitle: "生産計画変更履歴", manualPath: "README.md" },
  },
  {
    path: "/production/default-start-time",
    name: "DefaultStartTimeSetting",
    component: () => import("@/views/production/DefaultStartTimeSetting.vue"),
    meta: { pageTitle: "デフォルト開始時刻設定", manualPath: "生産/デフォルト開始時刻設定.md" },
  },
  {
    path: "/production/inventory",
    name: "ProductionInventory",
    component: () => import("@/views/inventory/ProductionInventory.vue"),
    meta: { pageTitle: "在庫 / 残量一覧", manualPath: "生産/在庫残量一覧.md" },
  },
  {
    path: "/production/component-inventory",
    name: "ComponentInventory",
    component: () => import("@/views/inventory/ComponentInventory.vue"),
    meta: { pageTitle: "構成部品在庫一覧", manualPath: "生産/構成部品在庫一覧.md" },
  },
  {
    path: "/production/stock-allocations",
    name: "StockAllocationList",
    component: () => import("@/views/production/StockAllocationList.vue"),
    meta: { pageTitle: "在庫引当一覧", manualPath: "生産/在庫引当一覧.md" },
  },
  {
    path: "/production/stock-allocations/new",
    name: "StockAllocationCreate",
    component: () => import("@/views/production/StockAllocationForm.vue"),
    meta: { pageTitle: "在庫引当 新規登録", manualPath: "生産/在庫引当一覧.md" },
  },
  {
    path: "/production/stock-allocations/:id/edit",
    name: "StockAllocationEdit",
    component: () => import("@/views/production/StockAllocationForm.vue"),
    props: true,
    meta: { pageTitle: "在庫引当 編集", manualPath: "生産/在庫引当一覧.md" },
  },
  {
    path: "/production/orders",
    name: "ProductionOrderList",
    component: () => import("@/views/production/ProductionOrderList.vue"),
    meta: { pageTitle: "製造指示一覧", manualPath: "生産/製造指示一覧.md" },
  },
  {
    path: "/production/orders/new",
    name: "ProductionOrderCreate",
    component: () => import("@/views/production/ProductionOrderForm.vue"),
    meta: { pageTitle: "製造指示 新規登録", manualPath: "生産/製造指示登録編集.md" },
  },
  {
    path: "/production/orders/:id/edit",
    name: "ProductionOrderEdit",
    component: () => import("@/views/production/ProductionOrderForm.vue"),
    props: true,
    meta: { pageTitle: "製造指示 編集", manualPath: "生産/製造指示登録編集.md" },
  },
  {
    path: "/production/orders/:id/actuals",
    name: "ProcessActualEntry",
    component: () => import("@/views/production/ProcessActualEntry.vue"),
    props: true,
    meta: { pageTitle: "工程実績入力", manualPath: "生産/工程実績入力.md" },
  },
  {
    path: "/production/sequence-board",
    name: "ProductionSequenceBoard",
    component: () => import("@/views/production/ProductionSequenceBoard.vue"),
    meta: { pageTitle: "日次ミックス順序ボード（7品固定運転向け）", manualPath: "生産/ミックス順序ボード.md" },
  },
  {
    path: "/production/line-monitor",
    name: "LineRealtimeMonitor",
    component: () => import("@/views/production/LineRealtimeMonitor.vue"),
    meta: { pageTitle: "ライン稼働監視", manualPath: "生産/ライン稼働監視.md" },
  },
  {
    path: "/production/mobile-input",
    name: "MobileLineInput",
    component: () => import("@/views/production/MobileLineInput.vue"),
    meta: { pageTitle: "ライン作業記録", manualPath: "生産/ライン作業記録.md" },
  },
  {
    path: "/production/mobile-process-input",
    name: "MobileProcessInput",
    component: () => import("@/views/production/MobileProcessInput.vue"),
    meta: {
      pageTitle: "工程作業記録",
      allowedRecordTypes: ["PRODUCTION", "EQUIPMENT_STATE"],
      manualPath: "生産/工程作業入力.md",
    },
  },
  {
    path: "/production/scrap-record",
    name: "ScrapRecordInput",
    component: () => import("@/views/production/MobileProcessInput.vue"),
    meta: {
      pageTitle: "仕損品記録",
      allowedRecordTypes: ["SCRAP"],
      manualPath: "生産/仕損品記録.md",
    },
  },
  {
    path: "/production/record-inquiry",
    name: "ProductionRecordInquiry",
    component: () => import("@/views/production/ProductionRecordInquiry.vue"),
    meta: { pageTitle: "生産実績照会", manualPath: "生産/生産実績照会.md" },
  },
  {
    path: "/production/record-edit",
    name: "ProductionRecordEdit",
    component: () => import("@/views/production/ProductionRecordEdit.vue"),
    meta: { pageTitle: "実績変更", manualPath: "生産/実績変更.md" },
  },
  {
    path: "/production/process-gantt",
    name: "ProcessGanttView",
    component: () => import("@/views/production/ProcessGanttView.vue"),
    meta: { pageTitle: "工程ガント", manualPath: "README.md" },
  },
  {
    path: "/production/scrap-history",
    name: "ScrapHistory",
    component: () => import("@/views/production/ScrapHistory.vue"),
    meta: { pageTitle: "仕損履歴", manualPath: "生産/仕損履歴.md" },
  },
];

export default production;
