const settings = [
  {
    path: "/settings",
    name: "SettingsMenu",
    component: () => import("@/views/settings/SettingsMenu.vue"),
    meta: { pageTitle: "設定", resource: "settings" },
  },
  {
    path: "/settings/profile",
    name: "Profile",
    component: () => import("@/views/settings/Profile.vue"),
    meta: { pageTitle: "プロフィール編集", resource: "settings.profile" },
  },
  {
    path: "/settings/users",
    name: "UserManagement",
    component: () => import("@/views/settings/UserManagement.vue"),
    meta: { pageTitle: "ユーザー管理", resource: "settings.users" },
  },
  {
    path: "/settings/user-permissions",
    name: "UserPermissionManagement",
    component: () => import("@/views/settings/UserPermissionManagement.vue"),
    meta: { pageTitle: "ユーザー権限編集", resource: "settings.user_permissions" },
  },
  {
    path: "/settings/permission-templates",
    name: "PermissionTemplates",
    component: () => import("@/views/settings/PermissionTemplates.vue"),
    meta: { pageTitle: "権限テンプレート", resource: "settings.permission_templates" },
  },
  {
    path: "/settings/smtp",
    name: "SmtpConfigSettings",
    component: () => import("@/views/settings/SmtpConfigSettings.vue"),
    meta: { pageTitle: "SMTP設定", resource: "settings.smtp" },
  },
  {
    path: "/settings/purchase-plan-lock",
    name: "PurchasePlanLockSetting",
    component: () => import("@/views/settings/PurchasePlanLockSetting.vue"),
    meta: { pageTitle: "仕入計画ロック設定", resource: "settings.purchase_plan_lock" },
  },
  {
    path: "/settings/production-plan-lock",
    name: "ProductionPlanLockSetting",
    component: () => import("@/views/settings/ProductionPlanLockSetting.vue"),
    meta: { pageTitle: "生産計画ロック設定", resource: "settings.production_plan_lock" },
  },
  {
    path: "/settings/kubota-sakai-due-plan-lock",
    name: "KubotaSakaiDuePlanLockSetting",
    component: () => import("@/views/settings/KubotaSakaiDuePlanLockSetting.vue"),
    meta: { pageTitle: "クボタ堺納期調整ロック設定", resource: "settings.production_plan_lock" },
  },
  {
    path: "/settings/scheduled-tasks",
    name: "ScheduledTasks",
    component: () => import("@/views/settings/ScheduledTasks.vue"),
    meta: { pageTitle: "定時タスク設定", manualPath: "設定/定時タスク設定.md", resource: "settings.scheduled_tasks" },
  },
  {
    path: "/settings/inventory-task-settings",
    name: "InventoryTaskSettings",
    component: () => import("@/views/settings/ScheduledTasks.vue"),
    meta: { pageTitle: "取り込み＋在庫進度計算", manualPath: "設定/定時タスク設定.md", resource: "settings.scheduled_tasks" },
  },
  {
    path: "/settings/task-settings",
    name: "TaskSettingsMenu",
    component: () => import("@/views/settings/TaskSettingsMenu.vue"),
    meta: { pageTitle: "タスク設定", resource: "settings.scheduled_tasks" },
  },
  {
    path: "/settings/auto-plan",
    name: "AutoPlanMenu",
    component: () => import("@/views/settings/AutoPlanSequenceSettings.vue"),
    meta: { pageTitle: "自動計画", resource: "settings.scheduled_tasks" },
  },
  {
    path: "/settings/auto-plan-sequence",
    name: "AutoPlanSequenceSettings",
    component: () => import("@/views/settings/AutoPlanSequenceSettings.vue"),
    meta: { pageTitle: "自動計画順序設定", resource: "settings.scheduled_tasks" },
  },
  {
    path: "/settings/stocktake-init",
    name: "StocktakeInit",
    component: () => import("@/views/settings/StocktakeInit.vue"),
    meta: { pageTitle: "棚卸初期化", resource: "settings.stocktake_init" },
  },
  {
    path: "/settings/supplier-order-pattern",
    name: "SupplierOrderPatternSettings",
    component: () => import("@/views/settings/SupplierOrderPatternSettings.vue"),
    meta: { pageTitle: "納入パターン設定", resource: "settings.supplier_order_schedule" },
  },
  {
    path: "/settings/supplier-order-schedule",
    name: "SupplierOrderScheduleSettings",
    component: () => import("@/views/settings/SupplierOrderScheduleSettings.vue"),
    meta: { pageTitle: "仕入れ先スケジュール設定", resource: "settings.supplier_order_schedule" },
  },
  {
    path: "/settings/purchase-order-approval",
    name: "PurchaseOrderApprovalSettings",
    component: () => import("@/views/settings/PurchaseOrderApprovalSettings.vue"),
    meta: { pageTitle: "発注承認者設定", resource: "settings.purchase_order_approval" },
  },
  {
    path: "/settings/departments",
    name: "DepartmentManagement",
    component: () => import("@/views/settings/DepartmentManagement.vue"),
    meta: { pageTitle: "組織管理", resource: "settings.departments" },
  },
  {
    path: "/settings/kubota-import",
    name: "KubotaImportSettings",
    component: () => import("@/views/settings/KubotaImportSettings.vue"),
    meta: { pageTitle: "クボタ堺取り込み通知設定", resource: "settings" },
  },
  {
    path: "/settings/kubota-sakai-config",
    name: "KubotaSakaiConfig",
    component: () => import("@/views/settings/KubotaSakaiConfig.vue"),
    meta: { pageTitle: "クボタ堺便計画設定", resource: "settings.kubota_sakai_config" },
  },
  {
    path: "/settings/lock-date",
    name: "LockDateSettings",
    component: () => import("@/views/settings/LockDateSettings.vue"),
    meta: { pageTitle: "締め日管理", resource: "settings.lock_date" },
  },
  {
    path: "/settings/system",
    name: "SystemSettings",
    component: () => import("@/views/settings/SystemSettings.vue"),
    meta: { pageTitle: "システム設定", resource: "settings" },
  },
];

export default settings;
