from django.urls import path

from .order_proposal_views import (
    PurchaseOrderApprovalConfigView,
    PurchaseOrderProposalApproveView,
    PurchaseOrderProposalAutoFillView,
    PurchaseOrderProposalCancelView,
    PurchaseOrderProposalDetailView,
    PurchaseOrderProposalListCreateView,
    PurchaseOrderProposalPdfView,
    PurchaseOrderProposalRejectView,
    PurchaseOrderProposalSendView,
    PurchaseOrderProposalSubmitView,
    PurchaseOrderTaskListView,
    SupplierOrderPatternDetailView,
    SupplierOrderPatternListCreateView,
    SupplierOrderScheduleDetailView,
    SupplierOrderScheduleListCreateView,
)
from .views import (
    PurchaseActualKikanMappingCandidatesView,
    PurchaseActualKikanMappingView,
    PurchaseActualDetailView,
    EngineeringChangeCaseRecalculateView,
    EngineeringChangePartDetailView,
    EngineeringChangeView,
    PurchaseActualBulkItemsView,
    PurchaseActualCandidatesView,
    PurchaseActualInquiryView,
    PurchaseActualProgressView,
    PurchaseActualRegisterView,
    PurchaseAutoDeliveryListConfigDetailView,
    PurchaseAutoDeliveryListConfigListCreateView,
    PurchaseAutoDeliveryListHolidayTrialView,
    PurchaseAutoDeliveryListRunNowView,
    PurchaseAutoOrderSendConfigDetailView,
    PurchaseAutoOrderSendConfigListCreateView,
    PurchaseAutoOrderSendHolidayTrialView,
    PurchaseAutoOrderSendRunNowView,
    PurchaseDeliveryListAutoTemplateView,
    PurchaseDeliveryListExcelDownloadView,
    PurchaseDeliveryNotePdfDownloadView,
    PurchaseDeliveryScheduleView,
    PurchaseReceiptPdfDownloadView,
    PurchaseOutsourceProgressCompareView,
    PurchaseProgressRecalculateView,
    PurchaseProgressExcelDownloadView,
    PurchaseProgressPdfDownloadView,
    PurchaseReceivingDeliveryListTemplateView,
    PurchasePlanLockSettingView,
    PurchaseReceivingHistoryView,
    PurchaseReceivingView,
)
from .views_truck_load_check import (
    PurchaseAutoOrderSendTruckLoadCheckCancelView,
    PurchaseAutoOrderSendTruckLoadCheckView,
)

urlpatterns = [
    path('purchase-plan-lock-setting/', PurchasePlanLockSettingView.as_view(), name='purchase-plan-lock-setting'),
    path('engineering-changes/', EngineeringChangeView.as_view(), name='engineering-changes'),
    path('engineering-changes/parts/<int:pk>/', EngineeringChangePartDetailView.as_view(), name='engineering-change-part-detail'),
    path('engineering-changes/cases/<int:case_id>/recalculate/', EngineeringChangeCaseRecalculateView.as_view(), name='engineering-change-case-recalculate'),
    path('purchase-actual/candidates/', PurchaseActualCandidatesView.as_view(), name='purchase-actual-candidates'),
    path('purchase-actual/inquiry/', PurchaseActualInquiryView.as_view(), name='purchase-actual-inquiry'),
    path('purchase-actual/progress/', PurchaseActualProgressView.as_view(), name='purchase-actual-progress'),
    path('purchase-actual/register/', PurchaseActualRegisterView.as_view(), name='purchase-actual-register'),
    path('purchase-actual/<int:record_id>/', PurchaseActualDetailView.as_view(), name='purchase-actual-detail'),
    path('purchase-actual/bulk-items/', PurchaseActualBulkItemsView.as_view(), name='purchase-actual-bulk-items'),
    path('supplier-order-patterns/', SupplierOrderPatternListCreateView.as_view(), name='supplier-order-patterns'),
    path('supplier-order-patterns/<int:pk>/', SupplierOrderPatternDetailView.as_view(), name='supplier-order-pattern-detail'),
    path('supplier-order-schedules/', SupplierOrderScheduleListCreateView.as_view(), name='supplier-order-schedules'),
    path('supplier-order-schedules/<int:pk>/', SupplierOrderScheduleDetailView.as_view(), name='supplier-order-schedule-detail'),
    path('purchase-order-proposals/', PurchaseOrderProposalListCreateView.as_view(), name='purchase-order-proposals'),
    path('purchase-order-proposals/<int:pk>/', PurchaseOrderProposalDetailView.as_view(), name='purchase-order-proposal-detail'),
    path('purchase-order-proposals/<int:pk>/submit/', PurchaseOrderProposalSubmitView.as_view(), name='purchase-order-proposal-submit'),
    path('purchase-order-proposals/<int:pk>/approve/', PurchaseOrderProposalApproveView.as_view(), name='purchase-order-proposal-approve'),
    path('purchase-order-proposals/<int:pk>/reject/', PurchaseOrderProposalRejectView.as_view(), name='purchase-order-proposal-reject'),
    path('purchase-order-proposals/<int:pk>/cancel/', PurchaseOrderProposalCancelView.as_view(), name='purchase-order-proposal-cancel'),
    path('purchase-order-proposals/<int:pk>/send/', PurchaseOrderProposalSendView.as_view(), name='purchase-order-proposal-send'),
    path('purchase-order-proposals/<int:pk>/pdf/', PurchaseOrderProposalPdfView.as_view(), name='purchase-order-proposal-pdf'),
    path('purchase-order-proposals/<int:pk>/auto_fill/', PurchaseOrderProposalAutoFillView.as_view(), name='purchase-order-proposal-auto-fill'),
    path('purchase-order-tasks/', PurchaseOrderTaskListView.as_view(), name='purchase-order-tasks'),
    path('purchase-order-approval-config/', PurchaseOrderApprovalConfigView.as_view(), name='purchase-order-approval-config'),
    path('purchase-receiving/', PurchaseReceivingView.as_view(), name='purchase-receiving'),
    path('purchase-receiving/history/', PurchaseReceivingHistoryView.as_view(), name='purchase-receiving-history'),
    path('purchase-receiving/delivery-list-template/', PurchaseReceivingDeliveryListTemplateView.as_view(), name='purchase-receiving-delivery-list-template'),
    path('purchase-receiving/delivery-list-auto-template/', PurchaseDeliveryListAutoTemplateView.as_view(), name='purchase-receiving-delivery-list-auto-template'),
    path('purchase-receiving/delivery-list-excel/', PurchaseDeliveryListExcelDownloadView.as_view(), name='purchase-receiving-delivery-list-excel'),
    path('purchase-receiving/recalculate-progress/', PurchaseProgressRecalculateView.as_view(), name='purchase-receiving-recalculate-progress'),
    path('purchase-receiving/progress-excel/', PurchaseProgressExcelDownloadView.as_view(), name='purchase-receiving-progress-excel'),
    path('purchase-receiving/progress-pdf/', PurchaseProgressPdfDownloadView.as_view(), name='purchase-receiving-progress-pdf'),
    path('purchase-receiving/delivery-note-pdf/', PurchaseDeliveryNotePdfDownloadView.as_view(), name='purchase-receiving-delivery-note-pdf'),
    path('purchase-receiving/receipt-pdf/', PurchaseReceiptPdfDownloadView.as_view(), name='purchase-receiving-receipt-pdf'),
    path('purchase-receiving/outsource-progress-compare/', PurchaseOutsourceProgressCompareView.as_view(), name='purchase-receiving-outsource-progress-compare'),
    path('purchase-delivery-schedules/', PurchaseDeliveryScheduleView.as_view(), name='purchase-delivery-schedules'),
    path('purchase-auto-delivery-list-configs/', PurchaseAutoDeliveryListConfigListCreateView.as_view(), name='purchase-auto-delivery-list-configs'),
    path('purchase-auto-delivery-list-configs/<int:pk>/', PurchaseAutoDeliveryListConfigDetailView.as_view(), name='purchase-auto-delivery-list-config-detail'),
    path('purchase-auto-delivery-list-configs/<int:pk>/run-now/', PurchaseAutoDeliveryListRunNowView.as_view(), name='purchase-auto-delivery-list-run-now'),
    path('purchase-auto-delivery-list-configs/<int:pk>/holiday-trial/', PurchaseAutoDeliveryListHolidayTrialView.as_view(), name='purchase-auto-delivery-list-holiday-trial'),
    path('purchase-auto-order-send-configs/', PurchaseAutoOrderSendConfigListCreateView.as_view(), name='purchase-auto-order-send-configs'),
    path('purchase-auto-order-send-configs/<int:pk>/', PurchaseAutoOrderSendConfigDetailView.as_view(), name='purchase-auto-order-send-config-detail'),
    path('purchase-auto-order-send-configs/<int:pk>/run-now/', PurchaseAutoOrderSendRunNowView.as_view(), name='purchase-auto-order-send-run-now'),
    path('purchase-auto-order-send-configs/<int:pk>/holiday-trial/', PurchaseAutoOrderSendHolidayTrialView.as_view(), name='purchase-auto-order-send-holiday-trial'),
    path('purchase-auto-order-send-configs/<int:pk>/truck-load-check/', PurchaseAutoOrderSendTruckLoadCheckView.as_view(), name='purchase-auto-order-send-truck-load-check'),
    path('purchase-auto-order-send-truck-load-check/', PurchaseAutoOrderSendTruckLoadCheckView.as_view(), name='purchase-auto-order-send-truck-load-check'),
    path('purchase-auto-order-send-truck-load-check/cancel/', PurchaseAutoOrderSendTruckLoadCheckCancelView.as_view(), name='purchase-auto-order-send-truck-load-check-cancel'),
    path('purchase-actual-kikan-mapping/', PurchaseActualKikanMappingView.as_view(), name='purchase-actual-kikan-mapping'),
    path('purchase-actual-kikan-mapping/candidates/', PurchaseActualKikanMappingCandidatesView.as_view(), name='purchase-actual-kikan-mapping-candidates'),
]
