# Generated by Django 5.2.9 on 2025-12-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_routingstep_hierarchy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='management_unit',
            field=models.CharField(choices=[('DAY', '日単位管理'), ('MINUTE', '分単位管理')], default='MINUTE', help_text='日単位管理（マクロ計画）または分単位管理（ミクロ実行）', max_length=10, verbose_name='管理単位'),
        ),
    ]
