# Generated by Django 5.2.9 on 2025-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_add_coproduct_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_line_final_product',
            field=models.BooleanField(default=False, help_text='そのラインで最後に出力される製品（次のラインへ渡す中間品）', verbose_name='ライン最終品'),
        ),
    ]
