# Generated by Django 5.2.9 on 2025-12-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_line_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pattern_code', models.CharField(max_length=20, unique=True, verbose_name='パターンコード')),
                ('pattern_name', models.CharField(max_length=50, verbose_name='パターン名')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('work_minutes', models.IntegerField(verbose_name='勤務時間(分)')),
                ('break_minutes', models.IntegerField(default=0, verbose_name='休憩時間(分)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '勤務パターン',
                'verbose_name_plural': '勤務パターン',
                'db_table': 'm_work_pattern',
            },
        ),
        migrations.AddField(
            model_name='calendarday',
            name='work_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.workpattern', verbose_name='勤務パターン'),
        ),
    ]
