# Generated by Django 5.2.9 on 2025-12-17 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_workpattern_calendarday_work_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpattern',
            name='break_minutes',
        ),
        migrations.RemoveField(
            model_name='workpattern',
            name='work_minutes',
        ),
        migrations.AddField(
            model_name='workpattern',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時刻'),
        ),
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('break_start', models.TimeField(verbose_name='休憩開始時刻')),
                ('break_end', models.TimeField(verbose_name='休憩終了時刻')),
                ('order', models.IntegerField(default=1, verbose_name='順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('work_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_times', to='masters.workpattern', verbose_name='勤務パターン')),
            ],
            options={
                'verbose_name': '休憩時間',
                'verbose_name_plural': '休憩時間',
                'db_table': 'm_break_time',
                'ordering': ['work_pattern', 'order'],
            },
        ),
    ]
