# Generated by Django 5.2.9 on 2025-12-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0018_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.line', verbose_name='ライン情報'),
        ),
        migrations.AddField(
            model_name='product',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.process', verbose_name='工程情報'),
        ),
        migrations.AddField(
            model_name='product',
            name='management_unit',
            field=models.CharField(blank=True, null=True, choices=[('DAY', '日単位管理'), ('MINUTE', '分単位管理')], max_length=10, verbose_name='管理区分'),
        ),
    ]
