# Generated by Django 5.2.9 on 2026-01-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0023_line_line_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerCapacity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='容器名')),
                ('capacity', models.IntegerField(verbose_name='入り数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '容器仕様',
                'verbose_name_plural': '容器仕様',
                'db_table': 'm_container_capacity',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=50, unique=True, verbose_name='グループコード')),
                ('group_name', models.CharField(max_length=100, verbose_name='グループ名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '製品グループ',
                'verbose_name_plural': '製品グループ',
                'db_table': 'm_product_group',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='容器入り数'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='機種名'),
        ),
        migrations.AddField(
            model_name='product',
            name='used_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.containercapacity', verbose_name='使用容器'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.productgroup', verbose_name='製品グループ'),
        ),
    ]
