# Generated by Django 5.2.9 on 2026-01-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0027_alter_capacity_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(max_length=50, verbose_name='連絡先種別')),
                ('company_name', models.CharField(max_length=255, verbose_name='会社名')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='部署名')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当者名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話番号')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '連絡先',
                'verbose_name_plural': '連絡先',
                'db_table': 'm_contacts',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
