# Generated by Django 5.2.9 on 2026-02-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_bomitem_is_coproduct_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('ASSEMBLY', '組立品'), ('SINGLE', '単品'), ('MATERIAL', '材料'), ('PURCHASED', '購入品'), ('UNKNOWN', '未定')], max_length=20, null=True, verbose_name='カテゴリ'),
        ),
    ]
