# Generated by Django 5.2.9 on 2026-02-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['calendar_code'], 'verbose_name': 'カレンダ', 'verbose_name_plural': 'カレンダ'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['line_code'], 'verbose_name': 'ライン', 'verbose_name_plural': 'ライン'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['supplier_code'], 'verbose_name': '仕入先', 'verbose_name_plural': '仕入先'},
        ),
    ]
