# Generated by Django 5.2.9 on 2026-03-01 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0031_alter_calendar_options_alter_line_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_lot_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='最小発注数'),
        ),
        migrations.AddField(
            model_name='product',
            name='order_lot_multiple',
            field=models.PositiveIntegerField(default=1, verbose_name='発注倍数'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.calendar', verbose_name='仕入先専用カレンダー'),
        ),
    ]
