# Generated by Django 5.2.9 on 2026-03-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_product_order_lot_min_product_order_lot_multiple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='order_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='送信メールアドレス'),
        ),
    ]
