# Generated by Django 5.2.9 on 2026-03-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0033_supplier_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('equipment_code', models.CharField(max_length=30, unique=True, verbose_name='設備コード')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='設備名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.line', verbose_name='ライン')),
            ],
            options={
                'verbose_name': '設備',
                'verbose_name_plural': '設備',
                'db_table': 'm_equipment',
                'ordering': ['display_order', 'equipment_code'],
            },
        ),
    ]
