# Generated by Django 5.2.9 on 2026-03-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0034_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.process', verbose_name='工程'),
        ),
    ]
