# Generated by Django 5.2.9 on 2026-03-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0037_merge_0027_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='use_direct_process',
            field=models.BooleanField(default=False, help_text='ONにすると自動計画展開でルーティングを使わず指定工程に直接書き込む（スポット系ライン向け）', verbose_name='工程直接展開'),
        ),
    ]
