# Generated by Django 5.2.9 on 2026-03-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0038_add_use_direct_process_to_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='next_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_process_products', to='masters.process', verbose_name='後工程'),
        ),
    ]
