# Generated by Django 5.2.9 on 2026-04-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0041_routing_valid_from_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routing',
            options={'ordering': ['product', 'routing_code', '-valid_from_datetime'], 'verbose_name': 'ルーティング', 'verbose_name_plural': 'ルーティング'},
        ),
        migrations.AlterUniqueTogether(
            name='routing',
            unique_together=set(),
        ),
    ]
