# Generated by Django 5.2.9 on 2026-04-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0042_remove_routing_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingstep',
            name='source_bom_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_routing_steps', to='masters.bomitem', verbose_name='元BOM明細'),
        ),
    ]
