# Generated by Django 5.2.9 on 2026-04-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0043_routingstep_source_bom_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubotaSakaiTruck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='便名')),
                ('width', models.IntegerField(verbose_name='荷台幅(mm)')),
                ('depth', models.IntegerField(verbose_name='荷台奥行(mm)')),
                ('height', models.IntegerField(verbose_name='荷台高さ(mm)')),
                ('max_weight', models.IntegerField(verbose_name='最大積載重量(kg)')),
                ('departure_time', models.TimeField(verbose_name='出発時刻')),
                ('arrival_time', models.TimeField(verbose_name='到着時刻')),
                ('arrival_day_offset', models.IntegerField(default=0, help_text='0=当日着, 1=翌日着', verbose_name='到着日オフセット')),
                ('default_use', models.BooleanField(default=True, verbose_name='常用便')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'クボタ堺向け便',
                'verbose_name_plural': 'クボタ堺向け便',
                'db_table': 'm_kubota_sakai_truck',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
