# Generated by Django 5.2.9 on 2026-04-22 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0046_add_alias_name_to_kubota_sakai_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingstep',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier', verbose_name='外作先'),
        ),
    ]
