# Generated by Django 5.2.9 on 2026-05-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0048_alter_product_category_add_outsourced'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transfer_destination',
            field=models.CharField(blank=True, choices=[('INLINE', '社内ライン'), ('INPAINT', '社内塗装'), ('CWL', 'CWL'), ('KOWA', '興和'), ('DIRECT', '直納'), ('OTHER', 'その他')], max_length=10, null=True, verbose_name='移動先'),
        ),
    ]
