# Generated by Django 5.2.9 on 2026-05-19 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0050_product_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_no', models.CharField(max_length=20, unique=True, verbose_name='管理No.')),
                ('device_type', models.CharField(choices=[('T', 'タブレット'), ('S', 'スマートフォン')], max_length=1, verbose_name='種別')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='製造元')),
                ('model_number', models.CharField(max_length=100, verbose_name='型番')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='S/N')),
                ('purchase_date', models.CharField(blank=True, default='', max_length=20, verbose_name='導入年月')),
                ('location', models.CharField(max_length=200, verbose_name='配置場所')),
                ('manager_name', models.CharField(max_length=100, verbose_name='管理責任者')),
                ('status', models.CharField(choices=[('ACTIVE', '使用中'), ('IDLE', '遊休'), ('DISPOSED', '廃却')], default='ACTIVE', max_length=10, verbose_name='状態')),
                ('idle_date', models.DateField(blank=True, null=True, verbose_name='遊休化年月')),
                ('disposed_date', models.DateField(blank=True, null=True, verbose_name='管理除外年月')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '携帯端末',
                'verbose_name_plural': '携帯端末',
                'ordering': ['-management_no'],
            },
        ),
        migrations.CreateModel(
            name='MobileDeviceInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_date', models.DateField(verbose_name='棚卸日')),
                ('result', models.CharField(choices=[('OK', '合格'), ('MISMATCH', '不一致'), ('LOST', '紛失'), ('BROKEN', '故障')], max_length=10, verbose_name='結果')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_inventory_approvals', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='masters.mobiledevice', verbose_name='端末')),
            ],
            options={
                'verbose_name': '端末棚卸記録',
                'verbose_name_plural': '端末棚卸記録',
                'ordering': ['-inventory_date', 'device__management_no'],
            },
        ),
    ]
