# Generated by Django 5.2.9 on 2026-05-20 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0051_mobile_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_key', models.CharField(max_length=200, unique=True, verbose_name='ドキュメントキー')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, default='', verbose_name='本文(Markdown)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'マニュアルドキュメント',
                'verbose_name_plural': 'マニュアルドキュメント',
                'ordering': ['doc_key'],
            },
        ),
    ]
