# Generated by Django 5.2.9 on 2026-06-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0060_product_stock_location_processing_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100, verbose_name='置き場名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '製品保管場所',
                'verbose_name_plural': '製品保管場所',
                'db_table': 'm_product_stock_location',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('product', 'location_name')},
            },
        ),
    ]
