# Generated by Django 5.2.9 on 2026-06-13 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0062_migrate_stock_location_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingstep',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.process', verbose_name='工程'),
        ),
    ]
