# Generated by Django 5.2.9 on 2026-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0063_allow_null_process_on_routing_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='identification_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='識別記号'),
        ),
    ]
