# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0064_add_identification_code_and_sei_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='containercapacity',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='画像URL'),
        ),
    ]
