# Generated by Django 5.2.9

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0065_containercapacity_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerCapacityImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255, verbose_name='画像URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='masters.containercapacity', verbose_name='容器')),
            ],
            options={
                'db_table': 'm_container_capacity_image',
                'verbose_name': '容器写真',
                'verbose_name_plural': '容器写真',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
