# Generated by Django 5.2.9 on 2026-07-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0066_containercapacityimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='入数')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_containers', to='masters.containercapacity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_containers', to='masters.product')),
            ],
            options={
                'verbose_name': '製品別容器入数',
                'verbose_name_plural': '製品別容器入数',
                'db_table': 'm_product_container',
                'unique_together': {('product', 'container')},
            },
        ),
    ]
