# Generated by Django 5.2.9 on 2026-07-15 22:44

from django.db import migrations


def forward(apps, schema_editor):
    Product = apps.get_model('masters', 'Product')
    ProductContainer = apps.get_model('masters', 'ProductContainer')
    rows = Product.objects.filter(
        used_container__isnull=False,
        capacity__isnull=False,
        capacity__gt=0,
    ).values_list('id', 'used_container_id', 'capacity')
    objs = [
        ProductContainer(product_id=pid, container_id=cid, capacity=cap)
        for pid, cid, cap in rows
    ]
    if objs:
        ProductContainer.objects.bulk_create(objs, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0067_add_product_container'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
