# Generated by Django 5.2.9 on 2026-07-16 15:35

from django.db import migrations, models


def normalize_blank_container_codes(apps, schema_editor):
    ContainerCapacity = apps.get_model('masters', 'ContainerCapacity')
    ContainerCapacity.objects.filter(container_code='').update(container_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0068_migrate_product_container_data'),
    ]

    operations = [
        migrations.RunPython(normalize_blank_container_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='containercapacity',
            name='container_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='容器コード'),
        ),
        migrations.AlterField(
            model_name='containercapacity',
            name='name',
            field=models.CharField(max_length=50, verbose_name='容器名'),
        ),
    ]
