# Generated by Django 5.2.9 on 2026-07-21 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0070_kubota_sakai_truck_physical_truck_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineCycleTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cycle_time_sec', models.DecimalField(decimal_places=2, help_text='1個あたりの通過時間（秒）', max_digits=10, verbose_name='サイクルタイム(秒/個)')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_cycle_times', to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_cycle_times', to='masters.process', verbose_name='工程')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_cycle_times', to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': 'ライン別サイクルタイム',
                'verbose_name_plural': 'ライン別サイクルタイム',
                'db_table': 'm_line_cycle_time',
                'indexes': [models.Index(fields=['line', 'is_active'], name='m_line_cycl_line_id_b858a5_idx')],
                'unique_together': {('product', 'line', 'process')},
            },
        ),
    ]
