# Generated by Django 5.2.9 on 2026-07-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0072_routingchangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='equipment_count',
            field=models.PositiveIntegerField(default=1, help_text='負荷計算用。負荷時間 ÷ 設備台数 = 実負荷', verbose_name='設備台数'),
        ),
        migrations.AddField(
            model_name='process',
            name='operating_rate',
            field=models.DecimalField(decimal_places=2, default=100, help_text='CT補正用。実績CT ÷ (稼働率/100) = 補正CT', max_digits=5, verbose_name='稼働率(%)'),
        ),
    ]
