# Generated by Django 5.2.9 on 2026-07-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0073_add_process_coefficients'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarday',
            name='is_holiday_work',
            field=models.BooleanField(default=False, verbose_name='休日出勤'),
        ),
    ]
