# Generated by Django 5.2.9 on 2026-08-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0075_add_is_delivery_day_to_calendar_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='containercapacity',
            name='orientation',
            field=models.CharField(blank=True, choices=[('free', '自由（自動判定）'), ('long', '容器長手'), ('short', '容器短手')], default='free', help_text='トラック荷台の両側（幅方向）に向ける辺。容器長手=長い辺を両側へ、容器短手=短い辺を両側へ、自由=自動判定', max_length=10, verbose_name='向き'),
        ),
    ]
