# Generated by Django 5.2.9 on 2026-08-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0076_containercapacity_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containercapacity',
            name='orientation',
            field=models.CharField(blank=True, choices=[('free', '自由（自動判定）'), ('long', '容器長手'), ('short', '容器短手')], default='free', help_text='トラック両側（荷台長手方向＝奥行き）へ向ける辺。容器長手=長い辺を両側（長手方向）へ、容器短手=短い辺を両側（長手方向）へ、自由=自動判定', max_length=10, verbose_name='向き'),
        ),
    ]
