# Generated by Django 5.2.9 on 2026-08-07 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0077_alter_containercapacity_orientation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierTruck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='便名')),
                ('alias_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='俗称')),
                ('physical_truck_code', models.CharField(blank=True, help_text='同じ物理トラックとして占有率を合算する便に同じ値を設定する', max_length=50, null=True, verbose_name='同一車両キー')),
                ('width', models.IntegerField(verbose_name='荷台幅(mm)')),
                ('depth', models.IntegerField(verbose_name='荷台奥行(mm)')),
                ('height', models.IntegerField(verbose_name='荷台高さ(mm)')),
                ('max_weight', models.IntegerField(verbose_name='最大積載重量(kg)')),
                ('departure_time', models.TimeField(verbose_name='出発時刻')),
                ('arrival_time', models.TimeField(verbose_name='到着時刻')),
                ('arrival_day_offset', models.IntegerField(default=0, help_text='0=当日着, 1=翌日着', verbose_name='到着日オフセット')),
                ('default_use', models.BooleanField(default=True, verbose_name='常用便')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.supplier', verbose_name='仕入先')),
            ],
            options={
                'verbose_name': '仕入れ先トラック',
                'verbose_name_plural': '仕入れ先トラック',
                'db_table': 'm_supplier_truck',
                'ordering': ['supplier', 'display_order', 'name'],
                'unique_together': {('supplier', 'name')},
            },
        ),
    ]
