# Generated by Django 5.2.9 on 2026-08-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0078_suppliertruck'),
    ]

    operations = [
        migrations.AddField(
            model_name='containercapacity',
            name='parent_capacity',
            field=models.IntegerField(blank=True, help_text='親容器1つにこの容器が何個入るか', null=True, verbose_name='親容器あたり収容数'),
        ),
        migrations.AddField(
            model_name='containercapacity',
            name='parent_container',
            field=models.ForeignKey(blank=True, help_text='この容器を入れる外側の容器（例: ポリコンを入れる小アミ）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_containers', to='masters.containercapacity', verbose_name='親容器'),
        ),
    ]
