# Generated by Django 5.2.9 on 2026-08-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0079_containercapacity_parent_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubotasakaitruck',
            name='container_gap',
            field=models.IntegerField(default=0, verbose_name='容器間隔(mm)'),
        ),
        migrations.AddField(
            model_name='suppliertruck',
            name='container_gap',
            field=models.IntegerField(default=0, verbose_name='容器間隔(mm)'),
        ),
    ]
