# Generated by Django 5.2.9 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0082_mobiledevicehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='担当者名'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='電話番号'),
        ),
    ]
