# Generated by Django 5.2.9 on 2026-09-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0083_supplier_contact_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='two_person_only',
            field=models.BooleanField(default=False, verbose_name='2人1設備専用'),
        ),
    ]
