# Generated by Django 5.2.9 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0084_add_two_person_only_to_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special_management_material',
            field=models.BooleanField(default=False, verbose_name='特別管理材料'),
        ),
    ]
