# Generated by Django 5.2.9 on 2026-09-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0085_add_special_management_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarday',
            name='is_order_day',
            field=models.BooleanField(default=False, verbose_name='発注日'),
        ),
    ]
