# Generated by Django 5.2.9 on 2025-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_stgorderdaily_product_name_halfwidth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'オープン'), ('CLOSED', 'クローズ'), ('CANCELED', 'キャンセル'), ('SUPERSEDED', '無効')], default='OPEN', max_length=20, verbose_name='ステータス'),
        ),
    ]
