# Generated by Django 5.2.9 on 2025-12-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_linebacklog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='linebacklog',
            new_name='line_backlo_plan_da_bdedd1_idx',
            old_name='line_backl_plan_da_8b86d8_idx',
        ),
        migrations.RenameIndex(
            model_name='linedemand',
            new_name='t_line_dema_line_id_f91926_idx',
            old_name='idx_linedemand_line_date',
        ),
        migrations.RenameIndex(
            model_name='linedemand',
            new_name='t_line_dema_product_9484e1_idx',
            old_name='idx_linedemand_product',
        ),
        migrations.AddField(
            model_name='linebacklog',
            name='actual_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='linebacklog',
            name='plan_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='linebacklog',
            name='planned_stock_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='linebacklog',
            name='stock_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
