# Generated by Django 5.2.9 on 2025-12-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_linebacklog_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebacklog',
            name='actual_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linebacklog',
            name='demand_qty_plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linebacklog',
            name='order_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linebacklog',
            name='plan_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linebacklog',
            name='planned_stock_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linebacklog',
            name='stock_qty',
            field=models.IntegerField(default=0),
        ),
    ]
