# Generated by Django 5.2.9 on 2025-12-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_add_management_unit_to_process'),
        ('orders', '0014_alter_linebacklog_actual_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(help_text='論理的な保管場所（倉庫、ロケーション等）', max_length=50, verbose_name='保管場所')),
                ('current_stock', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='現在庫数')),
                ('reserved_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='引当済数量')),
                ('min_stock_qty', models.DecimalField(decimal_places=3, help_text='この数量を下回るとアラート', max_digits=14, verbose_name='最小在庫数')),
                ('is_bottleneck', models.BooleanField(default=False, help_text='在庫不足によるボトルネック部品フラグ', verbose_name='ボトルネック品')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '在庫引当',
                'verbose_name_plural': '在庫引当',
                'db_table': 't_stock_allocation',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='製造指示番号')),
                ('order_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='指示数量')),
                ('scheduled_start_date', models.DateField(verbose_name='予定開始日')),
                ('scheduled_end_date', models.DateField(verbose_name='予定完了日')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='実績開始日')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='実績完了日')),
                ('status', models.CharField(choices=[('PLANNED', '計画済'), ('RELEASED', '指示済'), ('IN_PROGRESS', '進行中'), ('COMPLETED', '完了'), ('CANCELED', '中止')], default='PLANNED', max_length=20, verbose_name='ステータス')),
                ('priority', models.IntegerField(default=0, help_text='数値が大きいほど優先度が高い', verbose_name='優先度')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.line', verbose_name='ライン')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product', verbose_name='製品')),
                ('routing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.routing', verbose_name='ルーティング')),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='orders.stockallocation', verbose_name='在庫引当')),
            ],
            options={
                'verbose_name': '製造指示',
                'verbose_name_plural': '製造指示',
                'db_table': 't_production_order',
            },
        ),
        migrations.CreateModel(
            name='ProcessActual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('completed_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='完了数量')),
                ('actual_duration_min', models.IntegerField(help_text='実際にかかった時間（分）', verbose_name='実績工数(分)')),
                ('completed_at', models.DateTimeField(verbose_name='完了日時')),
                ('operator', models.CharField(blank=True, help_text='作業者コードまたは名前', max_length=50, null=True, verbose_name='作業者')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                ('routing_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.routingstep', verbose_name='ルーティング工程')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals', to='orders.productionorder', verbose_name='製造指示')),
            ],
            options={
                'verbose_name': '工程別製造実績',
                'verbose_name_plural': '工程別製造実績',
                'db_table': 't_process_actual',
                'indexes': [models.Index(fields=['production_order', 'routing_step'], name='t_process_a_product_e4c06e_idx'), models.Index(fields=['completed_at'], name='t_process_a_complet_8e2d15_idx'), models.Index(fields=['process'], name='t_process_a_process_badc6a_idx'), models.Index(fields=['line'], name='t_process_a_line_id_05a671_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['product'], name='t_stock_all_product_725da3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockallocation',
            index=models.Index(fields=['is_bottleneck'], name='t_stock_all_is_bott_e50c19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockallocation',
            unique_together={('product', 'location')},
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status'], name='t_productio_status_fe0278_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['scheduled_start_date'], name='t_productio_schedul_f1d93f_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['product'], name='t_productio_product_ba4de4_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['line'], name='t_productio_line_id_833043_idx'),
        ),
    ]
