# Generated by Django 5.2.9 on 2025-12-16 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_line_calendar'),
        ('orders', '0015_add_production_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineStatus',
            fields=[
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='masters.line', verbose_name='ライン')),
                ('current_state', models.CharField(choices=[('RUNNING', '運転中'), ('IDLE', '待機'), ('SETUP', '段取り中'), ('MAINTENANCE', '保全中'), ('BREAKDOWN', '故障'), ('STOPPED', '停止')], default='STOPPED', max_length=20, verbose_name='現在の状態')),
                ('today_output', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='本日生産数')),
                ('today_plan', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='本日計画数')),
                ('current_product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='現在生産品番')),
                ('current_product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='現在生産品名')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最終更新時刻')),
            ],
            options={
                'verbose_name': 'ライン状態',
                'verbose_name_plural': 'ライン状態',
                'db_table': 't_line_status',
            },
        ),
        migrations.CreateModel(
            name='LineRealtimeRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='記録時刻')),
                ('record_type', models.CharField(choices=[('PRODUCTION', '生産完成'), ('EQUIPMENT_STATE', '設備状態変更'), ('OPERATOR_ACTION', '作業者アクション')], max_length=20, verbose_name='記録タイプ')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='数量')),
                ('equipment_state', models.CharField(blank=True, choices=[('RUNNING', '運転中'), ('IDLE', '待機'), ('SETUP', '段取り中'), ('MAINTENANCE', '保全中'), ('BREAKDOWN', '故障'), ('STOPPED', '停止')], max_length=20, null=True, verbose_name='設備状態')),
                ('event_data', models.JSONField(blank=True, null=True, verbose_name='イベント詳細データ')),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ロット番号')),
                ('operator_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='作業者名')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.line', verbose_name='ライン')),
            ],
            options={
                'verbose_name': 'ライン実時間記録',
                'verbose_name_plural': 'ライン実時間記録',
                'db_table': 't_line_realtime_record',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['line', 'timestamp'], name='t_line_real_line_id_c0b2f1_idx'), models.Index(fields=['record_type'], name='t_line_real_record__e4761e_idx')],
            },
        ),
    ]
