# Generated by Django 5.2.9 on 2025-12-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_line_calendar'),
        ('orders', '0017_linebacklog_sequence_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='linerealtimerecord',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product', verbose_name='製品'),
        ),
        migrations.AddField(
            model_name='linerealtimerecord',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='製品コード'),
        ),
        migrations.AddField(
            model_name='linerealtimerecord',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='品名'),
        ),
        migrations.AddIndex(
            model_name='linerealtimerecord',
            index=models.Index(fields=['product_code'], name='t_line_real_product_1730d5_idx'),
        ),
    ]
