# Generated by Django 5.2.9 on 2025-12-31 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_stgorderdaily_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgorderdaily',
            name='raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.stgorderraw', verbose_name='生データ（旧・非推奨）'),
        ),
        migrations.CreateModel(
            name='StgOrderRawRieden',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=20, verbose_name='得意先コード')),
                ('order_type', models.CharField(choices=[('FIRM', '確定'), ('FORECAST', '内示')], max_length=20, verbose_name='受注タイプ')),
                ('source_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='ソースシステム')),
                ('source_file', models.CharField(blank=True, max_length=200, null=True, verbose_name='ソースファイル')),
                ('source_row_no', models.IntegerField(verbose_name='ソース行番号')),
                ('order_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='発注コード')),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='製品コード')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='納期')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='数量')),
                ('raw_payload', models.JSONField(verbose_name='生データ（JSON）')),
                ('parse_status', models.CharField(choices=[('PENDING', '未処理'), ('PARSED', '処理済'), ('ERROR', 'エラー')], default='PENDING', max_length=20, verbose_name='解析ステータス')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'リーデン受注取込ステージング（生データ）',
                'verbose_name_plural': 'リーデン受注取込ステージング（生データ）',
                'db_table': 'stg_order_raw_rieden',
                'indexes': [models.Index(fields=['customer_code'], name='stg_order_r_custome_e453b6_idx'), models.Index(fields=['parse_status'], name='stg_order_r_parse_s_47ba38_idx'), models.Index(fields=['source_file'], name='stg_order_r_source__141622_idx')],
            },
        ),
        migrations.AddField(
            model_name='stgorderdaily',
            name='raw_rieden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.stgorderrawrieden', verbose_name='リーデン生データ'),
        ),
    ]
