# Generated by Django 5.2.9 on 2026-01-01 14:25

from django.db import migrations, models


def populate_order_type(apps, schema_editor):
    """Populate order_type in OrderLine from related Order"""
    OrderLine = apps.get_model('orders', 'OrderLine')
    Order = apps.get_model('orders', 'Order')

    # Update all OrderLine records with order_type from their Order
    for order in Order.objects.all():
        OrderLine.objects.filter(order=order).update(order_type=order.order_type)


def reverse_populate_order_type(apps, schema_editor):
    """Reverse migration - clear order_type"""
    OrderLine = apps.get_model('orders', 'OrderLine')
    OrderLine.objects.all().update(order_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_stgorderdaily_raw_stgorderrawrieden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='order_type',
            field=models.CharField(blank=True, choices=[('FIRM', '確定'), ('FORECAST', '内示')], max_length=20, null=True, verbose_name='受注タイプ'),
        ),
        migrations.RunPython(populate_order_type, reverse_populate_order_type),
    ]
