# Generated by Django 5.2.9 on 2026-01-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_orderline_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='actual_shipment_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='出荷実績数'),
        ),
    ]
