# Generated by Django 5.2.9 on 2026-01-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_stgorderrawrieden_order_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgorderrawrieden',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='発注日'),
        ),
    ]
