# Generated by Django 5.2.9 on 2026-01-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_stgorderrawrieden_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgorderrawtiera',
            name='delivery_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='送付No'),
        ),
    ]
