# Generated by Django 5.2.9 on 2026-01-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_stgorderrawtiera_delivery_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='customer_order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='顧客発注番号'),
        ),
    ]
