# Generated by Django 5.2.9 on 2026-02-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_remove_migrated_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgorderrawtiera',
            name='order_document_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='注文番号'),
        ),
    ]
