# Generated by Django 5.2.9 on 2026-04-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0041_routing_valid_from_datetime_and_more'),
        ('orders', '0044_kubotasakaiimportconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='expanded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='展開日時'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='is_expanded',
            field=models.BooleanField(default=False, verbose_name='展開済み'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order_type', 'is_expanded'], name='t_order_lin_order_t_24884d_idx'),
        ),
    ]
