# Generated by Django 5.2.9 on 2026-04-15 02:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_orderline_expanded_at_orderline_is_expanded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KubotaSakaiDueAdjustment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('split_no', models.PositiveIntegerField(verbose_name='分割連番')),
                ('adjusted_due_date', models.DateField(verbose_name='調整後納期')),
                ('adjusted_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='調整後数量')),
                ('adjustment_type', models.CharField(choices=[('just', 'ジャスト'), ('forward', '前倒し'), ('backward', '後ろ倒し')], default='just', max_length=20, verbose_name='調整種別')),
                ('customer_approved', models.BooleanField(default=False, verbose_name='顧客承認済み')),
                ('adjusted_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='調整日時')),
                ('note', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kubota_sakai_due_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='調整者')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kubota_sakai_due_adjustments', to='orders.orderline', verbose_name='受注明細')),
            ],
            options={
                'verbose_name': 'クボタ堺納期調整',
                'verbose_name_plural': 'クボタ堺納期調整',
                'db_table': 't_kubota_sakai_due_adjustment',
                'ordering': ['order_line_id', 'split_no', 'id'],
                'indexes': [models.Index(fields=['adjusted_due_date'], name='t_kubota_sa_adjuste_c2f9fa_idx'), models.Index(fields=['order_line', 'split_no'], name='t_kubota_sa_order_l_ebeab6_idx')],
                'unique_together': {('order_line', 'split_no')},
            },
        ),
    ]
