# Generated by Django 5.2.9 on 2026-04-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_kubotasakaidueadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubotasakaidueadjustment',
            name='remaining_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='残量'),
        ),
    ]

