# Generated by Django 5.2.9 on 2026-04-15 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0045_kubota_sakai_truck_initial_data'),
        ('orders', '0047_kubotasakaidueadjustment_remaining_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KubotaSakaiTripAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('departure_date', models.DateField(verbose_name='出発日')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='割付数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kubota_sakai_trip_assignments', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kubota_sakai_trip_assignments', to='orders.orderline', verbose_name='受注明細')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kubota_sakai_trip_assignments', to='masters.kubotasakaitruck', verbose_name='便')),
            ],
            options={
                'verbose_name': 'クボタ堺便割付',
                'verbose_name_plural': 'クボタ堺便割付',
                'db_table': 't_kubota_sakai_trip_assignment',
                'ordering': ['departure_date', 'truck_id', 'order_line_id', 'id'],
                'indexes': [models.Index(fields=['departure_date', 'truck'], name='t_kubota_sa_departu_64afc7_idx'), models.Index(fields=['order_line'], name='t_kubota_sa_order_l_00289c_idx')],
            },
        ),
    ]
