# Generated by Django 5.2.9 on 2026-04-19 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_tripassignment_due_adjustment_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_type', models.CharField(max_length=40, verbose_name='業務種別')),
                ('customer_code', models.CharField(max_length=20, verbose_name='得意先コード')),
                ('ship_to_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='納入場コード')),
                ('target_date_from', models.DateField(verbose_name='対象開始日')),
                ('target_date_to', models.DateField(verbose_name='対象終了日')),
                ('status', models.CharField(choices=[('OPEN', '進行中'), ('CLOSED', '完了')], default='OPEN', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '出荷業務',
                'verbose_name_plural': '出荷業務',
                'db_table': 't_shipping_run',
            },
        ),
        migrations.CreateModel(
            name='ShippingTrip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_type', models.CharField(max_length=40, verbose_name='業務種別')),
                ('customer_code', models.CharField(max_length=20, verbose_name='得意先コード')),
                ('ship_to_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='納入場コード')),
                ('departure_date', models.DateField(verbose_name='出発日')),
                ('trip_ref', models.CharField(max_length=80, verbose_name='便参照キー')),
                ('trip_code', models.CharField(blank=True, max_length=80, null=True, verbose_name='便コード')),
                ('departure_time_plan', models.TimeField(blank=True, null=True, verbose_name='予定出発時刻')),
                ('departure_time_actual', models.DateTimeField(blank=True, null=True, verbose_name='実出発時刻')),
                ('status', models.CharField(choices=[('PLANNED', '計画'), ('LOADING', '積込中'), ('DEPARTED', '出発済'), ('CLOSED', '完了')], default='PLANNED', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '出荷便',
                'verbose_name_plural': '出荷便',
                'db_table': 't_shipping_trip',
            },
        ),
        migrations.CreateModel(
            name='ShippingTripAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=40, verbose_name='元データ種別')),
                ('source_id', models.BigIntegerField(verbose_name='元データID')),
                ('product_code', models.CharField(max_length=50, verbose_name='品番')),
                ('ship_to_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='納入場コード')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='納期')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='割付数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '出荷便割付',
                'verbose_name_plural': '出荷便割付',
                'db_table': 't_shipping_trip_allocation',
            },
        ),
        migrations.AddField(
            model_name='shippingrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_runs', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='shippingtrip',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='orders.shippingrun', verbose_name='出荷業務'),
        ),
        migrations.AddField(
            model_name='shippingtripallocation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orders.shippingtrip', verbose_name='出荷便'),
        ),
        migrations.AddIndex(
            model_name='shippingrun',
            index=models.Index(fields=['business_type', 'customer_code', 'ship_to_code'], name='t_shipping__busines_f65c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrun',
            index=models.Index(fields=['target_date_from', 'target_date_to'], name='t_shipping__target__796ed7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingrun',
            unique_together={('business_type', 'customer_code', 'ship_to_code', 'target_date_from', 'target_date_to')},
        ),
        migrations.AddIndex(
            model_name='shippingtrip',
            index=models.Index(fields=['run'], name='t_shipping__run_id_e98138_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingtrip',
            index=models.Index(fields=['departure_date', 'status'], name='t_shipping__departu_ccbf9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingtrip',
            unique_together={('business_type', 'customer_code', 'ship_to_code', 'departure_date', 'trip_ref')},
        ),
        migrations.AddIndex(
            model_name='shippingtripallocation',
            index=models.Index(fields=['source_type', 'source_id'], name='t_shipping__source__3b9040_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingtripallocation',
            index=models.Index(fields=['product_code'], name='t_shipping__product_2a0a8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingtripallocation',
            unique_together={('trip', 'source_type', 'source_id')},
        ),
    ]
