# Generated by Django 5.2.9 on 2026-04-24 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0047_routingstep_supplier'),
        ('orders', '0053_shippingtrip_loading_by_and_departed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubotaSakaiPseudoTruckProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50, verbose_name='製品コード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '擬似便対象製品',
                'verbose_name_plural': '擬似便対象製品',
                'db_table': 'm_kubota_sakai_pseudo_truck_product',
                'ordering': ['product_code', 'truck_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='kubotasakaitripassignment',
            options={'ordering': ['departure_date', 'truck_id', 'due_adjustment_id', 'id'], 'verbose_name': 'クボタ堺便割付', 'verbose_name_plural': 'クボタ堺便割付'},
        ),
        migrations.RenameIndex(
            model_name='kubotasakaidueadjustment',
            new_name='t_kubota_sa_due_dat_79b788_idx',
            old_name='orders_kubo_due_dat_idx',
        ),
        migrations.RenameIndex(
            model_name='kubotasakaitripassignment',
            new_name='t_kubota_sa_due_adj_b3bec8_idx',
            old_name='orders_kubo_due_adj_idx',
        ),
        migrations.AlterField(
            model_name='kubotasakaidueadjustment',
            name='source_order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='注番'),
        ),
        migrations.AddField(
            model_name='kubotasakaipseudotruckproduct',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pseudo_truck_products', to='masters.kubotasakaitruck', verbose_name='擬似便'),
        ),
        migrations.AlterUniqueTogether(
            name='kubotasakaipseudotruckproduct',
            unique_together={('product_code', 'truck')},
        ),
    ]
