# Generated by Django 5.2.9 on 2026-04-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0047_routingstep_supplier'),
        ('orders', '0054_kubota_sakai_pseudo_truck_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kubotasakaipseudotruckproduct',
            options={'ordering': ['product_code', 'ship_to_code', 'truck_id'], 'verbose_name': '擬似便対象製品', 'verbose_name_plural': '擬似便対象製品'},
        ),
        migrations.AlterUniqueTogether(
            name='kubotasakaipseudotruckproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kubotasakaipseudotruckproduct',
            name='ship_to_code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='納入場コード'),
        ),
        migrations.AlterUniqueTogether(
            name='kubotasakaipseudotruckproduct',
            unique_together={('product_code', 'ship_to_code', 'truck')},
        ),
    ]
