# Generated by Django 5.2.9 on 2026-07-15 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0064_add_identification_code_and_sei_ban'),
        ('orders', '0055_pseudo_truck_product_add_ship_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstArticleNoticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='製品コード')),
                ('due_date', models.DateField(verbose_name='納期')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='数量')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='通知日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.customer', verbose_name='得意先')),
            ],
            options={
                'verbose_name': 'お久しぶり製品通知履歴',
                'verbose_name_plural': 'お久しぶり製品通知履歴',
                'db_table': 't_first_article_notice_log',
                'indexes': [models.Index(fields=['product_code', 'due_date'], name='t_first_art_product_81bbf7_idx')],
                'unique_together': {('customer', 'product_code', 'due_date', 'quantity')},
            },
        ),
    ]
