# Generated by Django 5.2.9 on 2026-07-16 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0068_migrate_product_container_data'),
        ('orders', '0056_first_article_notice_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubotasakaitripassignment',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kubota_sakai_trip_assignments', to='masters.containercapacity', verbose_name='容器'),
        ),
    ]
