# Generated by Django 5.2.9 on 2026-08-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_shippingtripnotice_notice_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shippingtripnotice',
            new_name='t_shipping__busines_f5923b_idx',
            old_name='t_shipping_t_busines_258278_idx',
        ),
        migrations.RenameIndex(
            model_name='shippingtripnotice',
            new_name='t_shipping__departu_563a1e_idx',
            old_name='t_shipping_t_departu_2371c5_idx',
        ),
        migrations.AddField(
            model_name='kubotasakaiimportconfig',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name='メール通知有効'),
        ),
    ]
