# Generated by Django 5.2.9 on 2026-08-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_kubotasakaidueadjustment_coordination_note'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingtripnotice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='shippingtripnotice',
            name='notice_type',
            field=models.CharField(choices=[('NORMAL', '出荷担当'), ('URGENT', '緊急'), ('VENDOR', '業者')], default='NORMAL', max_length=20, verbose_name='連絡種別'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingtripnotice',
            unique_together={('business_type', 'customer_code', 'departure_date', 'trip_ref', 'notice_type')},
        ),
    ]
