# Generated by Django 5.2.9 on 2026-08-21 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_kubotasakaidueallocationoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KubotaSakaiDueNotifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='メール通知有効')),
                ('notify_users', models.ManyToManyField(blank=True, related_name='kubota_sakai_due_notify', to=settings.AUTH_USER_MODEL, verbose_name='通知先ユーザー')),
            ],
            options={
                'verbose_name': 'クボタ堺納期調整通知設定',
                'db_table': 'kubota_sakai_due_notify_config',
            },
        ),
    ]
