# Generated by Django 5.2.9 on 2026-08-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_kubota_sakai_due_notify_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubotasakaiduenotifyconfig',
            name='notify_horizon_days',
            field=models.IntegerField(default=0, help_text='0=制限なし。ダイソウカレンダーでN営業日後までの変更のみ通知。', verbose_name='通知対象営業日数'),
        ),
    ]
