# Generated by Django 5.2.9 on 2026-09-01 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0082_mobiledevicehistory'),
        ('orders', '0066_add_created_by_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingtripallocation',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_trip_allocations', to='masters.containercapacity', verbose_name='容器'),
        ),
        migrations.AddField(
            model_name='shippingtripallocation',
            name='container_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='容器個数'),
        ),
        migrations.AddField(
            model_name='shippingtripallocation',
            name='source_order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='注番'),
        ),
    ]
