# Generated by Django 5.2.9 on 2026-09-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0067_add_source_order_no_container_to_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubotaSakaiDueSharedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='品番')),
                ('ship_to_code', models.CharField(blank=True, default='', max_length=40, verbose_name='納入場所コード')),
                ('due_date', models.DateField(verbose_name='日付')),
                ('coordination_note', models.CharField(blank=True, default='', max_length=200, verbose_name='共通連絡メモ')),
            ],
            options={
                'verbose_name': 'クボタ堺納期調整共通連絡',
                'verbose_name_plural': 'クボタ堺納期調整共通連絡',
                'db_table': 't_kubota_sakai_due_shared_note',
                'unique_together': {('product_code', 'ship_to_code', 'due_date')},
            },
        ),
    ]
