# Generated by Django 5.2.9 on 2026-01-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_add_line_daily_schedule_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='linebacklog',
            name='progress_qty',
            field=models.IntegerField(default=0, verbose_name='進度'),
        ),
    ]
