# Generated by Django 5.2.9 on 2026-02-06 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_add_production_plan_lock_setting_and_change_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('INVENTORY_RECALC', '在庫再計算')], max_length=50, unique=True, verbose_name='タスク名')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('scheduled_hour', models.PositiveSmallIntegerField(default=7, verbose_name='実行時（時）')),
                ('scheduled_minute', models.PositiveSmallIntegerField(default=0, verbose_name='実行時（分）')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最終実行日時')),
                ('last_run_status', models.CharField(blank=True, choices=[('SUCCESS', '成功'), ('FAILED', '失敗'), ('RUNNING', '実行中')], max_length=20, null=True, verbose_name='最終実行結果')),
                ('last_run_message', models.TextField(blank=True, default='', verbose_name='最終実行メッセージ')),
                ('last_run_duration_seconds', models.FloatField(blank=True, null=True, verbose_name='最終実行時間（秒）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'スケジュール設定',
                'verbose_name_plural': 'スケジュール設定',
                'db_table': 'production_schedule_config',
            },
        ),
    ]
