# Generated by Django 5.2.9 on 2026-02-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_alter_product_category'),
        ('production', '0006_add_planned_progress_qty'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='linedailyschedulesetting',
            new_name='line_daily__line_id_afca5c_idx',
            old_name='line_daily_line_id_plan_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='lineplan',
            unique_together={('plan_date', 'line', 'sequence_no')},
        ),
    ]
