# Generated by Django 5.2.9 on 2026-02-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_rename_line_daily_line_id_plan_date_idx_line_daily__line_id_afca5c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linebacklog',
            name='scrap_adjust_qty',
            field=models.IntegerField(default=0, verbose_name='仕損調整数'),
        ),
    ]
