# Generated by Django 5.2.9 on 2026-02-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_line_default_schedule_setting'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='linedefaultschedulesetting',
            new_name='t_line_defa_line_id_a34ed0_idx',
            old_name='t_line_def_line_id_98e996_idx',
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='scheduled_dom',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='実行日（1-31）'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='task_name',
            field=models.CharField(choices=[('INVENTORY_RECALC', '在庫再計算'), ('AUTO_PLAN', '生産計画自動生成')], max_length=50, unique=True, verbose_name='タスク名'),
        ),
    ]
