# Generated by Django 5.2.9 on 2026-02-11 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_auto_plan_to_lines(apps, schema_editor):
    ScheduleConfig = apps.get_model('production', 'ScheduleConfig')
    Line = apps.get_model('masters', 'Line')

    base_cfg = ScheduleConfig.objects.filter(task_name='AUTO_PLAN', line__isnull=True).first()
    base_values = {
        'scheduled_hour': getattr(base_cfg, 'scheduled_hour', 3) or 3,
        'scheduled_minute': getattr(base_cfg, 'scheduled_minute', 0) or 0,
        'scheduled_dom': getattr(base_cfg, 'scheduled_dom', 1),
        'is_enabled': getattr(base_cfg, 'is_enabled', True),
        'include_next_month': getattr(base_cfg, 'include_next_month', True),
        'include_second_month': getattr(base_cfg, 'include_second_month', False),
        'include_third_month': getattr(base_cfg, 'include_third_month', False),
    }

    for line in Line.objects.filter(is_active=True, line_type='PROD'):
        ScheduleConfig.objects.get_or_create(
            task_name='AUTO_PLAN',
            line_id=line.id,
            defaults=base_values,
        )

    # 旧全体設定は無効化（参照されないようにする）
    ScheduleConfig.objects.filter(task_name='AUTO_PLAN', line__isnull=True).update(is_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_alter_product_category'),
        ('production', '0011_add_auto_plan_schedule_dom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='include_next_month',
            field=models.BooleanField(default=True, verbose_name='翌月を対象'),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='include_second_month',
            field=models.BooleanField(default=False, verbose_name='翌々月を対象'),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='include_third_month',
            field=models.BooleanField(default=False, verbose_name='翌々翌月を対象'),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_configs', to='masters.line', verbose_name='対象ライン'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='task_name',
            field=models.CharField(choices=[('INVENTORY_RECALC', '在庫再計算'), ('AUTO_PLAN', '生産計画自動生成')], max_length=50, verbose_name='タスク名'),
        ),
        migrations.RunPython(copy_auto_plan_to_lines, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='scheduleconfig',
            constraint=models.UniqueConstraint(fields=('task_name', 'line'), name='uniq_schedule_task_line'),
        ),
    ]
