# Generated by Django 5.2.9 on 2026-02-13 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_scheduleconfig_include_next_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='notify_users',
            field=models.ManyToManyField(blank=True, related_name='schedule_config_notifications', to=settings.AUTH_USER_MODEL, verbose_name='通知先ユーザー'),
        ),
    ]
