# Generated by Django 5.2.9 on 2026-02-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_alter_product_category'),
        ('production', '0013_scheduleconfig_notify_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessWorkSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, default='', max_length=50, verbose_name='製品コード')),
                ('product_name', models.CharField(blank=True, default='', max_length=100, verbose_name='品名')),
                ('plan_date', models.DateField(verbose_name='計画日')),
                ('session_no', models.IntegerField(default=1, verbose_name='セッション連番')),
                ('session_type', models.CharField(choices=[('WORK', '作業'), ('PAUSE', '中断')], default='WORK', max_length=10, verbose_name='セッション種別')),
                ('start_action', models.CharField(blank=True, default='', max_length=20, verbose_name='開始アクション')),
                ('end_action', models.CharField(blank=True, default='', max_length=20, verbose_name='終了アクション')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='開始時刻')),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='終了時刻')),
                ('status', models.CharField(choices=[('OPEN', '進行中'), ('CLOSED', '終了')], default='OPEN', max_length=10, verbose_name='セッション状態')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='継続秒数')),
                ('production_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='実績数量')),
                ('issue_count', models.IntegerField(default=0, verbose_name='不整合件数')),
                ('issue_flags', models.JSONField(blank=True, default=list, verbose_name='不整合フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('end_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_work_sessions', to='production.processrealtimerecord', verbose_name='終了記録')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product', verbose_name='製品')),
                ('start_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_work_sessions', to='production.processrealtimerecord', verbose_name='開始記録')),
            ],
            options={
                'verbose_name': '工程作業セッション',
                'verbose_name_plural': '工程作業セッション',
                'db_table': 't_process_work_session',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['process', 'plan_date'], name='t_process_w_process_64d222_idx'), models.Index(fields=['process', 'product', 'status'], name='t_process_w_process_6e65f3_idx'), models.Index(fields=['session_type', 'status'], name='t_process_w_session_2968ba_idx'), models.Index(fields=['plan_date', 'status'], name='t_process_w_plan_da_1f96c7_idx'), models.Index(fields=['issue_count'], name='t_process_w_issue_c_bc2c31_idx')],
            },
        ),
    ]
