# Generated by Django 5.2.9 on 2026-02-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_scheduleconfig_relative_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='include_current_month',
            field=models.BooleanField(default=False, verbose_name='今月を対象'),
        ),
    ]
