# Generated by Django 5.2.9 on 2026-02-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_include_current_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='execution_order',
            field=models.PositiveIntegerField(default=100, verbose_name='実行順'),
        ),
    ]

