# Generated by Django 5.2.9 on 2026-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_scheduleconfig_execution_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='auto_plan_sequence_locked',
            field=models.BooleanField(default=False, verbose_name='順序運用ロック'),
        ),
    ]

