# Generated by Django 5.2.9 on 2026-02-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_scheduleconfig_auto_plan_sequence_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedemand',
            name='is_shifted',
            field=models.BooleanField(default=False, verbose_name='前倒し需要フラグ'),
        ),
    ]
