# Generated by Django 5.2.9 on 2026-02-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_linedemand_is_shifted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='task_name',
            field=models.CharField(choices=[('INVENTORY_RECALC', '在庫再計算'), ('AUTO_PLAN', '生産計画自動生成'), ('ORDER_EXPANSION', '自動受注展開')], max_length=50, verbose_name='タスク名'),
        ),
    ]
