# Generated by Django 5.2.9 on 2026-03-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_linebacklogadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='average_days_window',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='平均算出日数'),
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='safety_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='安全在庫日数'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='task_name',
            field=models.CharField(choices=[('INVENTORY_RECALC', '在庫再計算'), ('PICKUP_ONLY', '取り込みのみ'), ('INVENTORY_ONLY', '在庫計算のみ'), ('PROGRESS_ONLY', '進度計算のみ'), ('AUTO_PLAN', '生産計画自動生成'), ('ORDER_EXPANSION', '自動受注展開'), ('AUTO_SAFETY_STOCK_INTERNAL', '自動安全在庫（社内）'), ('AUTO_SAFETY_STOCK_PURCHASE', '自動安全在庫（購入品）')], max_length=50, verbose_name='タスク名'),
        ),
    ]
