# Generated by Django 5.2.9 on 2026-03-01 09:02

from django.db import migrations, models


def set_safety_stock_window_default_one(apps, schema_editor):
    ScheduleConfig = apps.get_model('production', 'ScheduleConfig')
    ScheduleConfig.objects.filter(
        task_name__in=['AUTO_SAFETY_STOCK_INTERNAL', 'AUTO_SAFETY_STOCK_PURCHASE'],
        average_days_window=30,
    ).update(average_days_window=1)


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_scheduleconfig_average_days_window_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='average_days_window',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='平均算出日数'),
        ),
        migrations.RunPython(set_safety_stock_window_default_one, migrations.RunPython.noop),
    ]
