# Generated by Django 5.2.9 on 2026-03-01 09:10

from django.db import migrations, models


def set_safety_stock_defaults_to_60_and_1(apps, schema_editor):
    ScheduleConfig = apps.get_model('production', 'ScheduleConfig')
    ScheduleConfig.objects.filter(
        task_name__in=['AUTO_SAFETY_STOCK_INTERNAL', 'AUTO_SAFETY_STOCK_PURCHASE'],
        average_days_window__in=[1, 30],
        safety_days=7,
    ).update(average_days_window=60, safety_days=1)


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_alter_scheduleconfig_average_days_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='average_days_window',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='平均算出日数'),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='safety_days',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='安全在庫日数'),
        ),
        migrations.RunPython(set_safety_stock_defaults_to_60_and_1, migrations.RunPython.noop),
    ]
