# Generated by Django 5.2.9 on 2026-03-01 09:38

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


def round_min_stock_qty_to_int(apps, schema_editor):
    StockAllocation = apps.get_model('production', 'StockAllocation')
    batch = []
    for row in StockAllocation.objects.all().only('id', 'min_stock_qty').iterator():
        value = row.min_stock_qty
        rounded = int(Decimal(str(value or 0)).quantize(Decimal('1'), rounding=ROUND_HALF_UP))
        if rounded < 0:
            rounded = 0
        row.min_stock_qty = rounded
        batch.append(row)
    if batch:
        StockAllocation.objects.bulk_update(batch, ['min_stock_qty'])


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_alter_scheduleconfig_average_days_window_and_more'),
    ]

    operations = [
        migrations.RunPython(round_min_stock_qty_to_int, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stockallocation',
            name='min_stock_qty',
            field=models.PositiveIntegerField(help_text='この数量を下回るとアラート', verbose_name='最小在庫数'),
        ),
    ]
