# Generated by Django 5.2.9 on 2026-03-11 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0035_equipment_process'),
        ('production', '0029_alter_scheduleconfig_task_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingMigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migrated_at', models.DateTimeField(auto_now_add=True, verbose_name='移行日時')),
                ('migrated_qty', models.IntegerField(verbose_name='移行数量')),
                ('migration_date', models.DateField(verbose_name='移行基準日')),
                ('migrated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_migration_logs', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
                ('new_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_to_logs', to='masters.line', verbose_name='新ライン')),
                ('new_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_to_logs', to='masters.process', verbose_name='新工程')),
                ('old_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_from_logs', to='masters.line', verbose_name='旧ライン')),
                ('old_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_from_logs', to='masters.process', verbose_name='旧工程')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_migration_logs', to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': 'ルーティング変更在庫移行ログ',
                'verbose_name_plural': 'ルーティング変更在庫移行ログ',
                'db_table': 'production_routing_migration_log',
                'indexes': [models.Index(fields=['product', 'migrated_at'], name='production__product_44915d_idx'), models.Index(fields=['old_line', 'migrated_at'], name='production__old_lin_708206_idx'), models.Index(fields=['new_line', 'migrated_at'], name='production__new_lin_033b68_idx')],
            },
        ),
    ]
