# Generated by Django 5.2.9 on 2026-03-13 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0035_equipment_process'),
        ('production', '0031_productionrecordinquirysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserPattern',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pattern_no', models.CharField(max_length=50, unique=True, verbose_name='パターン番号')),
                ('process_time_min', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='加工時間(分/回)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laser_patterns', to='masters.equipment', verbose_name='使用設備')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laser_patterns_as_material', to='masters.product', verbose_name='使用材料')),
            ],
            options={
                'verbose_name': 'レーザパターン',
                'verbose_name_plural': 'レーザパターン',
                'db_table': 't_laser_pattern',
                'ordering': ['pattern_no'],
            },
        ),
        migrations.CreateModel(
            name='LaserPatternFinishedProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('units_per_shot', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='完成品取り数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laser_pattern_finished_items', to='masters.product', verbose_name='完成品')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_items', to='production.laserpattern', verbose_name='レーザパターン')),
            ],
            options={
                'verbose_name': 'レーザパターン完成品',
                'verbose_name_plural': 'レーザパターン完成品',
                'db_table': 't_laser_pattern_finished',
                'ordering': ['id'],
                'unique_together': {('pattern', 'finished_product')},
            },
        ),
        migrations.CreateModel(
            name='LaserPatternComponent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('take_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='取り数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laser_pattern_component_items', to='masters.product', verbose_name='構成部品')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_items', to='production.laserpattern', verbose_name='レーザパターン')),
            ],
            options={
                'verbose_name': 'レーザパターン構成部品',
                'verbose_name_plural': 'レーザパターン構成部品',
                'db_table': 't_laser_pattern_component',
                'ordering': ['id'],
                'unique_together': {('pattern', 'component_product')},
            },
        ),
    ]
