# Generated by Django 5.2.9 on 2026-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0032_laser_pattern_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecordinquirysetting',
            name='tab_key',
            field=models.CharField(
                choices=[
                    ('tank', 'タンク'),
                    ('floor', 'フロア'),
                    ('blade', 'ブレード'),
                    ('laser', 'レーザ'),
                    ('brake', 'ブレーキ'),
                    ('spot', 'スポット'),
                ],
                max_length=20,
                unique=True,
                verbose_name='対象タブ',
            ),
        ),
    ]
