# Generated by Django 5.2 on 2026-03-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0035_equipment_process'),
        ('production', '0033_alter_productionrecordinquirysetting_tab_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserActual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField(verbose_name='作業日')),
                ('shot_count', models.PositiveIntegerField(verbose_name='回数')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='備考')),
                ('pattern_no', models.CharField(max_length=50, verbose_name='パターン番号')),
                ('equipment_code', models.CharField(blank=True, default='', max_length=50, verbose_name='設備コード')),
                ('equipment_name', models.CharField(blank=True, default='', max_length=100, verbose_name='設備名')),
                ('material_code', models.CharField(blank=True, default='', max_length=50, verbose_name='使用材料コード')),
                ('material_name', models.CharField(blank=True, default='', max_length=100, verbose_name='使用材料名')),
                ('process_time_per_shot', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='加工時間(分/回)')),
                ('total_process_time', models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='総加工時間(分)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_laser_actuals', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laser_actuals', to='masters.equipment', verbose_name='設備')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laser_actual_materials', to='masters.product', verbose_name='使用材料')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laser_actuals', to='production.laserpattern', verbose_name='パターン')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_laser_actuals', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'レーザー実績',
                'verbose_name_plural': 'レーザー実績',
                'db_table': 't_laser_actual',
                'ordering': ['-work_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LaserActualDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('detail_type', models.CharField(choices=[('COMPONENT', '構成部品'), ('FINISHED', '完成品')], max_length=20, verbose_name='明細種別')),
                ('product_code', models.CharField(blank=True, default='', max_length=50, verbose_name='製品コード')),
                ('product_name', models.CharField(blank=True, default='', max_length=100, verbose_name='製品名')),
                ('units_per_shot', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='1回あたり数量')),
                ('total_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='換算数量')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='production.laseractual', verbose_name='レーザー実績')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laser_actual_details', to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': 'レーザー実績明細',
                'verbose_name_plural': 'レーザー実績明細',
                'db_table': 't_laser_actual_detail',
                'ordering': ['detail_type', 'display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='laseractual',
            index=models.Index(fields=['work_date'], name='t_laser_act_work_da_98a8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='laseractual',
            index=models.Index(fields=['equipment'], name='t_laser_act_equipme_1190ad_idx'),
        ),
        migrations.AddIndex(
            model_name='laseractual',
            index=models.Index(fields=['pattern_no'], name='t_laser_act_pattern_787ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='laseractualdetail',
            index=models.Index(fields=['actual', 'detail_type'], name='t_laser_act_actual__668646_idx'),
        ),
    ]
