# Generated by Django 5.2.9 on 2026-03-15 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0035_equipment_process'),
        ('production', '0038_replace_laser_equipment_daily_record_with_shift_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrakeLineRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_date', models.DateField(verbose_name='計画日')),
                ('product_code', models.CharField(blank=True, default='', max_length=50, verbose_name='品番')),
                ('operator', models.CharField(blank=True, default='', max_length=100, verbose_name='作業者')),
                ('operator_action', models.CharField(choices=[('START', '開始'), ('END', '終了'), ('PAUSE', '中断'), ('TEMP_END', '一時終了'), ('RESUME', '再開')], max_length=20, verbose_name='アクション')),
                ('operator_action_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='理由')),
                ('qty', models.IntegerField(default=0, verbose_name='加工数（END時）')),
                ('sequence_no', models.IntegerField(default=1, verbose_name='シーケンスNo')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.equipment', verbose_name='設備')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': 'ブレーキライン作業記録',
                'verbose_name_plural': 'ブレーキライン作業記録',
                'db_table': 'brake_line_record',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['plan_date', 'process', 'product'], name='blr_date_proc_prod_idx')],
            },
        ),
    ]
