# Generated by Django 5.2.9 on 2026-03-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0041_laserpattern_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='processworksession',
            name='defect_qty',
            field=models.IntegerField(default=0, verbose_name='仕損数量'),
        ),
    ]
