# Generated by Django 5.2.9 on 2026-04-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0044_alter_productionrecordinquirysetting_tab_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedemand',
            name='firm_is_shifted',
            field=models.BooleanField(default=False, verbose_name='確定前倒し需要フラグ'),
        ),
        migrations.AddField(
            model_name='linedemand',
            name='firm_order_numbers',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='展開元受注番号(確定)'),
        ),
        migrations.AddField(
            model_name='linedemand',
            name='forecast_is_shifted',
            field=models.BooleanField(default=False, verbose_name='内示前倒し需要フラグ'),
        ),
        migrations.AddField(
            model_name='linedemand',
            name='forecast_order_numbers',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='展開元受注番号(内示)'),
        ),
    ]
