# Generated by Django 5.2.9 on 2026-04-09 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0042_remove_routing_unique_together'),
        ('production', '0045_linedemand_firm_is_shifted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GanttDisplayProductMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('display_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gantt_display_target_maps', to='masters.product', verbose_name='表示品')),
                ('final_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gantt_display_final_product_maps', to='masters.product', verbose_name='ライン最終品')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gantt_display_product_maps', to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gantt_display_product_maps', to='masters.process', verbose_name='工程')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantt_display_product_maps', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'ガント表示品マップ',
                'verbose_name_plural': 'ガント表示品マップ',
                'db_table': 't_gantt_display_product_map',
                'indexes': [models.Index(fields=['line', 'final_product'], name='t_gantt_dis_line_id_71f98d_idx'), models.Index(fields=['process'], name='t_gantt_dis_process_9f7b5c_idx'), models.Index(fields=['display_product'], name='t_gantt_dis_display_96e402_idx')],
                'unique_together': {('line', 'final_product', 'process', 'display_product')},
            },
        ),
    ]
