# Generated by Django 5.2.9 on 2026-04-12 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0042_remove_routing_unique_together'),
        ('production', '0046_ganttdisplayproductmap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='task_name',
            field=models.CharField(choices=[('INVENTORY_RECALC', '在庫再計算'), ('PICKUP_ONLY', '取り込みのみ'), ('INVENTORY_ONLY', '在庫計算のみ'), ('PROGRESS_ONLY', '進度計算のみ'), ('AUTO_PLAN', '生産計画自動生成'), ('ORDER_EXPANSION', '自動受注展開'), ('AUTO_SAFETY_STOCK_INTERNAL', '自動安全在庫（社内）'), ('AUTO_SAFETY_STOCK_PURCHASE', '自動安全在庫（購入品）'), ('AUTO_PURCHASE_ORDER_CHECK', '発注タイミング日次チェック'), ('PURCHASE_ACTUAL_RECONCILE_CHECK', '納入実績整合チェック')], max_length=50, verbose_name='タスク名'),
        ),
        migrations.CreateModel(
            name='PurchaseActualReconcileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CHECK', '比較'), ('FIX', '修正')], default='CHECK', max_length=10, verbose_name='実行モード')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失敗')], default='SUCCESS', max_length=20, verbose_name='実行結果')),
                ('compared_count', models.IntegerField(default=0, verbose_name='比較件数')),
                ('diff_count', models.IntegerField(default=0, verbose_name='差分件数')),
                ('fixed_count', models.IntegerField(default=0, verbose_name='修正件数')),
                ('message', models.TextField(blank=True, default='', verbose_name='実行メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_actual_reconcile_reports', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
                ('task_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_actual_reconcile_reports', to='production.scheduleconfig', verbose_name='実行設定')),
            ],
            options={
                'verbose_name': '納入実績整合レポート',
                'verbose_name_plural': '納入実績整合レポート',
                'db_table': 'production_purchase_actual_reconcile_report',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseActualReconcileReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(verbose_name='納入日')),
                ('expected_qty', models.IntegerField(default=0, verbose_name='期待実績')),
                ('backlog_qty', models.IntegerField(default=0, verbose_name='Backlog実績')),
                ('diff_qty', models.IntegerField(default=0, verbose_name='差分')),
                ('fixed', models.BooleanField(default=False, verbose_name='修正済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_actual_reconcile_details', to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_actual_reconcile_details', to='masters.process', verbose_name='工程')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_actual_reconcile_details', to='masters.product', verbose_name='製品')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='production.purchaseactualreconcilereport', verbose_name='レポート')),
            ],
            options={
                'verbose_name': '納入実績整合レポート明細',
                'verbose_name_plural': '納入実績整合レポート明細',
                'db_table': 'production_purchase_actual_reconcile_report_detail',
                'indexes': [models.Index(fields=['report', 'plan_date'], name='production__report__0549a4_idx'), models.Index(fields=['line', 'process', 'product', 'plan_date'], name='production__line_id_888d2b_idx')],
            },
        ),
    ]
