# Generated by Django 5.2.9 on 2026-04-17 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0045_kubota_sakai_truck_initial_data'),
        ('production', '0048_alter_scheduleconfig_task_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecordConfirmation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField(verbose_name='対象日')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='確認日時')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_confirmations', to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_confirmations', to='masters.process', verbose_name='工程')),
            ],
            options={
                'verbose_name': '生産実績確認',
                'verbose_name_plural': '生産実績確認',
                'db_table': 't_production_record_confirmation',
                'indexes': [models.Index(fields=['work_date', 'line'], name='t_productio_work_da_906d02_idx')],
                'unique_together': {('work_date', 'line', 'process')},
            },
        ),
    ]
