# Generated by Django 5.2.9 on 2026-04-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0046_add_alias_name_to_kubota_sakai_truck'),
        ('production', '0049_record_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessWorkSessionEquipment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRIMARY', '主設備'), ('SUB', '副設備')], default='SUB', max_length=10, verbose_name='設備区分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.equipment', verbose_name='設備')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_equipments', to='production.processworksession', verbose_name='作業セッション')),
            ],
            options={
                'verbose_name': '工程作業セッション設備',
                'verbose_name_plural': '工程作業セッション設備',
                'db_table': 't_process_work_session_equipment',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['session'], name='pws_eq_session_idx'), models.Index(fields=['equipment'], name='pws_eq_equipment_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'equipment'), name='uniq_pws_equipment')],
            },
        ),
    ]
