# Generated by Django 5.2.9 on 2026-05-06 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0048_alter_product_category_add_outsourced'),
        ('production', '0051_schedule_config_plan_to_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraCountEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('camera_event_id', models.CharField(max_length=64, unique=True, verbose_name='カメライベントID')),
                ('count', models.IntegerField(default=1, verbose_name='加算数')),
                ('event_at_client', models.DateTimeField(verbose_name='端末検知時刻')),
                ('event_at_server', models.DateTimeField(auto_now_add=True, verbose_name='サーバ受信時刻')),
                ('business_date', models.DateField(verbose_name='業務日')),
                ('device_id', models.CharField(blank=True, default='', max_length=128, verbose_name='端末ID')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='信頼度')),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('replayed', 'replayed')], default='accepted', max_length=16, verbose_name='状態')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': 'カメラカウントイベント',
                'verbose_name_plural': 'カメラカウントイベント',
                'db_table': 't_camera_count_event',
                'indexes': [models.Index(fields=['business_date', 'line', 'process', 'product'], name='t_camera_co_busines_1a21a7_idx'), models.Index(fields=['event_at_server'], name='t_camera_co_event_a_4ecc36_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionResultDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_date', models.DateField(verbose_name='業務日')),
                ('actual_count', models.IntegerField(default=0, verbose_name='実績数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '日次生産実績',
                'verbose_name_plural': '日次生産実績',
                'db_table': 't_production_result_daily',
                'indexes': [models.Index(fields=['business_date', 'line', 'process', 'product'], name='t_productio_busines_bb9f30_idx')],
                'unique_together': {('business_date', 'line', 'process', 'product')},
            },
        ),
    ]
