# Generated by Django 5.2.9 on 2026-05-15 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0053_cameracountevent_shape_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brakelinerecord',
            name='operator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brake_line_records', to=settings.AUTH_USER_MODEL, verbose_name='作業者ユーザー'),
        ),
    ]
