# Generated by Django 5.2.9 on 2026-05-23 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0054_productcodemapping'),
        ('production', '0054_brakelinerecord_operator_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineProductDisplayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30, verbose_name='品番コード')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('context', models.CharField(default='default', max_length=30, verbose_name='コンテキスト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_display_orders', to='masters.line', verbose_name='ライン')),
            ],
            options={
                'verbose_name': 'ライン別製品表示順',
                'verbose_name_plural': 'ライン別製品表示順',
                'db_table': 't_line_product_display_order',
                'ordering': ['line', 'display_order'],
                'indexes': [models.Index(fields=['line', 'display_order'], name='t_line_prod_line_id_b0d8aa_idx')],
                'unique_together': {('line', 'product_code', 'context')},
            },
        ),
    ]
