# Generated by Django 5.2.9 on 2026-05-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0055_lineproductdisplayorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineproductdisplayorder',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='行背景色'),
        ),
        migrations.AddField(
            model_name='lineproductdisplayorder',
            name='plan_bg_color',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ロット追加ボタン背景色'),
        ),
        migrations.AddField(
            model_name='lineproductdisplayorder',
            name='plan_text_color',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ロット追加ボタン文字色'),
        ),
        migrations.AddField(
            model_name='lineproductdisplayorder',
            name='text_color',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='行文字色'),
        ),
    ]
