# Generated by Django 5.2.9 on 2026-05-25 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0058_calendar_created_by_updated_by'),
        ('production', '0056_lineproductdisplayorder_colors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPlanAggregateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_weekday', models.PositiveSmallIntegerField(default=2, verbose_name='まとめ生産日(0=日..6=土)')),
                ('aggregate_days', models.PositiveSmallIntegerField(default=7, verbose_name='まとめ対象期間(日数)')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_plan_aggregate_settings', to='masters.line')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_plan_aggregate_settings', to='masters.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_plan_aggregate_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '自動計画まとめ生産設定',
                'verbose_name_plural': '自動計画まとめ生産設定',
                'db_table': 't_auto_plan_aggregate_setting',
                'indexes': [models.Index(fields=['line', 'is_active'], name='t_auto_plan_line_id_3d1a68_idx'), models.Index(fields=['product', 'is_active'], name='t_auto_plan_product_e1603f_idx')],
                'unique_together': {('line', 'product')},
            },
        ),
    ]
