# Generated by Django 5.2.9 on 2026-05-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0058_calendar_created_by_updated_by'),
        ('production', '0057_autoplanaggregatesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeviationLineConfig',
            fields=[
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='masters.line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_plan_deviation_line_config',
            },
        ),
    ]
