# Generated by Django 5.2.9 on 2026-06-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0059_stocktake_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stocktakerecord',
            name='uniq_stocktake_record_key',
        ),
        migrations.RenameIndex(
            model_name='stocktakerecord',
            new_name='production__stockta_a2c2d0_idx',
            old_name='production_s_stockta_a248cb_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktakerecord',
            new_name='production__product_e0839f_idx',
            old_name='production_s_product_08a4b0_idx',
        ),
    ]
