# Generated by Django 5.2.9 on 2026-06-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0060_remove_stocktake_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakerecord',
            name='recorder_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='記入者名'),
        ),
        migrations.CreateModel(
            name='StocktakeRecorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocktake_date', models.DateField(verbose_name='棚卸日')),
                ('name', models.CharField(max_length=50, verbose_name='記入者名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'production_stocktake_recorder',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('stocktake_date', 'name'), name='uniq_stocktake_recorder')],
            },
        ),
    ]
