# Generated by Django 5.2.9 on 2026-06-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0061_add_stocktake_recorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktakerecord',
            name='diff_qty',
        ),
    ]
