# Generated by Django 5.2.9 on 2026-06-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0062_remove_stocktake_diff_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktakeLayoutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True, verbose_name='設定名')),
                ('cols', models.IntegerField(default=8, verbose_name='列数')),
                ('row_count', models.IntegerField(default=6, verbose_name='行数')),
                ('cells', models.JSONField(default=dict, verbose_name='セル配置')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_stocktake_layout_config',
            },
        ),
    ]
