# Generated by Django 5.2.9 on 2026-06-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0063_add_stocktake_layout_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktakeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='エリア名')),
                ('locations', models.JSONField(default=list, verbose_name='所属置き場リスト')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '棚卸エリア',
                'verbose_name_plural': '棚卸エリア',
                'db_table': 'production_stocktake_area',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
