# Generated by Django 5.2.9 on 2026-06-29 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0064_add_identification_code_and_sei_ban'),
        ('production', '0068_record_inquiry_tab_name_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplanlinesetting',
            name='tab_key',
            field=models.CharField(max_length=30, unique=True, verbose_name='タブキー'),
        ),
        migrations.CreateModel(
            name='SingleProcFinishedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField()),
                ('sequence_no', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.line')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
            ],
            options={
                'db_table': 't_singleproc_finished_entry',
                'indexes': [models.Index(fields=['line', 'process', 'plan_date'], name='t_singlepro_line_id_c2d2e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('line', 'process', 'plan_date', 'sequence_no'), name='uq_singleproc_finished_entry')],
            },
        ),
    ]
