# Generated by Django 5.2.9 on 2026-07-05 13:45

import django.db.models.deletion
import production.models_morning_meeting
from django.db import migrations, models


def migrate_single_targets_to_multi(apps, schema_editor):
    MorningMeeting = apps.get_model('production', 'MorningMeeting')
    for meeting in MorningMeeting.objects.all():
        if meeting.department_id:
            meeting.target_departments.add(meeting.department_id)
        if meeting.line_id:
            meeting.target_lines.add(meeting.line_id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_add_purchase_menu_permission_resources'),
        ('masters', '0064_add_identification_code_and_sei_ban'),
        ('production', '0072_morning_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningMeetingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=production.models_morning_meeting.morning_meeting_attachment_upload_to, verbose_name='添付ファイル')),
                ('original_name', models.CharField(max_length=255, verbose_name='元ファイル名')),
                ('content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Content-Type')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='ファイルサイズ')),
                ('attachment_type', models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', '画像'), ('EXCEL', 'Excel')], max_length=20, verbose_name='添付種別')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '朝礼添付資料',
                'verbose_name_plural': '朝礼添付資料',
                'db_table': 't_morning_meeting_attachment',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='morningmeeting',
            name='pm_mm_dept_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='morningmeeting',
            name='pm_mm_line_date_idx',
        ),
        migrations.AddField(
            model_name='morningmeeting',
            name='target_departments',
            field=models.ManyToManyField(blank=True, related_name='target_morning_meetings', to='accounts.department', verbose_name='対象部署'),
        ),
        migrations.AddField(
            model_name='morningmeeting',
            name='target_lines',
            field=models.ManyToManyField(blank=True, related_name='target_morning_meetings', to='masters.line', verbose_name='対象ライン'),
        ),
        migrations.AddField(
            model_name='morningmeetingattachment',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='production.morningmeeting', verbose_name='朝礼'),
        ),
        migrations.RunPython(migrate_single_targets_to_multi, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='morningmeeting',
            name='department',
        ),
        migrations.RemoveField(
            model_name='morningmeeting',
            name='line',
        ),
        migrations.AddIndex(
            model_name='morningmeetingattachment',
            index=models.Index(fields=['meeting', 'display_order'], name='pm_mma_meet_disp_idx'),
        ),
    ]
