# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0075_morningmeeting_meeting_date_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='task_name',
            field=models.CharField(
                choices=[
                    ('INVENTORY_RECALC', '在庫再計算'),
                    ('PICKUP_ONLY', '取り込みのみ'),
                    ('INVENTORY_ONLY', '在庫計算のみ'),
                    ('PROGRESS_ONLY', '進度計算のみ'),
                    ('AUTO_PLAN', '生産計画自動生成'),
                    ('ORDER_EXPANSION', '自動受注展開'),
                    ('AUTO_SAFETY_STOCK_INTERNAL', '自動安全在庫（社内）'),
                    ('AUTO_SAFETY_STOCK_PURCHASE', '自動安全在庫（購入品）'),
                    ('AUTO_PURCHASE_ORDER_CHECK', '発注タイミング日次チェック'),
                    ('PURCHASE_ACTUAL_RECONCILE_CHECK', '納入実績整合チェック'),
                    ('PRODUCTION_ACTUAL_RECONCILE_CHECK', '生産実績整合チェック'),
                    ('PLAN_TO_ACTUAL_COPY', '計画実績自動セット'),
                    ('CONTAINER_IMPORT_TMP_CLEANUP', '荷姿設定Excel取込 一時ファイル削除'),
                ],
                max_length=50,
                verbose_name='タスク名',
            ),
        ),
    ]
