# Generated by Django 5.2.9 on 2026-07-20 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0070_kubota_sakai_truck_physical_truck_code'),
        ('production', '0076_scheduleconfig_task_name_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('INVENTORY_RECALC', '在庫再計算'), ('PICKUP_ONLY', '取り込みのみ'), ('INVENTORY_ONLY', '在庫計算のみ'), ('PROGRESS_ONLY', '進度計算のみ'), ('AUTO_PLAN', '生産計画自動生成'), ('ORDER_EXPANSION', '自動受注展開'), ('AUTO_SAFETY_STOCK_INTERNAL', '自動安全在庫（社内）'), ('AUTO_SAFETY_STOCK_PURCHASE', '自動安全在庫（購入品）'), ('AUTO_PURCHASE_ORDER_CHECK', '発注タイミング日次チェック'), ('PURCHASE_ACTUAL_RECONCILE_CHECK', '納入実績整合チェック'), ('PRODUCTION_ACTUAL_RECONCILE_CHECK', '生産実績整合チェック'), ('PLAN_TO_ACTUAL_COPY', '計画実績自動セット'), ('CONTAINER_IMPORT_TMP_CLEANUP', '荷姿設定Excel取込 一時ファイル削除')], max_length=50, verbose_name='タスク名')),
                ('started_at', models.DateTimeField(verbose_name='実行開始日時')),
                ('finished_at', models.DateTimeField(verbose_name='実行終了日時')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失敗'), ('RUNNING', '実行中')], max_length=20, verbose_name='結果')),
                ('message', models.TextField(blank=True, default='', verbose_name='実行メッセージ')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='実行時間（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='production.scheduleconfig', verbose_name='タスク設定')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.line', verbose_name='対象ライン')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.process', verbose_name='対象工程')),
            ],
            options={
                'verbose_name': 'タスク実行履歴',
                'verbose_name_plural': 'タスク実行履歴',
                'db_table': 'production_schedule_run_log',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['config', '-started_at'], name='production__config__1e796c_idx')],
            },
        ),
    ]
