# Generated by Django 5.2.9 on 2026-07-25 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0072_routingchangehistory'),
        ('production', '0077_schedulerunlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualCycleTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calc_from_date', models.DateField(verbose_name='計算期間FROM')),
                ('calc_to_date', models.DateField(verbose_name='計算期間TO')),
                ('total_qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='出来高合計')),
                ('total_seconds', models.IntegerField(verbose_name='有効稼働時間合計(秒)')),
                ('cycle_time_sec', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平均サイクル時間(秒/個)')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='計算日時')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '実績サイクル時間',
                'verbose_name_plural': '実績サイクル時間',
                'db_table': 't_actual_cycle_time',
                'unique_together': {('product', 'process', 'line', 'calc_from_date', 'calc_to_date')},
            },
        ),
        migrations.CreateModel(
            name='FinishedProductCycleTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cycle_time_sec', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='サイクル時間(秒/個)')),
                ('calc_from_date', models.DateField(verbose_name='計算期間FROM')),
                ('calc_to_date', models.DateField(verbose_name='計算期間TO')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='計算日時')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_cycle_times', to='masters.product', verbose_name='完成品')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
            ],
            options={
                'verbose_name': '完成品サイクル時間',
                'verbose_name_plural': '完成品サイクル時間',
                'db_table': 't_finished_product_cycle_time',
                'unique_together': {('finished_product', 'process', 'line', 'calc_from_date', 'calc_to_date')},
            },
        ),
    ]
