# Generated by Django 5.2.9 on 2026-07-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0078_actualcycletime_finishedproductcycletime'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualcycletime',
            name='adjusted_cycle_time_sec',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='実績CT ÷ (稼働率/100)', max_digits=10, null=True, verbose_name='補正サイクル時間(秒/個)'),
        ),
        migrations.AddField(
            model_name='actualcycletime',
            name='operating_rate_applied',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='適用稼働率(%)'),
        ),
    ]
