# Generated by Django 5.2.9 on 2026-07-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0079_add_adjusted_ct_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproductcycletime',
            name='use_adjusted',
            field=models.BooleanField(default=False, verbose_name='補正CT使用'),
        ),
    ]
