# Generated by Django 5.2.9 on 2026-08-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0082_stocktakerecord_counter_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktakeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocktake_date', models.DateField(verbose_name='棚卸日')),
                ('name', models.CharField(max_length=50, verbose_name='カウンター名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'production_stocktake_counter',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='stocktakecounter',
            constraint=models.UniqueConstraint(fields=('stocktake_date', 'name'), name='uniq_stocktake_counter'),
        ),
    ]
