# Generated by Django 5.2.9 on 2026-08-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0083_stocktakecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brakelinerecord',
            name='operator_action',
            field=models.CharField(choices=[('START', '開始'), ('END', '終了'), ('PAUSE', '中断'), ('TEMP_END', '強制終了'), ('RESUME', '再開')], max_length=20, verbose_name='アクション'),
        ),
        migrations.AlterField(
            model_name='laseractual',
            name='operator_action',
            field=models.CharField(choices=[('START', '開始'), ('END', '終了'), ('PAUSE', '中断'), ('TEMP_END', '強制終了'), ('RESUME', '再開')], default='END', max_length=20, verbose_name='作業時刻'),
        ),
    ]
