# Generated by Django 5.2.9 on 2026-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0084_alter_brakelinerecord_operator_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linebacklog',
            name='order_qty_actual',
            field=models.IntegerField(default=0),
        ),
    ]
