# Generated by Django 5.2.9 on 2026-08-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0088_daily_process_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakerecord',
            name='area_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='入力エリア'),
        ),
    ]
