# Generated by Django 5.2.9 on 2026-08-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0089_stocktake_record_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakerecord',
            name='system_progress_qty',
            field=models.IntegerField(default=0, verbose_name='机上進度'),
        ),
    ]
