# Generated by Django 5.2.9 on 2026-08-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0082_mobiledevicehistory'),
        ('production', '0090_stocktake_record_system_progress_qty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='linedemand',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='linedemand',
            name='ship_to_code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='納入先コード'),
        ),
        migrations.AlterUniqueTogether(
            name='linedemand',
            unique_together={('line', 'product_code', 'plan_date', 'process', 'ship_to_code')},
        ),
        migrations.AddIndex(
            model_name='linedemand',
            index=models.Index(fields=['ship_to_code'], name='t_line_dema_ship_to_0aba2d_idx'),
        ),
    ]
