# Generated by Django 5.2.9 on 2026-09-02 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0094_laser_weekly_pattern_manual_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserWeeklyPatternInitialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='週開始日')),
                ('initial_progress', models.IntegerField(default=0, verbose_name='期首進度')),
                ('is_locked', models.BooleanField(default=False, verbose_name='ロック')),
                ('laser_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_initial_progress', to='production.laserpattern')),
            ],
            options={
                'db_table': 't_laser_weekly_pattern_initial_progress',
                'constraints': [models.UniqueConstraint(fields=('laser_pattern', 'week_start_date'), name='laser_weekly_initial_progress_unique')],
            },
        ),
    ]
