# Generated by Django 5.2.9 on 2026-09-02 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0095_laser_weekly_initial_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserProcessingFreqPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_code', models.CharField(max_length=30, unique=True, verbose_name='パターンコード')),
                ('pattern_name', models.CharField(max_length=100, verbose_name='パターン名')),
                ('frequency_type', models.CharField(choices=[('DAILY', '毎日'), ('WEEKLY', '毎週曜日'), ('EVERY_N_DAYS', 'N営業日ごと')], default='DAILY', max_length=20, verbose_name='加工頻度種別')),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金')], null=True, verbose_name='加工曜日(0=月〜4=金)')),
                ('interval_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='間隔営業日数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='備考')),
            ],
            options={
                'verbose_name': 'レーザ加工頻度パターン',
                'verbose_name_plural': 'レーザ加工頻度パターン',
                'db_table': 't_laser_processing_freq_pattern',
                'ordering': ['pattern_code'],
            },
        ),
        migrations.AddField(
            model_name='laserpattern',
            name='processing_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='加工頻度適用開始日'),
        ),
        migrations.AddField(
            model_name='laserpattern',
            name='processing_freq_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laser_patterns', to='production.laserprocessingfreqpattern', verbose_name='加工頻度パターン'),
        ),
    ]
