# Generated by Django 5.2.9 on 2026-09-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0083_supplier_contact_person_phone_number'),
        ('production', '0099_laser_weekly_material_initial_progress_is_locked'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='laserweeklymaterialorderprogress',
            name='laser_weekly_material_order_progress_unique',
        ),
        migrations.AddField(
            model_name='laserweeklymaterialorderprogress',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='手動追加'),
        ),
        migrations.AddField(
            model_name='laserweeklymaterialorderprogress',
            name='order_sheets',
            field=models.PositiveIntegerField(default=0, verbose_name='端数枚数'),
        ),
        migrations.AlterField(
            model_name='laserweeklymaterialorderprogress',
            name='lot_multiple',
            field=models.PositiveIntegerField(default=0, verbose_name='発注倍数'),
        ),
        migrations.AlterField(
            model_name='laserweeklymaterialorderprogress',
            name='order_lots',
            field=models.PositiveIntegerField(default=0, verbose_name='発注ロット数'),
        ),
        migrations.AlterField(
            model_name='laserweeklymaterialorderprogress',
            name='plan_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='計画開始日'),
        ),
        migrations.AlterField(
            model_name='laserweeklymaterialorderprogress',
            name='required_date',
            field=models.DateField(blank=True, null=True, verbose_name='必要日'),
        ),
        migrations.AlterField(
            model_name='laserweeklymaterialorderprogress',
            name='required_lots',
            field=models.PositiveIntegerField(default=0, verbose_name='必要ロット数'),
        ),
        migrations.AlterField(
            model_name='laserweeklymaterialorderprogress',
            name='required_sheets',
            field=models.PositiveIntegerField(default=0, verbose_name='必要枚数'),
        ),
        migrations.AddConstraint(
            model_name='laserweeklymaterialorderprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_manual', False)), fields=('plan_start_date', 'material', 'required_date', 'supplier'), name='laser_weekly_material_order_progress_unique'),
        ),
        migrations.AddConstraint(
            model_name='laserweeklymaterialorderprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_manual', True)), fields=('material', 'delivery_date', 'supplier'), name='laser_weekly_material_order_manual_unique'),
        ),
    ]
