# Generated by Django 5.2.9 on 2026-09-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0100_laser_material_order_manual_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laserweeklypatterninitialprogress',
            name='initial_progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='期首進度'),
        ),
    ]
