# Generated by Django 5.2.9 on 2026-09-05 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0101_initial_progress_to_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserWeeklyPatternDailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_date', models.DateField(verbose_name='日付')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='進度')),
                ('laser_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_daily_progress', to='production.laserpattern')),
            ],
            options={
                'db_table': 't_laser_weekly_pattern_daily_progress',
                'constraints': [models.UniqueConstraint(fields=('laser_pattern', 'progress_date'), name='laser_weekly_daily_progress_unique')],
            },
        ),
    ]
