# Generated by Django 5.2.9 on 2026-09-10 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0102_add_laser_weekly_pattern_daily_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserMaterialOrderEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(choices=[('SATO', '佐藤商事'), ('MEISEI', '名成鋼機')], max_length=10, unique=True, verbose_name='仕入先')),
                ('body', models.TextField(blank=True, default='', verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cc_users', models.ManyToManyField(blank=True, related_name='laser_material_order_email_configs', to=settings.AUTH_USER_MODEL, verbose_name='CCユーザー')),
            ],
            options={
                'db_table': 't_laser_material_order_email_config',
                'ordering': ['supplier'],
            },
        ),
    ]
