# Generated by Django 5.2.9 on 2026-09-12 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0084_add_two_person_only_to_process'),
        ('production', '0103_lasermaterialorderemailconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_type', models.CharField(max_length=50, verbose_name='ロック種別')),
                ('plan_date', models.DateField(blank=True, null=True, verbose_name='計画日')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='ロック日時')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.line', verbose_name='ライン')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ロック者')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '生産ロック',
                'verbose_name_plural': '生産ロック',
                'db_table': 'production_lock',
                'indexes': [models.Index(fields=['lock_type', 'line', 'plan_date'], name='production__lock_ty_dbe3f4_idx')],
                'unique_together': {('lock_type', 'line', 'plan_date', 'product')},
            },
        ),
    ]
