# Generated by Django 5.2.9 on 2026-09-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0104_production_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlock',
            name='locked_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ロック時計画数'),
        ),
    ]
