# Generated by Django 5.2.9 on 2026-09-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0084_add_two_person_only_to_process'),
        ('production', '0105_add_locked_qty_to_production_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserWeeklyMaterialDailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_date', models.DateField(verbose_name='日付')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='進度')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laser_weekly_material_daily_progresses', to='masters.product')),
            ],
            options={
                'db_table': 't_laser_weekly_material_daily_progress',
                'constraints': [models.UniqueConstraint(fields=('material', 'progress_date'), name='laser_weekly_material_daily_progress_unique')],
            },
        ),
    ]
