# Generated by Django 5.2.9 on 2026-09-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0106_add_laser_weekly_material_daily_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laserweeklymaterialinitialprogress',
            name='initial_progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='期首進度'),
        ),
    ]
