# Generated by Django 5.2.9 on 2026-09-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0107_change_material_initial_progress_to_decimal'),
        ('masters', '0085_add_special_management_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserMaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(verbose_name='入荷日')),
                ('received_lots', models.PositiveIntegerField(default=0, verbose_name='入荷ロット数')),
                ('received_sheets', models.PositiveIntegerField(default=0, verbose_name='端数枚数')),
                ('lot_number', models.CharField(blank=True, default='', max_length=100, verbose_name='ロット番号')),
                ('label_photo', models.FileField(blank=True, null=True, upload_to='laser_material_receipts/%Y/%m/', verbose_name='ラベル写真')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='production.laserweeklymaterialorderprogress', verbose_name='材料発注明細')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laser_material_receipts', to=settings.AUTH_USER_MODEL, verbose_name='入荷登録者')),
            ],
            options={
                'verbose_name': 'レーザ材料入荷実績',
                'verbose_name_plural': 'レーザ材料入荷実績',
                'db_table': 't_laser_material_receipt',
                'ordering': ['-received_date', '-id'],
            },
        ),
    ]
