# Generated by Django 5.2.9 on 2026-09-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0108_lasermaterialreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lasermaterialreceipt',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消日時'),
        ),
        migrations.AddField(
            model_name='lasermaterialreceipt',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_laser_material_receipts', to=settings.AUTH_USER_MODEL, verbose_name='取消者'),
        ),
        migrations.AddField(
            model_name='lasermaterialreceipt',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='取消理由'),
        ),
    ]
