# Generated by Django 5.2.9 on 2026-09-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0109_lasermaterialreceipt_cancellation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lasermaterialreceipt',
            options={'ordering': ['-received_date', '-id']},
        ),
    ]
