# Generated by Django 5.2.9 on 2026-10-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0086_add_is_order_day_to_calendar_day"),
        ("production", "0114_alter_processrealtimerecord_record_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="processrealtimerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("record_type", "PURCHASE"), _negated=True),
                    models.Q(
                        ("event_data__has_key", "source"),
                        ("event_data__isnull", False),
                        (
                            "event_data__source__in",
                            [
                                "PURCHASE_ACTUAL_INPUT",
                                "PURCHASE_RECEIVING",
                                "PURCHASE_RECEIVING_MOBILE",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="prr_purchase_requires_purchase_source",
            ),
        ),
    ]
