# Generated by Django 5.2.9 on 2026-02-21 04:01
# Modified: SeparateDatabaseAndState を使用。
# t_scrap_record / t_scrap_record_detail は orders マイグレーションで既に作成済み。
# このマイグレーションは DB を変更せず、Django の migration state を quality アプリに移管するのみ。

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0031_alter_calendar_options_alter_line_options_and_more'),
        ('production', '0018_include_current_month'),
        ('quality', '0004_add_occurrence_process_to_scraprecord'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ScrapRecord',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('product_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='製品コード')),
                        ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品名')),
                        ('event_type', models.CharField(choices=[('SCRAP', '仕損'), ('RETURN', '戻し')], default='SCRAP', max_length=20, verbose_name='イベント種別')),
                        ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='仕損数量')),
                        ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='記録時刻')),
                        ('plan_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='計画日')),
                        ('disposition_status', models.CharField(choices=[('PENDING', '判定待ち'), ('APPROVED', '使用可'), ('REJECTED', '仕損確定'), ('PARTIAL', '一部使用可')], default='REJECTED', max_length=20, verbose_name='判定ステータス')),
                        ('return_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='戻し数量')),
                        ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='判定日時')),
                        ('decided_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='判定者')),
                        ('reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='理由/区分')),
                        ('reason_detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='理由詳細')),
                        ('batch_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ロット番号')),
                        ('operator_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='作業者名')),
                        ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                        ('is_replenished', models.BooleanField(default=False, verbose_name='補充完了')),
                        ('replenished_at', models.DateTimeField(blank=True, null=True, verbose_name='補充完了日時')),
                        ('replenished_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='補充完了者')),
                        ('is_production_recorded', models.BooleanField(default=False, verbose_name='実績入力済み')),
                        ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.line', verbose_name='ライン')),
                        ('occurrence_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_occurrences', to='masters.process', verbose_name='発生工程')),
                        ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.process', verbose_name='工程')),
                        ('process_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrap_detail', to='production.processrealtimerecord', verbose_name='工程実時間記録')),
                        ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product', verbose_name='製品')),
                        ('return_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_records', to='quality.scraprecord', verbose_name='戻し対象仕損')),
                    ],
                    options={
                        'verbose_name': '仕損記録',
                        'verbose_name_plural': '仕損記録',
                        'db_table': 't_scrap_record',
                        'ordering': ['-recorded_at'],
                    },
                ),
                migrations.CreateModel(
                    name='ScrapRecordDetail',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('product_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='製品コード')),
                        ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品名')),
                        ('process_id', models.BigIntegerField(blank=True, null=True, verbose_name='工程ID')),
                        ('line_id', models.BigIntegerField(blank=True, null=True, verbose_name='ラインID')),
                        ('supplier_id', models.BigIntegerField(blank=True, null=True, verbose_name='仕入先ID')),
                        ('sourcing_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='調達区分')),
                        ('deduct_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='減算数量')),
                        ('is_replenished', models.BooleanField(default=False, verbose_name='補充完了')),
                        ('replenished_at', models.DateTimeField(blank=True, null=True, verbose_name='補充完了日時')),
                        ('replenished_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='補充完了者')),
                        ('is_backlog_processed', models.BooleanField(default=False, verbose_name='Backlog反映済み')),
                        ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product', verbose_name='製品')),
                        ('scrap_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quality.scraprecord', verbose_name='仕損記録')),
                    ],
                    options={
                        'verbose_name': '仕損記録明細',
                        'verbose_name_plural': '仕損記録明細',
                        'db_table': 't_scrap_record_detail',
                    },
                ),
                migrations.AddIndex(
                    model_name='scraprecord',
                    index=models.Index(fields=['process', 'recorded_at'], name='t_scrap_rec_process_79ed8b_idx'),
                ),
                migrations.AddIndex(
                    model_name='scraprecord',
                    index=models.Index(fields=['line', 'recorded_at'], name='t_scrap_rec_line_id_48671a_idx'),
                ),
            ],
        ),
    ]
