# Generated by Django 5.2.9 on 2026-03-03 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_code', models.CharField(max_length=40, verbose_name='設備コード')),
                ('sheet_name', models.CharField(max_length=120, verbose_name='設備名')),
                ('title', models.CharField(max_length=200, verbose_name='帳票タイトル')),
                ('source_sheet_name', models.CharField(blank=True, default='', max_length=80, verbose_name='元シート名')),
                ('revision_date', models.DateField(blank=True, null=True, verbose_name='改訂日')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='運用開始日')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('REVIEW_PENDING', '確認待ち'), ('APPROVAL_PENDING', '承認待ち'), ('APPROVED', '承認済み'), ('REJECTED', '差戻し')], default='DRAFT', max_length=20, verbose_name='ステータス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認日時')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('rejection_comment', models.TextField(blank=True, default='', verbose_name='差戻しコメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_approved', to=settings.AUTH_USER_MODEL, verbose_name='承認実施者')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_approver', to=settings.AUTH_USER_MODEL, verbose_name='承認担当')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='確認実施者')),
                ('reviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='確認担当')),
            ],
            options={
                'verbose_name': '設備点検表テンプレート',
                'verbose_name_plural': '設備点検表テンプレート',
                'db_table': 'quality_equipment_inspection_template',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('DAILY', '日次点検'), ('QUARTERLY', '定期実測')], default='DAILY', max_length=20, verbose_name='区分')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('inspection_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='点検No')),
                ('item_name', models.TextField(verbose_name='点検項目')),
                ('standard', models.TextField(blank=True, default='', verbose_name='規格')),
                ('frequency', models.CharField(blank=True, default='', max_length=50, verbose_name='確認頻度')),
                ('method', models.TextField(blank=True, default='', verbose_name='方法')),
                ('record_type', models.CharField(choices=[('CHECK', 'チェック'), ('NUMERIC', '数値'), ('TEXT', '文字')], default='CHECK', max_length=20, verbose_name='記録種別')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='単位')),
                ('criteria', models.TextField(blank=True, default='', verbose_name='判定基準')),
                ('is_required', models.BooleanField(default=True, verbose_name='必須')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.equipmentinspectiontemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': '設備点検項目',
                'verbose_name_plural': '設備点検項目',
                'db_table': 'quality_equipment_inspection_item',
                'ordering': ['section_type', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentInspectionWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', '作成'), ('UPDATED', '更新'), ('SUBMITTED', '確認依頼'), ('REVIEWED', '確認完了'), ('APPROVED', '承認'), ('REJECTED', '差戻し')], max_length=20, verbose_name='操作')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='遷移前')),
                ('to_status', models.CharField(blank=True, default='', max_length=20, verbose_name='遷移後')),
                ('comment', models.TextField(blank=True, default='', verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_template_workflow_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='quality.equipmentinspectiontemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': '設備点検表ワークフロー履歴',
                'verbose_name_plural': '設備点検表ワークフロー履歴',
                'db_table': 'quality_equipment_inspection_workflow_log',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentinspectiontemplate',
            index=models.Index(fields=['sheet_code', 'status'], name='quality_equ_sheet_c_daefce_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentinspectiontemplate',
            index=models.Index(fields=['status', 'is_active'], name='quality_equ_status_ec0365_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentinspectiontemplate',
            unique_together={('sheet_code', 'version')},
        ),
        migrations.AddIndex(
            model_name='equipmentinspectionitem',
            index=models.Index(fields=['template', 'section_type', 'display_order'], name='quality_equ_templat_4f4c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentinspectionworkflowlog',
            index=models.Index(fields=['template', 'created_at'], name='quality_equ_templat_74dd82_idx'),
        ),
    ]
