# Generated by Django 5.2.9 on 2026-03-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_equipmentinspectiontemplate_equipmentinspectionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinspectiontemplate',
            name='revision_notes',
            field=models.TextField(blank=True, default='', verbose_name='改定内容'),
        ),
    ]
