# Generated by Django 5.2.9 on 2026-03-22 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_add_revision_notes_to_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_code', models.CharField(max_length=40, verbose_name='設備コード')),
                ('sheet_name', models.CharField(max_length=120, verbose_name='設備名')),
                ('template_title', models.CharField(blank=True, default='', max_length=200, verbose_name='帳票タイトル')),
                ('template_version', models.PositiveIntegerField(default=1, verbose_name='テンプレート版')),
                ('operation_date', models.DateField(verbose_name='点検日')),
                ('section_type', models.CharField(choices=[('DAILY', '日次点検'), ('QUARTERLY', '定期実測')], default='DAILY', max_length=20, verbose_name='区分')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('COMPLETED', '完了')], default='DRAFT', max_length=20, verbose_name='状態')),
                ('overall_result', models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], default='', max_length=10, verbose_name='総合判定')),
                ('memo', models.TextField(blank=True, default='', verbose_name='備考')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_inspection_records', to=settings.AUTH_USER_MODEL, verbose_name='実施者')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_records', to='quality.equipmentinspectiontemplate', verbose_name='使用テンプレート')),
            ],
            options={
                'verbose_name': '設備点検実施',
                'verbose_name_plural': '設備点検実施',
                'db_table': 'quality_equipment_inspection_record',
                'ordering': ['-operation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentInspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('inspection_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='点検No')),
                ('item_name', models.TextField(verbose_name='点検項目')),
                ('standard', models.TextField(blank=True, default='', verbose_name='規格')),
                ('frequency', models.CharField(blank=True, default='', max_length=50, verbose_name='確認頻度')),
                ('method', models.TextField(blank=True, default='', verbose_name='方法')),
                ('record_type', models.CharField(choices=[('CHECK', 'チェック'), ('NUMERIC', '数値'), ('TEXT', '文字')], default='CHECK', max_length=20, verbose_name='記録種別')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='単位')),
                ('criteria', models.TextField(blank=True, default='', verbose_name='判定基準')),
                ('is_required', models.BooleanField(default=True, verbose_name='必須')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='数値記録')),
                ('text_value', models.TextField(blank=True, default='', verbose_name='文字記録')),
                ('judgement', models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], default='', max_length=10, verbose_name='判定')),
                ('comment', models.TextField(blank=True, default='', verbose_name='コメント')),
                ('measured_at', models.DateTimeField(blank=True, null=True, verbose_name='記録日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_results', to='quality.equipmentinspectionitem', verbose_name='元点検項目')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.equipmentinspectionrecord', verbose_name='点検実施')),
            ],
            options={
                'verbose_name': '設備点検実施明細',
                'verbose_name_plural': '設備点検実施明細',
                'db_table': 'quality_equipment_inspection_result',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentInspectionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_code', models.CharField(max_length=40, verbose_name='設備コード')),
                ('sheet_name', models.CharField(max_length=120, verbose_name='設備名')),
                ('target_month', models.DateField(verbose_name='対象月')),
                ('confirm_type', models.CharField(choices=[('WEEKLY_LEADER', '週間リーダ確認'), ('MONTHLY_CHIEF', '月間班長確認')], max_length=30, verbose_name='確認種別')),
                ('week_index', models.PositiveIntegerField(default=0, verbose_name='週番号')),
                ('comment', models.TextField(blank=True, default='', verbose_name='コメント')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_inspection_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
            ],
            options={
                'verbose_name': '設備点検確認',
                'verbose_name_plural': '設備点検確認',
                'db_table': 'quality_equipment_inspection_confirmation',
                'ordering': ['target_month', 'confirm_type', 'week_index', 'id'],
                'indexes': [models.Index(fields=['sheet_code', 'target_month'], name='quality_equ_sheet_c_2f2945_idx'), models.Index(fields=['target_month', 'confirm_type'], name='quality_equ_target__ff186f_idx')],
                'unique_together': {('sheet_code', 'target_month', 'confirm_type', 'week_index')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentInspectionItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, default='', verbose_name='補足説明')),
                ('check_point', models.TextField(blank=True, default='', verbose_name='確認ポイント')),
                ('ok_example', models.TextField(blank=True, default='', verbose_name='OK例')),
                ('ng_example', models.TextField(blank=True, default='', verbose_name='NG例')),
                ('image_url', models.CharField(blank=True, default='', max_length=255, verbose_name='画像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quality.equipmentinspectionitem', verbose_name='点検項目')),
            ],
            options={
                'verbose_name': '設備点検項目付表',
                'verbose_name_plural': '設備点検項目付表',
                'db_table': 'quality_equipment_inspection_item_attachment',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['item', 'display_order'], name='quality_equ_item_id_51a606_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentinspectionrecord',
            index=models.Index(fields=['sheet_code', 'operation_date'], name='quality_equ_sheet_c_41c4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentinspectionrecord',
            index=models.Index(fields=['operation_date', 'status'], name='quality_equ_operati_226c4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentinspectionrecord',
            unique_together={('sheet_code', 'operation_date', 'section_type')},
        ),
        migrations.AddIndex(
            model_name='equipmentinspectionresult',
            index=models.Index(fields=['record', 'display_order'], name='quality_equ_record__7c2289_idx'),
        ),
    ]
