# Generated by Django 5.2.9 on 2026-03-22 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_workflow(apps, schema_editor):
    template_model = apps.get_model('quality', 'EquipmentInspectionTemplate')
    workflow_log_model = apps.get_model('quality', 'EquipmentInspectionWorkflowLog')
    task_model = apps.get_model('quality', 'EquipmentInspectionTask')

    status_map = {
        'REVIEW_PENDING': 'SUPERVISOR_PENDING',
        'APPROVAL_PENDING': 'MANAGER_PENDING',
    }
    for before_status, after_status in status_map.items():
        template_model.objects.filter(status=before_status).update(status=after_status)
        workflow_log_model.objects.filter(from_status=before_status).update(from_status=after_status)
        workflow_log_model.objects.filter(to_status=before_status).update(to_status=after_status)

    workflow_log_model.objects.filter(action='REVIEWED').update(action='SUPERVISOR_REVIEWED')

    task_type_by_status = {
        'SUPERVISOR_PENDING': 'SUPERVISOR_REVIEW',
        'CHIEF_PENDING': 'CHIEF_REVIEW',
        'MANAGER_PENDING': 'MANAGER_APPROVE',
    }
    assignee_field_by_status = {
        'SUPERVISOR_PENDING': 'reviewer_user_id',
        'CHIEF_PENDING': 'chief_user_id',
        'MANAGER_PENDING': 'approver_user_id',
    }
    pending_templates = template_model.objects.filter(status__in=task_type_by_status.keys())
    for template in pending_templates.iterator():
        task_type = task_type_by_status.get(template.status)
        assignee_field = assignee_field_by_status.get(template.status)
        assigned_to_id = getattr(template, assignee_field, None)
        if not task_type or not assigned_to_id:
            continue
        exists = task_model.objects.filter(
            template_id=template.id,
            task_type=task_type,
            assigned_to_id=assigned_to_id,
            status='PENDING',
        ).exists()
        if exists:
            continue
        task_model.objects.create(
            template_id=template.id,
            task_type=task_type,
            assigned_to_id=assigned_to_id,
            status='PENDING',
            due_date=template.effective_from,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_equipmentinspectionrecord_equipmentinspectionresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinspectiontemplate',
            name='chief_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='係長確認日時'),
        ),
        migrations.AddField(
            model_name='equipmentinspectiontemplate',
            name='chief_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_chief_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='係長確認実施者'),
        ),
        migrations.AddField(
            model_name='equipmentinspectiontemplate',
            name='chief_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_chief', to=settings.AUTH_USER_MODEL, verbose_name='係長担当'),
        ),
        migrations.AlterField(
            model_name='equipmentinspectiontemplate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='部長承認日時'),
        ),
        migrations.AlterField(
            model_name='equipmentinspectiontemplate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_approved', to=settings.AUTH_USER_MODEL, verbose_name='部長承認実施者'),
        ),
        migrations.AlterField(
            model_name='equipmentinspectiontemplate',
            name='approver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_approver', to=settings.AUTH_USER_MODEL, verbose_name='部長担当'),
        ),
        migrations.AlterField(
            model_name='equipmentinspectiontemplate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='班長確認日時'),
        ),
        migrations.AlterField(
            model_name='equipmentinspectiontemplate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='班長確認実施者'),
        ),
        migrations.AlterField(
            model_name='equipmentinspectiontemplate',
            name='reviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_templates_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='班長担当'),
        ),
        migrations.AlterField(
            model_name='equipmentinspectiontemplate',
            name='status',
            field=models.CharField(choices=[('DRAFT', '下書き'), ('SUPERVISOR_PENDING', '班長確認待ち'), ('CHIEF_PENDING', '係長確認待ち'), ('MANAGER_PENDING', '部長承認待ち'), ('APPROVED', '承認済み'), ('REJECTED', '差戻し')], default='DRAFT', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='equipmentinspectionworkflowlog',
            name='action',
            field=models.CharField(choices=[('CREATED', '作成'), ('UPDATED', '更新'), ('SUBMITTED', '確認依頼'), ('SUPERVISOR_REVIEWED', '班長確認完了'), ('CHIEF_REVIEWED', '係長確認完了'), ('APPROVED', '部長承認'), ('REJECTED', '差戻し')], max_length=20, verbose_name='操作'),
        ),
        migrations.CreateModel(
            name='EquipmentInspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('SUPERVISOR_REVIEW', '班長確認'), ('CHIEF_REVIEW', '係長確認'), ('MANAGER_APPROVE', '部長承認')], max_length=30, verbose_name='タスク種別')),
                ('status', models.CharField(choices=[('PENDING', '未対応'), ('DONE', '完了'), ('SKIPPED', 'スキップ')], default='PENDING', max_length=20, verbose_name='状態')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_inspection_tasks', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='quality.equipmentinspectiontemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': '設備点検表タスク',
                'verbose_name_plural': '設備点検表タスク',
                'db_table': 'quality_equipment_inspection_task',
                'ordering': ['status', 'due_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='quality_equ_assigne_e17c9b_idx'), models.Index(fields=['task_type', 'status'], name='quality_equ_task_ty_b2ce57_idx'), models.Index(fields=['template'], name='quality_equ_templat_2d6dfa_idx')],
            },
        ),
        migrations.RunPython(migrate_existing_workflow, migrations.RunPython.noop),
    ]
