# Generated by Django 5.2.9 on 2026-03-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0038_add_use_direct_process_to_line'),
        ('quality', '0009_equipmentinspectiontemplate_chief_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinspectiontemplate',
            name='lines',
            field=models.ManyToManyField(blank=True, related_name='inspection_templates', to='masters.line', verbose_name='対象ライン'),
        ),
        migrations.AddField(
            model_name='equipmentinspectiontemplate',
            name='processes',
            field=models.ManyToManyField(blank=True, related_name='inspection_templates', to='masters.process', verbose_name='対象工程'),
        ),
    ]
