# Generated by Django 5.2.9 on 2026-03-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_add_process_line_to_inspection_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinspectiontask',
            name='task_type',
            field=models.CharField(choices=[('SUPERVISOR_REVIEW', '班長確認'), ('CHIEF_REVIEW', '係長確認'), ('MANAGER_APPROVE', '部長承認'), ('CREATOR_FIX', '差戻し修正')], max_length=30, verbose_name='タスク種別'),
        ),
    ]
