# Generated by Django 5.2.9 on 2026-04-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0011_add_creator_fix_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinspectiontemplate',
            name='submitted_items_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='提出時点検項目スナップショット'),
        ),
    ]
