# Generated by Django 5.2.9 on 2026-04-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0012_add_submitted_items_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinspectiontemplate',
            name='measurement_months',
            field=models.JSONField(blank=True, default=list, verbose_name='定期実測対象月'),
        ),
    ]
