# Generated by Django 5.2.9 on 2026-04-27 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0047_routingstep_supplier'),
        ('production', '0050_processworksessionequipment'),
        ('quality', '0013_add_measurement_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChecksheetTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='テンプレート名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_checksheet_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_checksheet_templates', to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_checksheet_templates', to='masters.process', verbose_name='工程')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_checksheet_templates', to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '製品チェックシートテンプレート',
                'verbose_name_plural': '製品チェックシートテンプレート',
                'db_table': 'quality_product_checksheet_template',
                'ordering': ['line_id', 'process_id', 'product_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductChecksheetBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lot_no', models.CharField(blank=True, default='', max_length=100, verbose_name='ロットNo')),
                ('quantity', models.PositiveIntegerField(verbose_name='対象数量')),
                ('operator_name', models.CharField(blank=True, default='', max_length=120, verbose_name='作業者')),
                ('source_context', models.JSONField(blank=True, default=dict, verbose_name='工程入力元情報')),
                ('status', models.CharField(choices=[('OPEN', '入力中'), ('COMPLETED', '入力完了')], default='OPEN', max_length=20, verbose_name='状態')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='入力完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_checksheet_batches_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_checksheet_batches', to='masters.line', verbose_name='ライン')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_checksheet_batches', to='masters.process', verbose_name='工程')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_checksheet_batches', to='masters.product', verbose_name='製品')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_checksheet_batches', to='production.productionorder', verbose_name='製造指示')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='quality.productchecksheettemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': '製品チェックシート入力ロット',
                'verbose_name_plural': '製品チェックシート入力ロット',
                'db_table': 'quality_product_checksheet_batch',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductChecksheetTemplateVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField(verbose_name='版')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('ACTIVE', '有効'), ('ARCHIVED', '過去版')], default='DRAFT', max_length=20, verbose_name='状態')),
                ('source_type', models.CharField(choices=[('pdf', 'PDF台紙'), ('image', '画像台紙')], default='image', max_length=20, verbose_name='台紙種別')),
                ('source_pdf', models.FileField(blank=True, upload_to='product_checksheets/source_pdf/', verbose_name='台紙PDF')),
                ('source_image', models.ImageField(blank=True, upload_to='product_checksheets/source_image/', verbose_name='台紙画像')),
                ('background_image', models.ImageField(blank=True, upload_to='product_checksheets/background/', verbose_name='編集用背景画像')),
                ('background_width', models.PositiveIntegerField(default=1200, verbose_name='背景幅')),
                ('background_height', models.PositiveIntegerField(default=1600, verbose_name='背景高さ')),
                ('editor_notes', models.TextField(blank=True, default='', verbose_name='編集メモ')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='有効化日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_checksheet_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quality.productchecksheettemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': '製品チェックシートテンプレート版',
                'verbose_name_plural': '製品チェックシートテンプレート版',
                'db_table': 'quality_product_checksheet_template_version',
                'ordering': ['template_id', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='ProductChecksheetRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_no', models.PositiveIntegerField(verbose_name='ロット内番号')),
                ('status', models.CharField(choices=[('PENDING', '未入力'), ('COMPLETED', '入力完了'), ('APPROVED', '承認済み')], default='PENDING', max_length=20, verbose_name='状態')),
                ('responses_json', models.JSONField(blank=True, default=dict, verbose_name='回答データ')),
                ('planned_ship_date', models.DateField(blank=True, null=True, verbose_name='出荷日')),
                ('shipment_unit_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='台目')),
                ('shipment_sequence_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='出荷分内番号')),
                ('completed_by_name', models.CharField(blank=True, default='', max_length=120, verbose_name='入力者')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='入力完了日時')),
                ('supervisor_name', models.CharField(blank=True, default='', max_length=120, verbose_name='確認者')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('generated_pdf', models.FileField(blank=True, upload_to='product_checksheets/approved_pdfs/', verbose_name='完成PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='quality.productchecksheetbatch', verbose_name='入力ロット')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='quality.productchecksheettemplateversion', verbose_name='テンプレート版')),
            ],
            options={
                'verbose_name': '製品チェックシート記録',
                'verbose_name_plural': '製品チェックシート記録',
                'db_table': 'quality_product_checksheet_record',
                'ordering': ['batch_id', 'sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='ProductChecksheetField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, verbose_name='内部キー')),
                ('label', models.CharField(max_length=120, verbose_name='表示名')),
                ('field_type', models.CharField(choices=[('checkbox', 'チェック'), ('text', 'テキスト'), ('aggregate_okng', 'OK/NG'), ('date', '日付'), ('photo', '写真'), ('pen', '手書き'), ('worker_name', '作業者名'), ('supervisor_stamp', '監督者確認スタンプ')], default='text', max_length=30, verbose_name='項目種類')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='説明')),
                ('x', models.FloatField(default=0, verbose_name='左位置')),
                ('y', models.FloatField(default=0, verbose_name='上位置')),
                ('width', models.FloatField(default=160, verbose_name='幅')),
                ('height', models.FloatField(default=36, verbose_name='高さ')),
                ('required', models.BooleanField(default=False, verbose_name='必須')),
                ('placeholder', models.CharField(blank=True, default='', max_length=120, verbose_name='初期表示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('show_label', models.BooleanField(default=True, verbose_name='表示名を表示')),
                ('text_direction', models.CharField(choices=[('horizontal', '横書き'), ('vertical', '縦書き')], default='horizontal', max_length=20, verbose_name='文字方向')),
                ('counter_step', models.PositiveIntegerField(default=1, verbose_name='カウント加算値')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='quality.productchecksheettemplateversion', verbose_name='テンプレート版')),
            ],
            options={
                'verbose_name': '製品チェックシート項目',
                'verbose_name_plural': '製品チェックシート項目',
                'db_table': 'quality_product_checksheet_field',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productchecksheetbatch',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='quality.productchecksheettemplateversion', verbose_name='テンプレート版'),
        ),
        migrations.CreateModel(
            name='ProductChecksheetPhoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=80, verbose_name='項目キー')),
                ('image', models.ImageField(upload_to='product_checksheets/photos/', verbose_name='写真')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='quality.productchecksheetrecord', verbose_name='チェック記録')),
            ],
            options={
                'verbose_name': '製品チェックシート写真',
                'verbose_name_plural': '製品チェックシート写真',
                'db_table': 'quality_product_checksheet_photo',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['record', 'field_key'], name='quality_pro_record__dacc9b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productchecksheettemplate',
            index=models.Index(fields=['line', 'process', 'product', 'is_active'], name='quality_pro_line_id_602c67_idx'),
        ),
        migrations.AddIndex(
            model_name='productchecksheettemplate',
            index=models.Index(fields=['product', 'is_active'], name='quality_pro_product_6e4373_idx'),
        ),
        migrations.AddIndex(
            model_name='productchecksheettemplateversion',
            index=models.Index(fields=['template', 'status'], name='quality_pro_templat_be2815_idx'),
        ),
        migrations.AddIndex(
            model_name='productchecksheettemplateversion',
            index=models.Index(fields=['template', 'version_no'], name='quality_pro_templat_1222b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productchecksheettemplateversion',
            unique_together={('template', 'version_no')},
        ),
        migrations.AddIndex(
            model_name='productchecksheetrecord',
            index=models.Index(fields=['batch', 'status'], name='quality_pro_batch_i_47fd10_idx'),
        ),
        migrations.AddIndex(
            model_name='productchecksheetrecord',
            index=models.Index(fields=['planned_ship_date', 'shipment_unit_no'], name='quality_pro_planned_2a2ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='productchecksheetrecord',
            index=models.Index(fields=['status', 'approved_at'], name='quality_pro_status_4f0d4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productchecksheetrecord',
            unique_together={('batch', 'sequence_no')},
        ),
        migrations.AddIndex(
            model_name='productchecksheetfield',
            index=models.Index(fields=['version', 'sort_order'], name='quality_pro_version_3a07ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productchecksheetfield',
            unique_together={('version', 'key')},
        ),
        migrations.AddIndex(
            model_name='productchecksheetbatch',
            index=models.Index(fields=['production_order', 'line', 'process', 'product'], name='quality_pro_product_394dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='productchecksheetbatch',
            index=models.Index(fields=['status', 'created_at'], name='quality_pro_status_ee1331_idx'),
        ),
        migrations.AddIndex(
            model_name='productchecksheetbatch',
            index=models.Index(fields=['lot_no'], name='quality_pro_lot_no_43e49d_idx'),
        ),
    ]
