# Generated by Django 5.2.9 on 2026-04-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0014_productchecksheettemplate_productchecksheetbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchecksheettemplateversion',
            name='document_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='帳票タイトル'),
        ),
        migrations.AddField(
            model_name='productchecksheettemplateversion',
            name='effective_from',
            field=models.DateField(blank=True, null=True, verbose_name='運用開始日'),
        ),
        migrations.AddField(
            model_name='productchecksheettemplateversion',
            name='revision_date',
            field=models.DateField(blank=True, null=True, verbose_name='改訂日'),
        ),
        migrations.AddField(
            model_name='productchecksheettemplateversion',
            name='revision_notes',
            field=models.TextField(blank=True, default='', verbose_name='改訂内容'),
        ),
        migrations.AddField(
            model_name='productchecksheettemplateversion',
            name='sheet_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='元シート名'),
        ),
    ]
