# Generated by Django 5.2.9 on 2026-05-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0023_integrated_template_workflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='integratedchecksheetbatch',
            new_name='quality_int_product_55e2c6_idx',
            old_name='idx_intcs_batch_prod_date',
        ),
        migrations.RenameIndex(
            model_name='integratedchecksheetbatch',
            new_name='quality_int_status_ca5e4e_idx',
            old_name='idx_intcs_batch_status',
        ),
        migrations.RenameIndex(
            model_name='productchecksheetbatch',
            new_name='quality_pro_plan_da_1c495e_idx',
            old_name='quality_pro_plan_da_idx',
        ),
        migrations.AlterField(
            model_name='integratedchecksheetprocessblock',
            name='sketch_image',
            field=models.ImageField(blank=True, upload_to='integrated_checksheets/sketches/', verbose_name='台紙画像'),
        ),
    ]
