# Generated by Django 5.2.9 on 2026-05-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0025_batch_confirm_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratedchecksheettemplate',
            name='revision_notes',
            field=models.TextField(default='', verbose_name='改訂内容'),
        ),
        migrations.CreateModel(
            name='IntegratedChecksheetTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('SUPERVISOR_REVIEW', '班長確認'), ('CHIEF_REVIEW', '係長確認'), ('MANAGER_APPROVE', '部長承認'), ('CREATOR_FIX', '差戻し修正')], max_length=30, verbose_name='タスク種別')),
                ('status', models.CharField(choices=[('PENDING', '未対応'), ('DONE', '完了'), ('SKIPPED', 'スキップ')], default='PENDING', max_length=20, verbose_name='状態')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrated_checksheet_tasks', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='quality.integratedchecksheettemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': '工程一体CSタスク',
                'verbose_name_plural': '工程一体CSタスク',
                'db_table': 'quality_integrated_cs_task',
            },
        ),
    ]
