# Generated by Django 5.2.9 on 2026-05-10 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0026_add_integrated_checksheet_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integratedchecksheettemplate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='部長承認日時'),
        ),
        migrations.AddField(
            model_name='integratedchecksheettemplate',
            name='chief_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='係長確認日時'),
        ),
        migrations.AddField(
            model_name='integratedchecksheettemplate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='班長確認日時'),
        ),
        migrations.CreateModel(
            name='IntegratedChecksheetWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', '作成'), ('UPDATED', '更新'), ('SUBMITTED', '確認依頼'), ('SUPERVISOR_REVIEWED', '班長確認完了'), ('CHIEF_REVIEWED', '係長承認完了'), ('APPROVED', '部長承認'), ('REJECTED', '差戻し')], max_length=20, verbose_name='操作')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='遷移前')),
                ('to_status', models.CharField(blank=True, default='', max_length=20, verbose_name='遷移後')),
                ('comment', models.TextField(blank=True, default='', verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ics_template_workflow_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='quality.integratedchecksheettemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': '工程一体CSワークフロー履歴',
                'verbose_name_plural': '工程一体CSワークフロー履歴',
                'db_table': 'quality_integrated_cs_workflow_log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['template', 'created_at'], name='quality_int_templat_c688c9_idx')],
            },
        ),
    ]
