# Generated by Django 5.2.9 on 2026-06-09 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0033_integrated_item_record_type_add_numeric_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratedchecksheetitem',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
        migrations.CreateModel(
            name='IntegratedChecksheetItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, default='', verbose_name='補足説明')),
                ('check_point', models.TextField(blank=True, default='', verbose_name='確認ポイント')),
                ('ok_example', models.TextField(blank=True, default='', verbose_name='OK例')),
                ('ng_example', models.TextField(blank=True, default='', verbose_name='NG例')),
                ('image_url', models.CharField(blank=True, default='', max_length=255, verbose_name='画像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quality.integratedchecksheetitem', verbose_name='チェック項目')),
            ],
            options={
                'verbose_name': 'チェック項目付表',
                'verbose_name_plural': 'チェック項目付表',
                'db_table': 'quality_integrated_cs_item_attachment',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
