# Generated by Django 5.2.9 on 2026-06-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0034_integrated_checksheet_item_remarks_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratedchecksheetcheck',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='写真URL'),
        ),
    ]
