# Generated by Django 5.2.9 on 2026-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0035_integrated_check_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratedchecksheetunit',
            name='sei_ban',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='製番'),
        ),
    ]
