# Generated by Django 5.2.9 on 2026-08-12 18:44
# 0039 で DROP TABLE IF EXISTS 済みのため、DB操作は不要。
# Django の内部状態（モデル定義）だけ同期する。

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0039_drop_product_checksheet_tables'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='productchecksheetrecord',
                    name='batch',
                ),
                migrations.AlterUniqueTogether(
                    name='productchecksheetfield',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='productchecksheetfield',
                    name='template',
                ),
                migrations.RemoveField(
                    model_name='productchecksheetphoto',
                    name='record',
                ),
                migrations.AlterUniqueTogether(
                    name='productchecksheetrecord',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='productchecksheetrecord',
                    name='template',
                ),
                migrations.RemoveField(
                    model_name='productchecksheettask',
                    name='assigned_to',
                ),
                migrations.RemoveField(
                    model_name='productchecksheettask',
                    name='template',
                ),
                migrations.AlterUniqueTogether(
                    name='productchecksheettemplate',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='productchecksheettemplate',
                    name='approved_by',
                ),
                migrations.RemoveField(
                    model_name='productchecksheettemplate',
                    name='approver_user',
                ),
                migrations.RemoveField(
                    model_name='productchecksheettemplate',
                    name='chief_reviewed_by',
                ),
                migrations.RemoveField(
                    model_name='productchecksheettemplate',
                    name='chief_user',
                ),
                migrations.RemoveField(
                    model_name='productchecksheettemplate',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='productchecksheettemplate',
                    name='line',
                ),
                migrations.RemoveField(
                    model_name='productchecksheettemplate',
                    name='process',
                ),
                migrations.RemoveField(
                    model_name='productchecksheettemplate',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='productchecksheettemplate',
                    name='reviewed_by',
                ),
                migrations.RemoveField(
                    model_name='productchecksheettemplate',
                    name='reviewer_user',
                ),
                migrations.RemoveField(
                    model_name='productchecksheetworkflowlog',
                    name='template',
                ),
                migrations.RemoveField(
                    model_name='productchecksheetworkflowlog',
                    name='actor',
                ),
                migrations.DeleteModel(
                    name='ProductChecksheetBatch',
                ),
                migrations.DeleteModel(
                    name='ProductChecksheetField',
                ),
                migrations.DeleteModel(
                    name='ProductChecksheetPhoto',
                ),
                migrations.DeleteModel(
                    name='ProductChecksheetRecord',
                ),
                migrations.DeleteModel(
                    name='ProductChecksheetTask',
                ),
                migrations.DeleteModel(
                    name='ProductChecksheetTemplate',
                ),
                migrations.DeleteModel(
                    name='ProductChecksheetWorkflowLog',
                ),
            ],
        ),
    ]
