# Generated by Django 5.2.9 on 2026-08-19 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0081_kubotasakaitruck_auto_assign_target'),
        ('quality', '0040_remove_productchecksheetrecord_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecksheetReworkAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='修正流動率閾値(%)')),
                ('scheduled_hour', models.PositiveSmallIntegerField(default=17, verbose_name='実行時（時）')),
                ('scheduled_minute', models.PositiveSmallIntegerField(default=0, verbose_name='実行時（分）')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('lookback_days', models.PositiveSmallIntegerField(default=1, verbose_name='集計対象日数（当日含む）')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最終実行日時')),
                ('last_run_message', models.TextField(blank=True, default='', verbose_name='最終実行メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checksheet_rework_alert_configs', to='masters.line', verbose_name='対象ライン')),
                ('notify_users', models.ManyToManyField(blank=True, related_name='checksheet_rework_alert_configs', to=settings.AUTH_USER_MODEL, verbose_name='通知先ユーザー')),
            ],
            options={
                'verbose_name': '修正流動率通知設定',
                'verbose_name_plural': '修正流動率通知設定',
                'db_table': 'quality_checksheet_rework_alert_config',
            },
        ),
    ]
