# Generated by Django 5.2.9 on 2026-08-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0041_checksheetreworkalertconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksheetreworkalertconfig',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name='メール通知有効'),
        ),
    ]
