"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent

# ルートの config.py 等を読み込むためにパスを追加
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-_4wufh_x8tvr3%_0d%!r4b_&uvlgf!nhvl--&(8+%hncxf(9tj')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Allow local access plus any comma-separated hosts from ALLOWED_HOSTS env
_default_hosts = {"localhost", "127.0.0.1", "10.0.1.36", "10.0.1.232", "192.168.0.11", "192.168.0.12", "192.168.0.9", "192.168.0.16", "192.168.0.22", "192.168.0.39", "192.168.0.15", "192.168.0.18", "192.168.0.19", "192.168.11.5"}
_env_hosts = {
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "").split(",")
    if host.strip()
}
ALLOWED_HOSTS = list(_default_hosts | _env_hosts)

# Disable COOP header on insecure dev origins to avoid browser warnings
SECURE_CROSS_ORIGIN_OPENER_POLICY = None if DEBUG else "same-origin"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'ai',
    'ocr',
    'masters',
    'orders',
    'production',
    'purchase',
    'quality',
    'shipping',
    'accounts',
    'proposals',
    'notifications',
    'overtime',
    'system_settings',
    'outsource',
    'shifts',
    'consumables',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'apps' / 'masters' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 未保存の分析案は共有Redisだけへ保持し、未設定時に代替先へ保存しない。
# Dockerなしの開発接続先は pm_backend/.env、本番はComposeの内部サービスURLを使う。
AI_ANALYSIS_REDIS_URL = os.getenv('AI_ANALYSIS_REDIS_URL', '').strip()

AI_READER_DB_OPTIONS = {
    'charset': 'utf8mb4',
    'init_command': "SET sql_mode='STRICT_TRANS_TABLES', time_zone='+09:00'",
    'connection_timeout': 10,
}
_ai_reader_ssl_ca = os.getenv('AI_DB_SSL_CA', '').strip()
_ai_reader_ssl_cert = os.getenv('AI_DB_SSL_CERT', '').strip()
_ai_reader_ssl_key = os.getenv('AI_DB_SSL_KEY', '').strip()
# MySQL公式コネクタ向けのTLS設定。CA指定時はサーバー証明書も検証する。
if _ai_reader_ssl_ca:
    AI_READER_DB_OPTIONS['ssl_ca'] = _ai_reader_ssl_ca
    AI_READER_DB_OPTIONS['ssl_verify_cert'] = True
    if _ai_reader_ssl_cert:
        AI_READER_DB_OPTIONS['ssl_cert'] = _ai_reader_ssl_cert
    if _ai_reader_ssl_key:
        AI_READER_DB_OPTIONS['ssl_key'] = _ai_reader_ssl_key
else:
    AI_READER_DB_OPTIONS['ssl_disabled'] = False

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'pm_db'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', time_zone='+09:00'",
            'connect_timeout': 10,
        },
        'CONN_HEALTH_CHECKS': True,
    },
    # AIチャットの集計専用。通常業務の default 接続へフォールバックしない。
    'ai_reader': {
        'ENGINE': 'mysql.connector.django',
        'NAME': os.getenv('AI_DB_NAME', os.getenv('DB_NAME', '')),
        'USER': os.getenv('AI_DB_USER', ''),
        'PASSWORD': os.getenv('AI_DB_PASSWORD', ''),
        'HOST': os.getenv('AI_DB_HOST', os.getenv('DB_HOST', '')),
        'PORT': os.getenv('AI_DB_PORT', os.getenv('DB_PORT', '3306')),
        'OPTIONS': AI_READER_DB_OPTIONS,
        'CONN_HEALTH_CHECKS': True,
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = False  # 日本時間をそのままDBに保存


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# nginx リバースプロキシ経由のHTTPS対応
# X-Forwarded-Proto ヘッダーが付いている場合のみ有効（開発環境には影響なし）
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS設定
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite default port
    "http://localhost:5174",
    "http://localhost:8501",  # Custom port
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8501",
    "http://10.0.1.194:8501",  # IP address
    "http://10.0.1.232:8501",  # Production IP address
    "https://10.0.1.232:8501",  # Production HTTPS
    "https://localhost:8501",
    "http://192.168.0.18",
    "http://192.168.0.11",
    "http://192.168.0.15",
    "http://192.168.0.7",
    "http://192.168.0.19",
    "http://192.168.0.9",
    "http://192.168.0.39",
    "http://192.168.0.9:8501",
    "http://192.168.0.18:8501",
    "http://192.168.0.39:8501",
    "http://192.168.0.15:5173",
    "http://192.168.0.39:5173",
    "http://192.168.0.39:5174",
    "http://192.168.0.7:8501",
    "http://192.168.0.10:8501",
    "http://192.168.0.11:8501",
    "http://192.168.0.15:8501",
    "http://192.168.0.19:8501",
    "http://192.168.0.19:5173",
    "http://192.168.0.19:5174",
    "http://192.168.0.22",
    "http://192.168.0.22:8501",
    "http://192.168.11.5",
    "http://192.168.11.5:8501",
]

CORS_ALLOW_CREDENTIALS = True

# CSRF設定（JavaScriptからクッキーを読み取れるようにする）
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:8501",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8501",
    "http://10.0.1.194:8501",
    "https://10.0.1.194:8501",
    "http://10.0.1.232:8501",  # Production IP address
    "https://10.0.1.232:8501",
    "http://192.168.0.18",
    "http://192.168.0.9",
    "http://192.168.0.9:8501",
    "http://192.168.0.18:8501",
    "http://192.168.0.7",
    "http://192.168.0.7:8501",
    "http://192.168.0.11",
    "http://192.168.0.11:8501",
    "http://192.168.0.15",
    "http://192.168.0.15:8501",
    "http://192.168.0.15:5173",
    "http://192.168.0.15:5174",
    "http://192.168.0.19",
    "http://192.168.0.19:8501",
    "http://192.168.0.19:5173",
    "http://192.168.0.19:5174",
    "http://192.168.0.22",
    "http://192.168.0.22:8501",
    "http://192.168.11.5",
    "http://192.168.11.5:8501",
]

# REST Framework設定
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'project.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'project.authentication.CsrfExemptSessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# ログ設定
LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
            'filename': str(LOG_DIR / 'production.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'trace_file': {
            'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
            'filename': str(LOG_DIR / 'production_trace.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'production': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'production.trace': {
            'handlers': ['console', 'trace_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Web Push 設定
WEB_PUSH_VAPID_PUBLIC_KEY = os.getenv('WEB_PUSH_VAPID_PUBLIC_KEY', '')
WEB_PUSH_VAPID_PRIVATE_KEY = os.getenv('WEB_PUSH_VAPID_PRIVATE_KEY', '')
WEB_PUSH_VAPID_SUBJECT = os.getenv('WEB_PUSH_VAPID_SUBJECT', 'mailto:')

# FCM 設定
FCM_PROJECT_ID = os.getenv('FCM_PROJECT_ID', '')
FCM_SERVICE_ACCOUNT_FILE = os.getenv('FCM_SERVICE_ACCOUNT_FILE', '')
FCM_SERVICE_ACCOUNT_JSON = os.getenv('FCM_SERVICE_ACCOUNT_JSON', '')
