# Generated by Django 5.2.9 on 2026-09-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_aitoolpolicy_tool_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek API'), ('qwen', 'ローカルQwen'), ('openrouter', 'OpenRouter（評価用）')], max_length=30, unique=True),
        ),
    ]
