# Generated by Django 5.2.9 on 2026-09-30 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_aidatapolicy_allow_external_image_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_context', models.CharField(blank=True, default='', max_length=40, verbose_name='起点画面')),
                ('provider', models.CharField(blank=True, default='', max_length=30, verbose_name='最後に使用したプロバイダ')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='会話タイトル')),
                ('messages', models.JSONField(default=list, verbose_name='会話内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
            ],
            options={
                'verbose_name': '社内AI会話履歴',
                'verbose_name_plural': '社内AI会話履歴',
                'db_table': 'ai_conversation',
                'ordering': ['-updated_at'],
            },
        ),
    ]
