# Generated by Django 5.2.9 on 2026-09-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_aiconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidatapolicy',
            name='conversation_retention_days',
            field=models.PositiveIntegerField(default=0, verbose_name='会話履歴の保存期間(日、0は無期限)'),
        ),
    ]
