# Generated by Django 5.2.9 on 2026-10-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0019_aicrossscreenaccesspolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicrossscreenaccesspolicy',
            options={
                'ordering': ['source_screen_id', 'target_screen_id'],
                'verbose_name': 'AI横断参照定義',
                'verbose_name_plural': 'AI横断参照定義',
            },
        ),
    ]
