# Generated by Django 5.2.9 on 2026-10-04 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0023_aiproviderconfig_analysis_plan_timeout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=64, verbose_name='分析案ID')),
                ('template_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='テンプレートID')),
                ('template_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='テンプレート版')),
                ('views', models.JSONField(default=list, verbose_name='利用ビュー・取得列')),
                ('date_from', models.DateField(verbose_name='期間開始')),
                ('date_to', models.DateField(verbose_name='期間終了')),
                ('conditions', models.TextField(blank=True, default='', verbose_name='条件')),
                ('method_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='分析案の承認日時')),
                ('data_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='データ範囲の承認日時')),
                ('approved_counts', models.JSONField(blank=True, null=True, verbose_name='承認時の件数')),
                ('snapshot_counts', models.JSONField(blank=True, null=True, verbose_name='実行時のスナップショットのCOUNT')),
                ('fetched_rows', models.JSONField(blank=True, null=True, verbose_name='1回目の取得行数')),
                ('sent_rows', models.JSONField(blank=True, null=True, verbose_name='2回目の送信行数')),
                ('loaded_rows', models.JSONField(blank=True, null=True, verbose_name='コンテナへの投入行数')),
                ('unique_key_check', models.JSONField(blank=True, null=True, verbose_name='一意キー重複の確認結果')),
                ('sql_sha256', models.CharField(blank=True, max_length=64, null=True, verbose_name='SQLのハッシュ(別のSQLがない実行はNULL)')),
                ('python_sha256', models.CharField(blank=True, max_length=64, null=True, verbose_name='Pythonのハッシュ(コードを作る前に終わった実行はNULL)')),
                ('settings_snapshot', models.JSONField(default=dict, verbose_name='実行時の設定値')),
                ('status', models.CharField(choices=[('running', '実行中'), ('success', '成功'), ('failed', '失敗'), ('cancelled', '中止'), ('expired', '期限切れ'), ('unknown', '生存確認失敗・状態不明')], default='running', max_length=20, verbose_name='状態')),
                ('reason', models.CharField(blank=True, default='', max_length=80, verbose_name='失敗理由コード')),
                ('detail', models.CharField(blank=True, default='', max_length=300, verbose_name='理由の説明(データを含まない)')),
                ('cleanup', models.JSONField(default=dict, verbose_name='後始末の結果(closed / pending / failed)')),
                ('worker_id', models.CharField(max_length=120, verbose_name='実行を担当するプロセス')),
                ('heartbeat_at', models.DateTimeField(verbose_name='生存確認の最終更新')),
                ('started_at', models.DateTimeField(verbose_name='開始')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='取得完了')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信完了')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='終了')),
                ('fetch_seconds', models.FloatField(blank=True, null=True, verbose_name='取得の所要秒')),
                ('transfer_seconds', models.FloatField(blank=True, null=True, verbose_name='送信の所要秒')),
                ('launcher_seconds', models.FloatField(blank=True, null=True, verbose_name='launcherの実行・応答待ちの秒')),
                ('container_load_seconds', models.FloatField(blank=True, null=True, verbose_name='コンテナ内の投入の秒')),
                ('python_seconds', models.FloatField(blank=True, null=True, verbose_name='Python実行の秒')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_runs', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
            ],
            options={
                'verbose_name': 'AI分析実行履歴',
                'verbose_name_plural': 'AI分析実行履歴',
                'db_table': 'ai_analysis_run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='ai_run_user_started'), models.Index(fields=['status', 'heartbeat_at'], name='ai_run_status_heartbeat')],
            },
        ),
    ]
