# Generated by Django 5.2.9 on 2026-10-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0024_aianalysisrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisrun',
            name='loaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='投入完了(コンテナ内の件数・一意キーの照合を含む)'),
        ),
    ]
