# Generated by Django 5.2.9 on 2026-10-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0025_aianalysisrun_loaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisrun',
            name='executed_code_sha256',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='コンテナへ送ったコード全体(固定外枠を含む)のハッシュ'),
        ),
        migrations.AddField(
            model_name='aianalysisrun',
            name='wrapper_version',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='固定外枠の版'),
        ),
    ]
