# Generated by Django 5.2.9 on 2026-10-04 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0026_aianalysisrun_executed_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.UUIDField(verbose_name='系統ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版')),
                ('source_plan_id', models.CharField(max_length=64, verbose_name='元の分析案ID')),
                ('source_plan_revision', models.PositiveIntegerField(verbose_name='元の分析案の承認版')),
                ('name', models.CharField(max_length=300, verbose_name='名称')),
                ('purpose', models.TextField(verbose_name='分析目的')),
                ('procedure', models.JSONField(verbose_name='分析手順')),
                ('output_spec', models.JSONField(verbose_name='出力案')),
                ('conditions', models.TextField(blank=True, default='', verbose_name='条件')),
                ('datasets', models.JSONField(verbose_name='利用ビュー・承認列')),
                ('date_from', models.DateField(verbose_name='期間開始')),
                ('date_to', models.DateField(verbose_name='期間終了')),
                ('sql_steps', models.JSONField(verbose_name='SQLの手順')),
                ('python_code', models.TextField(verbose_name='承認済みPython')),
                ('wrapper_version', models.CharField(max_length=40, verbose_name='承認時の固定外枠の版')),
                ('sql_sha256', models.CharField(blank=True, max_length=64, null=True, verbose_name='SQLのハッシュ(SQLの手順がなければNULL)')),
                ('python_sha256', models.CharField(max_length=64, verbose_name='Pythonのハッシュ')),
                ('executed_code_sha256', models.CharField(max_length=64, verbose_name='固定外枠を含むコード全体のハッシュ')),
                ('content_sha256', models.CharField(max_length=64, verbose_name='承認対象全体のハッシュ')),
                ('method_approved_at', models.DateTimeField(verbose_name='手順の承認日時')),
                ('data_approved_at', models.DateTimeField(verbose_name='データ範囲の承認日時')),
                ('code_approved_at', models.DateTimeField(verbose_name='コードの承認日時')),
                ('status', models.CharField(choices=[('pending_admin', '管理者承認待ち'), ('approved', '正式'), ('rejected', '却下'), ('superseded', '置換済み')], default='pending_admin', max_length=20, verbose_name='状態')),
                ('state_revision', models.PositiveIntegerField(default=1, verbose_name='状態の版(競合検出用)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='保存日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_templates', to=settings.AUTH_USER_MODEL, verbose_name='利用者承認を行った人')),
            ],
            options={
                'verbose_name': 'AI分析テンプレート',
                'verbose_name_plural': 'AI分析テンプレート',
                'db_table': 'ai_analysis_template',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'updated_at', 'id'], name='ai_tpl_status_updated'), models.Index(fields=['approved_by', 'created_at', 'id'], name='ai_tpl_user_created')],
                'constraints': [models.UniqueConstraint(fields=('family_id', 'version'), name='ai_tpl_family_version'), models.UniqueConstraint(fields=('source_plan_id', 'source_plan_revision'), name='ai_tpl_source_revision'), models.UniqueConstraint(fields=('source_plan_id', 'content_sha256'), name='ai_tpl_source_content')],
            },
        ),
    ]
