# Generated by Django 5.2.9 on 2026-10-05 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0027_aianalysistemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysistemplate',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='却下理由(管理者が入力。作成者と管理者だけが閲覧)'),
        ),
        migrations.AddField(
            model_name='aianalysistemplate',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='ai.aianalysistemplate', verbose_name='この訂正版が置き換える、却下された版'),
        ),
        migrations.AddField(
            model_name='aianalysistemplate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='承認・却下の日時'),
        ),
        migrations.AddField(
            model_name='aianalysistemplate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_template_reviews', to=settings.AUTH_USER_MODEL, verbose_name='承認・却下した管理者'),
        ),
    ]
