# Generated by Django 5.2.9 on 2026-10-05 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0028_aianalysistemplate_review'),
        ('notifications', '0011_user_request_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisTemplateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('submitted', '確認依頼'), ('approved', '承認'), ('rejected', '却下'), ('superseded', '置換')], max_length=20, verbose_name='種別')),
                ('channel', models.CharField(choices=[('mail', 'メール'), ('pm', 'PM通知')], max_length=10, verbose_name='手段')),
                ('status', models.CharField(choices=[('sent', '送信済み'), ('failed', '失敗'), ('skipped', '送れない')], max_length=10, verbose_name='状態')),
                ('reason', models.CharField(blank=True, default='', max_length=40, verbose_name='固定の理由コード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('pm_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notifications.notification', verbose_name='PM通知')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_template_notifications', to=settings.AUTH_USER_MODEL, verbose_name='宛先ユーザー')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='ai.aianalysistemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': 'AI分析テンプレートの通知',
                'verbose_name_plural': 'AI分析テンプレートの通知',
                'db_table': 'ai_analysis_template_notification',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['template', 'kind', 'created_at', 'id'], name='ai_tplnt_tpl_kind'), models.Index(fields=['status', 'created_at', 'id'], name='ai_tplnt_status')],
            },
        ),
    ]
