# Generated by Django 5.2.9 on 2026-10-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0029_aianalysistemplatenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysistemplate',
            name='category',
            field=models.CharField(choices=[('receipt', '入荷'), ('shipment', '出荷'), ('inventory', '在庫'), ('production', '生産'), ('quality', '品質'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
