# Generated by Django 5.2.9 on 2026-10-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0030_aianalysistemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysistemplate',
            name='parameters',
            field=models.JSONField(blank=True, default=list, verbose_name='変数の定義'),
        ),
    ]
