# Generated by Django 5.2.9 on 2026-10-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0031_aianalysistemplate_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisrun',
            name='refined_from_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refinements', to='ai.aianalysisrun', verbose_name='改良の元の実行'),
        ),
        migrations.AddField(
            model_name='aianalysisrun',
            name='refinement_instruction',
            field=models.TextField(blank=True, null=True, verbose_name='結果の改良の追加の指示'),
        ),
    ]
