# Generated by Django 5.2.9 on 2026-10-07 16:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0032_aianalysisrun_refined_from_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='analysis_temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='分析の温度（0〜1）'),
        ),
    ]
