# Generated by Django 5.2.9 on 2026-09-25 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0068_alter_departmentpermission_resource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='コード')),
                ('order_code', models.CharField(blank=True, default='', max_length=50, verbose_name='発注コード')),
                ('name', models.CharField(max_length=255, verbose_name='品名')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='カテゴリ')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='単位')),
                ('storage_location', models.CharField(blank=True, default='', max_length=100, verbose_name='保管場所')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='在庫数')),
                ('safety_stock', models.IntegerField(default=0, verbose_name='安全在庫')),
                ('order_unit', models.PositiveIntegerField(default=1, verbose_name='発注単位')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='単価')),
                ('image', models.ImageField(blank=True, default='', upload_to='consumables/images/', verbose_name='画像')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '消耗品',
                'verbose_name_plural': '消耗品',
                'db_table': 't_consumable',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='購入先名')),
                ('contact_person', models.CharField(blank=True, default='', max_length=100, verbose_name='担当者')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='メールアドレス')),
                ('address', models.TextField(blank=True, default='', verbose_name='住所')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '消耗品購入先',
                'verbose_name_plural': '消耗品購入先',
                'db_table': 't_consumable_supplier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableDispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='注文書番号')),
                ('business_date', models.DateField(verbose_name='業務日')),
                ('daily_count', models.PositiveIntegerField(default=1, verbose_name='同一購入先の当日回数')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='購入先名')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='明細数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='合計金額')),
                ('status', models.CharField(choices=[('unsent', '未送信'), ('sent', '送信済')], default='unsent', max_length=20, verbose_name='ステータス')),
                ('pdf_file', models.FileField(blank=True, default='', upload_to='consumables/purchase_orders/', verbose_name='PDF')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信日時')),
                ('sent_email', models.CharField(blank=True, default='', max_length=255, verbose_name='送信先')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('approval_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_dispatch_order', to='accounts.approvalrequest', verbose_name='承認申請')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_orders', to='consumables.consumablesupplier', verbose_name='購入先')),
            ],
            options={
                'verbose_name': '消耗品注文書',
                'verbose_name_plural': '消耗品注文書',
                'db_table': 't_consumable_dispatch_order',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(blank=True, default='', max_length=100, verbose_name='事業部')),
                ('group_name', models.CharField(blank=True, default='', max_length=100, verbose_name='係')),
                ('team_name', models.CharField(blank=True, default='', max_length=100, verbose_name='班')),
                ('unit_name', models.CharField(blank=True, default='', max_length=100, verbose_name='グループ')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='単価')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='金額')),
                ('deadline', models.CharField(choices=[('最短', '最短'), ('通常', '通常'), ('余裕あり', '余裕あり')], default='通常', max_length=20, verbose_name='納期')),
                ('requester_name', models.CharField(blank=True, default='', max_length=100, verbose_name='依頼者名')),
                ('request_type', models.CharField(choices=[('manual', '手動'), ('auto', '自動')], default='manual', max_length=10, verbose_name='依頼種別')),
                ('status', models.CharField(choices=[('requested', '依頼中'), ('preparing', '発注準備'), ('ordered', '発注済'), ('received', '入庫済'), ('rejected', '却下'), ('cancelled', 'キャンセル')], default='requested', max_length=20, verbose_name='ステータス')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('requested_at', models.DateTimeField(verbose_name='依頼日時')),
                ('ordered_at', models.DateTimeField(blank=True, null=True, verbose_name='発注日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='consumables.consumable', verbose_name='消耗品')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_requests', to=settings.AUTH_USER_MODEL, verbose_name='依頼者')),
            ],
            options={
                'verbose_name': '消耗品注文依頼',
                'verbose_name_plural': '消耗品注文依頼',
                'db_table': 't_consumable_request',
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableDispatchOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='コード')),
                ('order_code', models.CharField(blank=True, default='', max_length=50, verbose_name='発注コード')),
                ('name', models.CharField(max_length=255, verbose_name='品名')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='単位')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='単価')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='金額')),
                ('deadline', models.CharField(blank=True, default='', max_length=20, verbose_name='納期')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='consumables.consumable', verbose_name='消耗品')),
                ('dispatch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consumables.consumabledispatchorder', verbose_name='注文書')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_items', to='consumables.consumablerequest', verbose_name='元の依頼')),
            ],
            options={
                'verbose_name': '消耗品注文書明細',
                'verbose_name_plural': '消耗品注文書明細',
                'db_table': 't_consumable_dispatch_order_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(blank=True, default='', max_length=100, verbose_name='事業部')),
                ('group_name', models.CharField(blank=True, default='', max_length=100, verbose_name='係')),
                ('team_name', models.CharField(blank=True, default='', max_length=100, verbose_name='班')),
                ('unit_name', models.CharField(blank=True, default='', max_length=100, verbose_name='グループ')),
                ('movement_type', models.CharField(choices=[('inbound', '入庫'), ('outbound', '出庫')], max_length=10, verbose_name='区分')),
                ('inbound_type', models.CharField(blank=True, choices=[('manual', '手動'), ('dispatch', '発注分')], default='', max_length=10, verbose_name='入庫種別')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('stock_after', models.IntegerField(verbose_name='処理後在庫')),
                ('worker_name', models.CharField(blank=True, default='', max_length=100, verbose_name='作業者名')),
                ('usage_line', models.CharField(blank=True, default='', max_length=100, verbose_name='使用ライン')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='単価')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='金額')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('moved_at', models.DateTimeField(verbose_name='処理日時')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='consumables.consumable', verbose_name='消耗品')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='consumables.consumablerequest', verbose_name='対象の依頼')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_movements', to=settings.AUTH_USER_MODEL, verbose_name='作業者')),
            ],
            options={
                'verbose_name': '消耗品入出庫履歴',
                'verbose_name_plural': '消耗品入出庫履歴',
                'db_table': 't_consumable_stock_movement',
                'ordering': ['-moved_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='consumable',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='consumables.consumablesupplier', verbose_name='購入先'),
        ),
        migrations.AddIndex(
            model_name='consumablerequest',
            index=models.Index(fields=['status'], name='t_consumabl_status_b25dea_idx'),
        ),
        migrations.AddIndex(
            model_name='consumablerequest',
            index=models.Index(fields=['requested_at'], name='t_consumabl_request_3772b5_idx'),
        ),
        migrations.AddIndex(
            model_name='consumablestockmovement',
            index=models.Index(fields=['movement_type', 'moved_at'], name='t_consumabl_movemen_8cba4c_idx'),
        ),
        migrations.AddIndex(
            model_name='consumablestockmovement',
            index=models.Index(fields=['consumable', 'moved_at'], name='t_consumabl_consuma_b57e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['name'], name='t_consumabl_name_c643fd_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['category'], name='t_consumabl_categor_52b5bd_idx'),
        ),
    ]
