# Generated by Django 5.2.9 on 2026-09-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumabledispatchorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入庫日時'),
        ),
        migrations.AlterField(
            model_name='consumabledispatchorder',
            name='status',
            field=models.CharField(choices=[('unsent', '未送信'), ('sent', '送信済'), ('received', '入庫済')], default='unsent', max_length=20, verbose_name='ステータス'),
        ),
    ]
