# Generated by Django 5.2.9 on 2026-09-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0002_consumabledispatchorder_received_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablestockmovement',
            name='movement_type',
            field=models.CharField(choices=[('inbound', '入庫'), ('outbound', '出庫'), ('adjustment', '在庫調整')], max_length=10, verbose_name='区分'),
        ),
    ]
