# Generated by Django 5.2.9 on 2026-09-26 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0003_alter_consumablestockmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableOrderEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='', verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cc_users', models.ManyToManyField(blank=True, related_name='consumable_order_email_configs', to=settings.AUTH_USER_MODEL, verbose_name='CCユーザー')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_email_config', to='consumables.consumablesupplier', verbose_name='購入先')),
            ],
            options={
                'verbose_name': '消耗品注文書メール設定',
                'verbose_name_plural': '消耗品注文書メール設定',
                'db_table': 't_consumable_order_email_config',
                'ordering': ['supplier__name'],
            },
        ),
    ]
