# Generated by Django 5.2.9 on 2026-05-20 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0053_seed_manual_documents'),
        ('orders', '0055_pseudo_truck_product_add_ship_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentActual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shipment_date', models.DateField(verbose_name='出荷日')),
                ('product_code', models.CharField(max_length=50, verbose_name='品番コード')),
                ('customer_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='得意先コード')),
                ('ship_to_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='納入先コード')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='出荷実績数')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer', verbose_name='得意先')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '出荷実績',
                'verbose_name_plural': '出荷実績',
                'db_table': 't_shipment_actual',
            },
        ),
        migrations.CreateModel(
            name='ShipmentActualHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', '作成'), ('UPDATE', '更新'), ('DELETE', '削除')], max_length=10, verbose_name='操作')),
                ('shipment_date', models.DateField(verbose_name='出荷日')),
                ('product_code', models.CharField(max_length=50, verbose_name='品番コード')),
                ('customer_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='得意先コード')),
                ('ship_to_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='納入先コード')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='出荷実績数')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('shipment_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='shipping.shipmentactual', verbose_name='出荷実績')),
            ],
            options={
                'verbose_name': '出荷実績履歴',
                'verbose_name_plural': '出荷実績履歴',
                'db_table': 't_shipment_actual_history',
            },
        ),
        migrations.CreateModel(
            name='ShipToLeadTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ship_to_code', models.CharField(max_length=40, verbose_name='納入先コード')),
                ('ship_to_name', models.CharField(blank=True, default='', max_length=100, verbose_name='納入地名')),
                ('additional_days', models.PositiveIntegerField(default=0, verbose_name='出荷加算日数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.customer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '納入地別出荷加算日数',
                'verbose_name_plural': '納入地別出荷加算日数',
                'db_table': 'm_ship_to_lead_time',
                'ordering': ['customer__customer_code', 'ship_to_code'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(verbose_name='出荷日')),
                ('order_quantity', models.IntegerField(verbose_name='受注数量')),
                ('shipped_quantity', models.IntegerField(default=0, verbose_name='出荷済数量')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='受注')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '出荷進捗',
                'verbose_name_plural': '出荷進捗',
                'db_table': 't_delivery_progress',
                'indexes': [models.Index(fields=['order_date'], name='t_delivery__order_d_c16dd1_idx'), models.Index(fields=['product'], name='t_delivery__product_6386b6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shipmentactual',
            index=models.Index(fields=['shipment_date'], name='t_shipment__shipmen_6a1e16_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentactual',
            index=models.Index(fields=['product_code'], name='t_shipment__product_b3d76c_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentactual',
            index=models.Index(fields=['customer_code'], name='t_shipment__custome_3e3ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentactual',
            index=models.Index(fields=['ship_to_code'], name='t_shipment__ship_to_e6ab81_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentactualhistory',
            index=models.Index(fields=['shipment_actual', 'created_at'], name='t_shipment__shipmen_19135a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shiptoleadtime',
            unique_together={('customer', 'ship_to_code')},
        ),
    ]
