# Generated by Django 5.2.9 on 2026-07-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0064_add_identification_code_and_sei_ban'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiptoleadtime',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.calendar', verbose_name='カレンダ'),
        ),
    ]
