# Generated by Django 5.2.9 on 2026-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_add_calendar_to_shiptoleadtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubotaSakaiDeliveryProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_date', models.DateField(verbose_name='日付')),
                ('product_code', models.CharField(max_length=50, verbose_name='製品コード')),
                ('ship_to_code', models.CharField(max_length=40, verbose_name='納入地コード')),
                ('demand_qty', models.IntegerField(default=0, verbose_name='需要数')),
                ('assigned_qty', models.IntegerField(default=0, verbose_name='便振分数')),
                ('adjust_qty', models.IntegerField(default=0, verbose_name='調整数')),
                ('progress_qty', models.IntegerField(default=0, verbose_name='進捗')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'クボタ堺配送進捗',
                'verbose_name_plural': 'クボタ堺配送進捗',
                'db_table': 't_kubota_sakai_delivery_progress',
                'indexes': [models.Index(fields=['product_code', 'ship_to_code', 'plan_date'], name='t_kubota_sa_product_0346f8_idx')],
                'unique_together': {('plan_date', 'product_code', 'ship_to_code')},
            },
        ),
    ]
