# Generated by Django 5.2.9 on 2026-07-12 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0064_add_identification_code_and_sei_ban'),
        ('orders', '0055_pseudo_truck_product_add_ship_to'),
        ('shipping', '0005_shipmentactualsplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentactual',
            name='shipping_trip_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_actuals', to='orders.shippingtripallocation', verbose_name='出荷便割付'),
        ),
        migrations.AddIndex(
            model_name='shipmentactual',
            index=models.Index(fields=['shipping_trip_allocation'], name='t_shipment__shippin_66fa80_idx'),
        ),
    ]
