# Generated by Django 5.2.9 on 2026-07-12 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_pseudo_truck_product_add_ship_to'),
        ('shipping', '0006_shipmentactual_shipping_trip_allocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingTripAllocationSplit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField(default=1, verbose_name='行番号')),
                ('production_date', models.DateField(verbose_name='生産日')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='数量')),
                ('source_order_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='注番')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('shipping_trip_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_splits', to='orders.shippingtripallocation', verbose_name='出荷便割付')),
            ],
            options={
                'verbose_name': '便割付内訳',
                'verbose_name_plural': '便割付内訳',
                'db_table': 't_shipping_trip_allocation_split',
                'ordering': ['shipping_trip_allocation_id', 'line_no', 'id'],
                'indexes': [models.Index(fields=['shipping_trip_allocation', 'line_no'], name='t_shipping__shippin_0527b0_idx'), models.Index(fields=['production_date'], name='t_shipping__product_1f2e50_idx'), models.Index(fields=['source_order_no'], name='t_shipping__source__ea2ad9_idx')],
            },
        ),
    ]
