# Generated by Django 5.2.9 on 2026-07-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_shippingtripallocationsplit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_date', models.DateField(verbose_name='日付')),
                ('product_code', models.CharField(max_length=50, verbose_name='製品コード')),
                ('customer_code', models.CharField(max_length=20, verbose_name='得意先コード')),
                ('ship_to_code', models.CharField(default='', max_length=40, verbose_name='納入先コード')),
                ('forecast_qty', models.IntegerField(default=0, verbose_name='内示数')),
                ('firm_qty', models.IntegerField(default=0, verbose_name='確定数')),
                ('actual_qty', models.IntegerField(default=0, verbose_name='実績数')),
                ('adjust_qty', models.IntegerField(default=0, verbose_name='調整数')),
                ('progress_qty', models.IntegerField(default=0, verbose_name='累積進度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '出荷進度',
                'verbose_name_plural': '出荷進度',
                'db_table': 't_shipping_progress',
                'indexes': [models.Index(fields=['product_code', 'customer_code', 'ship_to_code', 'plan_date'], name='t_shipping__product_6cf6db_idx')],
                'unique_together': {('plan_date', 'product_code', 'customer_code', 'ship_to_code')},
            },
        ),
    ]
