# Generated by Django 5.2.9 on 2026-07-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_shippingprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentactualhistory',
            name='action',
            field=models.CharField(choices=[('CREATE', '作成'), ('UPDATE', '更新'), ('UPDATE_BEFORE', '更新前'), ('UPDATE_AFTER', '更新後'), ('DELETE', '削除')], max_length=15, verbose_name='操作'),
        ),
    ]
