# Generated by Django 5.2.9 on 2026-08-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_shiptoleadtimecolorexclusion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiptoleadtimecolorexclusion',
            options={'ordering': ['ship_to_lead_time_id', 'product_code'], 'verbose_name': '納入地色設定適用品番', 'verbose_name_plural': '納入地色設定適用品番'},
        ),
    ]
